'use client';
import StoryCard from './story-card';
import {useEffect,useState} from 'react';
import type {JournalPlace} from '@/lib/catalog-views';
import {readJournal,writeJournal,removePause,journalEvent,type RestRecord} from '@/lib/rest-journal';
import {countries,countryCodes,countryCode} from '@/lib/countries';
import {trackEngagement} from '@/lib/engagement-client';
import {loadGeo} from '@/lib/geo-client';
export default function Journal({language}:{language:'ko'|'en'}){const ko=language==='ko',text=(kr:string,en:string)=>ko?kr:en;const [records,setRecords]=useState<RestRecord[]>([]),[ready,setReady]=useState(false),[filter,setFilter]=useState<'all'|'visited'|'planned'>('all'),[confirm,setConfirm]=useState(false),[notice,setNotice]=useState('');const [geo,setGeo]=useState<any>(null),[world,setWorld]=useState<any>(null);useEffect(()=>{function refresh(){setRecords(readJournal());setReady(true);}refresh();window.addEventListener(journalEvent,refresh);try{trackEngagement('journal_open',countryCode(localStorage.getItem('nhp-last-country')));}catch{}Promise.all([loadGeo(),fetch('/maps/world.json').then(r=>r.json())]).then(([g,w])=>{setGeo(()=>g);setWorld(w);}).catch(()=>{});return()=>window.removeEventListener(journalEvent,refresh);},[]);const [places,setPlaces]=useState<JournalPlace[]>([]),[placeState,setPlaceState]=useState('loading'),[retry,setRetry]=useState(0);
 const hasRecords=records.length>0;
 // Load the same public display-only chunk for everyone. Local record IDs,
 // dates, visit states and noise responses never become request parameters.
 useEffect(()=>{let live=true;if(!hasRecords){setPlaces([]);setPlaceState('ready');return;}setPlaceState('loading');
  import('@/lib/journal-places.json').then(({default:catalog})=>{if(live){setPlaces(catalog as JournalPlace[]);setPlaceState('ready');}}).catch(()=>{if(live)setPlaceState('error');});
  return()=>{live=false;};
 },[hasRecords,retry]);
 const shown=records.filter(r=>filter==='all'||r.state===filter);const visited=records.filter(r=>r.state==='visited');const projection=geo?.geoNaturalEarth1().scale(130).translate([450,250]),path=geo?.geoPath(projection);async function clear(){try{const res=await fetch('/api/quick-feedback',{method:'DELETE',headers:{'Content-Type':'application/json'},body:'{}'});if(!res.ok)throw Error();if(!writeJournal([]))throw Error();setConfirm(false);setNotice(text('이 기기의 쉼 기록과 이 브라우저의 간단 후기를 삭제했어요.','Deleted this device’s journal and this browser’s quick responses.'));}catch{setNotice(text('삭제하지 못했어요. 연결 상태를 확인하고 다시 시도해 주세요.','Unable to delete. Check your connection and try again.'));}}
 return <main className="journal-page"><header><a className="brand" href={'/?lang='+language}>Not<span>_</span>Hotplace</a><a href={'/guides?lang='+language}>{text('새로운 쉼 찾기','Find another pause')} ↗</a></header><span className="place-eyebrow">MY LITTLE PAUSES.</span><h1>{text('내가 쉬어간 곳.','Places I paused.')}</h1><p>{text('다녀온 쉼과 다음에 가보고 싶은 곳을 모아요. 로그인 없이 이 기기에만 저장됩니다.','Keep places you visited and places you might try. Your journal stays on this device without sign-in.')}</p><div className="journal-summary"><strong>{visited.length}<span>{text('다녀온 곳','Visited')}</span></strong><strong>{records.filter(r=>r.state==='planned').length}<span>{text('지도에서 살펴본 곳','Opened in maps')}</span></strong><strong>{new Set(visited.flatMap(r=>{const p=places.find(p=>p.id===r.placeId);return p?[p.country||'KR']:[];})).size}<span>{text('나라','Countries')}</span></strong></div>
 {visited.some(r=>{const p=places.find(p=>p.id===r.placeId);return p?.lat!=null&&p.lon!=null;})&&<section className="journal-map" aria-label={text('내 쉼 지도','My rest map')}><h2>{text('나만의 쉼 지도','My rest map')}</h2><p>{text('좌표가 확인된 장소를 표시해요. 나머지 기록은 아래 목록에서 확인할 수 있어요.','Places with known coordinates are shown. All records are in the list below.')}</p><svg viewBox="0 0 900 500" role="img" aria-label={text('실제 방문을 기록한 장소 지도','Map of places you recorded visiting')}>{geo&&world?.features.map((f:any,i:number)=><path key={i} d={path(f)||''}/>)}{geo&&visited.map(r=>{const p=places.find(p=>p.id===r.placeId);if(!p||p.lat==null||p.lon==null)return null;const point=projection([p.lon,p.lat]);return <a key={p.id} href={'/places/'+p.id+'/'+language}><circle cx={point[0]} cy={point[1]} r="5"><title>{p.name}</title></circle></a>;})}</svg></section>}
 <StoryCard records={records.filter(r=>places.some(p=>p.id===r.placeId))} places={places} language={language}/>{!!records.length&&placeState==='loading'&&<p role="status">{text('장소 정보를 불러오는 중…','Loading place details…')}</p>}{placeState==='error'&&<p role="status">{text('장소 정보를 불러오지 못했어요. 기기 기록은 그대로 보관되어 있어요.','Place details could not load. Your local records are still saved.')} <button className="place-secondary" onClick={()=>setRetry(n=>n+1)}>{text('다시 불러오기','Try again')}</button></p>}<nav className="journal-filters" aria-label={text('기록 필터','Journal filters')}>{(['all','visited','planned'] as const).map((v,i)=><button key={v} type="button" aria-pressed={filter===v} onClick={()=>setFilter(v)}>{ko?['전체','다녀온 쉼','가보고 싶은 곳'][i]:['All','Visited','To explore'][i]}</button>)}</nav>{!ready&&<p role="status">{text('기록을 불러오는 중…','Loading your journal…')}</p>}{ready&&!shown.length&&<div className="journal-empty"><h2>{text('오늘의 첫 쉼을 남겨볼까요?','Record your first pause.')}</h2><p>{text('장소 페이지에서 다녀온 후 조용함을 한 번 눌러주세요. 지도 열기는 가보고 싶은 곳으로만 남겨요.','After visiting, tap a noise response on a place page. Opening maps only records a place to explore.')}</p><a className="place-primary" href={'/kr?lang='+language}>{text('장소 찾아보기','Explore places')}</a></div>}
 {countryCodes.map(country=>{const rows=shown.filter(r=>places.some(p=>p.id===r.placeId&&(p.country||'KR')===country));return !!rows.length&&<section key={country}><h2>{ko?countries[country].nameKo:countries[country].nameEn}</h2><div className="journal-grid">{rows.map(r=>{const p=places.find(p=>p.id===r.placeId)!;return <article key={r.placeId}>{p.image&&<img src={p.image} alt="" loading="lazy"/>}<div><small>{p.area} · {text(r.state==='visited'?'다녀온 쉼':'가보고 싶은 곳',r.state==='visited'?'Visited':'To explore')}</small><h3><a href={'/places/'+p.id+'/'+language}>{p.name}</a></h3><p>{r.noise?(ko?r.noise:({조용함:'Quiet',보통:'Moderate',시끄러움:'Loud'})[r.noise]):text('실제 방문 여부를 알려주세요.','Let us know after a visit.')}</p><time dateTime={new Date(r.at).toISOString()}>{new Date(r.at).toLocaleDateString(ko?'ko-KR':'en-US',{timeZone:'Asia/Seoul'})} · {text('기록일','Recorded')}</time><div className="quick-footer"><a href={'/places/'+p.id+'/'+language+'#reviews'}>{text(r.state==='visited'?'다시 살펴보기':'다녀왔어요 · 한 번 누르기',r.state==='visited'?'View place':'Visited? Leave one tap')}</a><button type="button" onClick={()=>{if(!removePause(p.id))setNotice(text('기록을 지우지 못했어요.','Unable to remove the record.'));}}>{text('기기 기록 삭제','Remove local record')}</button></div></div></article>;})}</div></section>;})}
 {placeState==='error'&&<div className="journal-grid">{shown.filter(r=>!places.some(p=>p.id===r.placeId)).map(r=><article key={r.placeId}><div><small>{text(r.state==='visited'?'다녀온 쉼':'가보고 싶은 곳',r.state==='visited'?'Visited':'To explore')}</small><h3><a href={'/places/'+encodeURIComponent(r.placeId)+'/'+language}>{r.placeId}</a></h3><time dateTime={new Date(r.at).toISOString()}>{new Date(r.at).toLocaleDateString(ko?'ko-KR':'en-US',{timeZone:'Asia/Seoul'})} · {text('기록일','Recorded')}</time><div className="quick-footer"><button type="button" onClick={()=>{if(!removePause(r.placeId))setNotice(text('기록을 지우지 못했어요.','Unable to remove the record.'));}}>{text('기기 기록 삭제','Remove local record')}</button></div></div></article>)}</div>}
 <footer><p>{text('브라우저 데이터를 지우거나 다른 기기를 사용하면 이 기록이 보이지 않아요. 공개 간단 후기는 최대 90일 동안 별도로 보관됩니다. 로그인 상세 후기·저장 목록은 계정에서 관리해요.','Clearing browser data or changing devices removes access to this journal. Public quick responses are retained for up to 90 days. Account reviews and saved places are managed separately.')}</p>{confirm?<div className="journal-confirm"><p>{text('이 기기의 모든 쉼 기록과 이 브라우저의 공개 간단 후기를 삭제할까요?','Delete all local records and this browser’s public quick responses?')}</p><button className="place-secondary" onClick={()=>setConfirm(false)}>{text('취소','Cancel')}</button><button className="place-primary" onClick={()=>void clear()}>{text('모두 삭제','Delete all')}</button></div>:<button className="place-secondary" onClick={()=>setConfirm(true)}>{text('기록과 간단 후기 모두 삭제','Delete journal and quick responses')}</button>}<p role="status">{notice}</p><a href={'/privacy?lang='+language}>{text('개인정보 처리방침','Privacy notice')}</a></footer></main>;
}
