'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {JournalPlace} from '@/lib/catalog-views';
import type {RestRecord} from '@/lib/rest-journal';
import {storySelection,storyCaption} from '@/lib/story-card';
import {trackEngagement} from '@/lib/engagement-client';
export default function StoryCard({records,places,language}:{records:RestRecord[];places:JournalPlace[];language:'ko'|'en'}){
 const ko=language==='ko',text=(kr:string,en:string)=>ko?kr:en,[open,setOpen]=useState(false),[selected,setSelected]=useState<string[]>([]),[includeDate,setDate]=useState(false),[includeNoise,setNoise]=useState(false),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null),preview=useRef<HTMLCanvasElement>(null),file=useRef<File|null>(null),generation=useRef(0);
 useEffect(()=>{if(!open)return;const current=++generation.current;setReady(false);file.current=null;setNotice('');let live=true;
 async function paint(){await document.fonts.ready;const c=document.createElement('canvas');c.width=1080;c.height=1920;const ctx=c.getContext('2d');if(!ctx)throw Error();canvas.current=c;ctx.fillStyle='#101c17';ctx.fillRect(0,0,1080,1920);ctx.fillStyle='#d1ff73';ctx.font='700 38px sans-serif';ctx.fillText('Not_Hotplace',88,140);ctx.font='700 78px sans-serif';ctx.fillText(ko?'내 속도로, 쉬어가기.':'A pause at my pace.',88,258);ctx.fillStyle='#a7b9ad';ctx.font='28px sans-serif';ctx.fillText(ko?'내가 고른 작은 쉼.':'Little pauses I chose.',88,316);
 const rows=storySelection(records,selected,places);let y=380;const height=rows.length===1?1160:rows.length===2?620:415;
 function wrap(value:string,x:number,start:number,width:number,size:number,color:string,maxLines=4){ctx!.font='400 '+size+'px sans-serif';ctx!.fillStyle=color;const chars=Array.from(value);let line='',n=0;for(const char of chars){if(ctx!.measureText(line+char).width>width){ctx!.fillText(line,x,start+n*(size+10));n++;line='';if(n>=maxLines)return;}line+=char;}if(line)ctx!.fillText(line,x,start+n*(size+10));}
 for(const {record,place} of rows){ctx.fillStyle='#20332a';ctx.fillRect(70,y,940,height);ctx.fillStyle='#a9bfaf';ctx.font='25px sans-serif';ctx.fillText(place.area,104,y+48);wrap(place.name,104,y+108,866,rows.length===1?47:35,'#f1f5ee',2);const titleLines=Math.ceil(ctx.measureText(place.name).width/866);let lineY=y+136+(titleLines>1?45:0);
 const licensed=!!place.image&&!!place.imageCredit&&/^(Type1|CC BY [0-9.]|CC0|public domain)/i.test(place.imageLicense||'')&&place.image!.startsWith('/')&&!place.image!.startsWith('//');
 if(licensed&&rows.length<=2){try{const img=new Image();img.src=place.image!;await img.decode();const boxHeight=rows.length===1?660:rows.length===2?150:130,scale=Math.min(866/img.naturalWidth,boxHeight/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,104+(866-w)/2,lineY,w,h);lineY+=boxHeight+28;wrap(place.imageCredit+' · '+place.imageLicense,104,lineY,866,18,'#afc4b7',2);lineY+=55;}catch{}}
 wrap(storyCaption(record,language,includeNoise),104,lineY+12,866,26,'#d1ff73',2);lineY+=62;if(includeDate){ctx.font='24px sans-serif';ctx.fillStyle='#a7b9ad';ctx.fillText(text('기록일: ','Recorded: ')+new Date(record.at).toLocaleDateString(ko?'ko-KR':'en-US',{timeZone:'Asia/Seoul'}),104,lineY);lineY+=45;}wrap('nothotplace.com/places/'+place.id+'/'+language,104,lineY+7,866,18,'#a7b9ad',3);y+=height+22;}
 ctx.fillStyle='#d1ff73';ctx.font='700 32px sans-serif';ctx.fillText('WE WANT REST.',88,1784);ctx.fillStyle='#a7b9ad';ctx.font='21px sans-serif';ctx.fillText(text('사진 출처·이용허락은 각 장소 링크에서 확인하세요.','Photo credits and licenses are at each place link.'),88,1835);const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error()),'image/png'));if(!live||generation.current!==current)return;file.current=new File([blob],'NotHotplace-pause.png',{type:'image/png'});if(preview.current){preview.current.width=1080;preview.current.height=1920;preview.current.getContext('2d')?.drawImage(c,0,0);}setReady(rows.length>0);}
 void paint().catch(()=>{if(live)setNotice(text('카드를 만들지 못했어요. 다시 시도해 주세요.','Unable to create the card. Please try again.'));});return()=>{live=false;};
 },[open,selected,includeDate,includeNoise,language,records,places]);
 function download(){if(!file.current)return;const url=URL.createObjectURL(file.current),a=document.createElement('a');a.href=url;a.download=file.current.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);trackEngagement('share',places.find(p=>p.id===selected[0])?.country||'KR');setNotice(text('이미지를 저장했어요. 인스타 스토리에서 사진으로 골라 올리면 됩니다.','Image saved. Choose it as a photo in your Instagram story.'));}
 async function share(){if(!file.current)return;const f=file.current;try{if(navigator.canShare?.({files:[f]})&&navigator.share){await navigator.share({files:[f],title:'NotHotplace'});trackEngagement('share',places.find(p=>p.id===selected[0])?.country||'KR');}else download();}catch(e){if((e as Error).name!=='AbortError')download();}}
 return <><button className="place-secondary" disabled={!records.length} onClick={()=>{setSelected(records.slice(0,1).map(r=>r.placeId));setOpen(true);}}>{text('기록을 골라 스토리 카드 만들기','Choose records for a story card')} ↗</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="nhp-modal story-modal"><DialogTitle>{text('내가 고른 쉼만 공유해요.','Share only the pauses you choose.')}</DialogTitle><DialogDescription>{text('최대 3곳 · 1080×1920 이미지. 날짜·소음은 선택한 경우에만 넣습니다. 사진의 출처 표기는 유지해요.','Up to three places in a 1080×1920 image. Dates and noise are optional. Photo credits are retained.')}</DialogDescription><div className="story-controls"><fieldset className="collection-places"><legend>{text('공유할 기록 선택','Choose records to share')} · {selected.length}/3</legend>{records.map(r=>{const p=places.find(p=>p.id===r.placeId);return p&&<label key={r.placeId}><input type="checkbox" checked={selected.includes(r.placeId)} disabled={!selected.includes(r.placeId)&&selected.length>=3} onChange={e=>setSelected(e.target.checked?[...selected,r.placeId]:selected.filter(id=>id!==r.placeId))}/>{p.name}</label>;})}</fieldset><label><input type="checkbox" checked={includeDate} onChange={e=>setDate(e.target.checked)}/>{text('기록일 포함','Include record date')}</label><label><input type="checkbox" checked={includeNoise} onChange={e=>setNoise(e.target.checked)}/>{text('내 소음 응답 포함','Include my noise response')}</label></div><canvas className="story-preview" ref={preview} aria-label={text('선택한 기록의 공유 이미지 미리보기','Preview of selected records')}/><div className="button-row"><button className="place-primary" disabled={!ready} onClick={()=>void share()}>{text('이미지 공유','Share image')}</button><button className="place-secondary" disabled={!ready} onClick={download}>{text('PNG 저장','Download PNG')}</button></div><p role="status">{notice}</p></DialogContent></Dialog></>;
}
