'use client';
import {useEffect,useState} from 'react';
import {catalog,type Place} from '@/lib/catalog';
import {countries,type CountryCode} from '@/lib/countries';
import {inRegion} from '@/lib/regions';
export default function CommunityEditor({language}:{language:'ko'|'en'}){
 const ko=language==='ko',text=(kr:string,en:string)=>ko?kr:en,[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[places,setPlaces]=useState<Place[]>(catalog);
 const [profile,setProfile]=useState({name:'',country:'KR' as CountryCode,region:'청주',link:'',bio:'',consent:false});
 const [collection,setCollection]=useState({title:'',country:'KR' as CountryCode,region:'청주',placeIds:[] as string[],note:''});
 const status=(s:string)=>ko?({pending:'운영자 검토 중',approved:'공개됨',rejected:'다시 확인이 필요해요'} as Record<string,string>)[s]||s:s;
 async function load(){const r=await fetch('/api/community',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json() as any;setData(d);setProfile(d.profile?{name:d.profile.name,country:d.profile.country,region:d.profile.region,link:d.profile.link,bio:d.profile.bio,consent:false}:{name:'',country:'KR',region:'청주',link:'',bio:'',consent:false});setError('');}
 useEffect(()=>{void load().catch(()=>setError(text('신청 정보를 불러오지 못했어요.','Unable to load your application.')));},[]);
 useEffect(()=>{let live=true;fetch('/api/data?country='+collection.country,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<any>;}).then(d=>{if(live)setPlaces(d.places);}).catch(()=>{if(live)setPlaces(catalog);});return()=>{live=false;};},[collection.country]);
 async function send(payload:object){setBusy(true);setNotice('');try{const r=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error(String(r.status));await load();setNotice(text('저장했어요. 신청·모음은 검토 후 공개됩니다. 공개 철회는 즉시 반영됩니다.','Saved. Applications and collections are reviewed before publishing. Withdrawal hides your profile immediately.'));return true;}catch(e){setNotice((e as Error).message==='401'?text('다시 로그인해 주세요.','Please sign in again.'):(e as Error).message==='429'?text('오늘의 신청 한도에 도달했어요. 모음은 하루 3개까지 제안할 수 있습니다.','Daily limit reached. You can propose up to three collections a day.'):text('입력과 장소 선택을 확인한 뒤 다시 시도해 주세요.','Check your entries and place selection, then try again.'));return false;}finally{setBusy(false);}}
 const options=(country:CountryCode)=>(countries[country].regions as readonly string[]);
 const candidates=places.filter(p=>(p.country||'KR')===collection.country&&inRegion(p,collection.region));
 return <main className="community-page"><header><a className="brand" href={'/?lang='+language}>Not_Hotplace</a><a href={'/contributors?lang='+language}>{text('발견자 모음','Contributor collections')} ↗</a></header><h1>{text('내 지역의 발견자로.','Become a contributor in your region.')}</h1><p>{text('공개할 닉네임과 채널을 직접 골라주세요. 신청만으로 공개되지 않으며, 운영자가 출처와 내용을 확인합니다.','Choose your public nickname and optional channel. The operator checks applications and sources before publication.')}</p>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">{text('신청 정보 확인 중…','Loading your application…')}</p>}
 {data&&!data.signedIn&&<a className="place-primary" href={'/login?lang='+language+'&next='+encodeURIComponent('/contributors/join?lang='+language)}>{text('로그인하고 참여하기','Sign in to participate')}</a>}
 {data?.signedIn&&<><form className="community-form" onSubmit={e=>{e.preventDefault();void send({action:'profile',...profile});}}><h2>{text('공개 프로필 신청','Public profile application')}</h2>{data.profile&&<p>{status(data.profile.status)}{!data.profile.consent&&text(' · 공개 동의 철회됨',' · Consent withdrawn')}{data.profile.reason&&' · '+data.profile.reason}</p>}<label>{text('공개 닉네임','Public nickname')}<input value={profile.name} required minLength={2} maxLength={30} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><div className="community-fields"><label>{text('나라','Country')}<select value={profile.country} onChange={e=>{const c=e.target.value as CountryCode;setProfile({...profile,country:c,region:countries[c].defaultRegion});}}>{Object.entries(countries).map(([id,c])=><option key={id} value={id}>{ko?c.nameKo:c.nameEn}</option>)}</select></label><label>{text('발견할 지역','Your region')}<select value={profile.region} onChange={e=>setProfile({...profile,region:e.target.value})}>{options(profile.country).map(r=><option key={r}>{r}</option>)}</select></label></div><label>{text('내 채널 HTTPS 링크 · 선택','Your channel HTTPS link · optional')}<input type="url" value={profile.link} maxLength={240} placeholder="https://" onChange={e=>setProfile({...profile,link:e.target.value})}/></label><label>{text('어떤 쉼을 찾나요 · 선택','Your kind of pause · optional')}<textarea value={profile.bio} maxLength={160} onChange={e=>setProfile({...profile,bio:e.target.value})}/></label><label className="community-consent"><input type="checkbox" required checked={profile.consent} onChange={e=>setProfile({...profile,consent:e.target.checked})}/>{text('닉네임·지역·소개·채널 링크와 승인된 장소 모음이 사이트에 공개되는 데 동의합니다. 이메일과 계정 ID는 공개하지 않습니다.','I consent to publishing my nickname, region, bio, channel link and approved collections. Email and account ID remain private.')}</label><button className="place-primary" disabled={busy}>{text('프로필 검토 신청','Submit profile for review')}</button>{data.profile?.consent===1&&<button type="button" className="place-secondary" disabled={busy} onClick={()=>void send({action:'withdraw'})}>{text('프로필·모음 공개 철회','Withdraw public profile and collections')}</button>}{data.profile&&<button type="button" className="place-secondary" disabled={busy} onClick={()=>void send({action:'deleteProfile'})}>{text('신청 프로필과 모음 모두 삭제','Delete profile application and collections')}</button>}</form>
 {!!data.profile?.consent&&<form className="community-form" onSubmit={async e=>{e.preventDefault();if(await send({action:'collection',...collection}))setCollection({...collection,title:'',placeIds:[],note:''});}}><h2>{text('작은 쉼 모음 제안','Propose a small collection')}</h2><p>{text('같은 지역의 등록 장소 2~8곳. 이동 경로를 답사했다고 표시하지 말고, 함께 살펴볼 이유와 이용 조건을 알려주세요.','Choose 2–8 registered places in one region. Explain the connection and visiting conditions without implying you have surveyed a route.')}</p><label>{text('모음 제목','Collection title')}<input required minLength={4} maxLength={70} value={collection.title} onChange={e=>setCollection({...collection,title:e.target.value})}/></label><div className="community-fields"><label>{text('나라','Country')}<select value={collection.country} onChange={e=>{const c=e.target.value as CountryCode;setCollection({...collection,country:c,region:countries[c].defaultRegion,placeIds:[]});}}>{Object.entries(countries).map(([id,c])=><option key={id} value={id}>{ko?c.nameKo:c.nameEn}</option>)}</select></label><label>{text('지역','Region')}<select value={collection.region} onChange={e=>setCollection({...collection,region:e.target.value,placeIds:[]})}>{options(collection.country).map(r=><option key={r}>{r}</option>)}</select></label></div><fieldset className="collection-places"><legend>{text('장소 선택','Choose places')} · {collection.placeIds.length}/8</legend>{candidates.map(p=><label key={p.id}><input type="checkbox" checked={collection.placeIds.includes(p.id)} disabled={!collection.placeIds.includes(p.id)&&collection.placeIds.length>=8} onChange={e=>setCollection({...collection,placeIds:e.target.checked?[...collection.placeIds,p.id]:collection.placeIds.filter(id=>id!==p.id)})}/>{p.name}</label>)}</fieldset><label>{text('함께 살펴볼 이유와 방문 조건','Why these places, and visiting conditions')}<textarea required minLength={20} maxLength={600} rows={4} value={collection.note} onChange={e=>setCollection({...collection,note:e.target.value})}/></label><button className="place-primary" disabled={busy||collection.placeIds.length<2}>{text('모음 검토 신청','Submit collection for review')}</button></form>}
 {!!data.ownCollections?.length&&<section><h2>{text('내가 제안한 모음','My proposed collections')}</h2>{data.ownCollections.map((c:any)=><article className="community-proposal" key={c.id}><h3>{c.title}</h3><p>{status(c.status)} · {c.reason}</p><button type="button" className="place-secondary" disabled={busy} onClick={()=>void send({action:'cancel',id:c.id})}>{text('모음 삭제','Delete collection')}</button></article>)}</section>}</>}
 <p role="status">{notice}</p><footer><a href={'/privacy?lang='+language}>{text('개인정보 처리방침','Privacy')}</a></footer></main>;
}
