import type {Metadata} from 'next';
import {db,allPlaces} from '@/lib/store';
import {catalog} from '@/lib/catalog';
import {publicCollection,validCollection} from '@/lib/community';
import {countries,type CountryCode} from '@/lib/countries';
import {SITE_URL} from '@/lib/seo';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'지역 발견자와 쉼 모음 | NotHotplace',description:'내 지역에서 쉬어갈 곳을 함께 발견하고, 방문 조건과 출처를 갖춘 작은 장소 모음을 제안하세요.',alternates:{canonical:SITE_URL+'/contributors'}};
export default async function Contributors({searchParams}:{searchParams:Promise<{lang?:string}>}){
 const language=(await searchParams).lang==='en'?'en':'ko',ko=language==='ko',text=(kr:string,en:string)=>ko?kr:en;let profiles:any[]=[],collections:any[]=[],failed=false;
 try{const [p,c]=await Promise.all([db().prepare("SELECT id,name,country,region,link,bio FROM contributor_profiles WHERE status='approved' AND consent=1 ORDER BY updated_at DESC LIMIT 100").all<any>(),db().prepare("SELECT c.*,p.id profile_id,p.name author,p.link FROM contributor_collections c JOIN contributor_profiles p ON p.user_id=c.user_id WHERE c.status='approved' AND p.status='approved' AND p.consent=1 ORDER BY c.updated_at DESC LIMIT 100").all<any>()]);profiles=p.results;const places=await allPlaces();collections=c.results.filter(row=>{try{return validCollection(places,JSON.parse(row.place_ids),row.country,row.region);}catch{return false;}}).map(publicCollection);}catch{failed=true;}
 return <main className="community-page"><header><a className="brand" href={'/?lang='+language}>Not<span>_</span>Hotplace</a><a href={'/contributors?lang='+(ko?'en':'ko')}>{ko?'EN':'한국어'}</a></header><span className="world-kicker">FOUND AT YOUR OWN PACE.</span><h1>{text('우리 동네의 작은 발견.','Little discoveries, close to home.')}</h1><p>{text('이름난 장소보다 내가 쉬어갈 조건을 함께 찾습니다. 공개에 동의한 발견자의 닉네임과 출처가 있는 장소 모음만 운영자 검토 후 소개해요.','Help find conditions for a better pause. Consenting contributors and sourced place collections are published after operator review.')}</p><a className="place-primary" href={'/contributors/join?lang='+language}>{text('지역 발견자로 참여하기','Become a regional contributor')} ↗</a>
 {failed?<p role="status">{text('발견자 모음을 불러오지 못했어요. 잠시 후 다시 확인해 주세요.','Unable to load collections. Please try again later.')}</p>:<>{!collections.length&&<section className="community-empty"><h2>{text('첫 번째 발견자를 기다리고 있어요.','The first collection is still to come.')}</h2><p>{text('등록된 장소 2~8곳과 왜 함께 쉬기 좋은지 알려주세요. 운영자가 출처·이용 조건을 확인한 뒤 소개합니다.','Choose 2–8 registered places and explain why they belong together. The operator will check sources and visiting conditions.')}</p></section>}
 <div className="community-grid">{collections.map(c=><article key={c.id}><small>{c.region}</small><h2>{c.title}</h2><p>{c.note}</p><ol>{c.placeIds.map((id:string)=>{const p=catalog.find(p=>p.id===id);return <li key={id}><a href={p?'/places/'+id+'/'+language:'/'+c.country.toLowerCase()+'?place='+encodeURIComponent(id)+'&lang='+language}>{p?.name||text('제안으로 등록된 장소 보기','View an approved suggestion')}</a></li>;})}</ol><a href={'#'+c.profileId}>{text('발견자','By')} {c.author}</a></article>)}</div>
 {!!profiles.length&&<section><h2>{text('이 지역을 함께 발견하는 사람들','People discovering their region')}</h2><div className="community-grid">{profiles.map(p=><article id={p.id} key={p.id}><small>{ko?countries[p.country as CountryCode].nameKo:countries[p.country as CountryCode].nameEn} · {p.region}</small><h3>{p.name}</h3><p>{p.bio}</p>{p.link&&<a href={p.link} target="_blank" rel="noopener noreferrer nofollow">{text('발견자의 채널','Contributor’s channel')} ↗</a>}</article>)}</div></section>}</>}
 <footer><a href={'/guides?lang='+language}>{text('목적별 가이드','Pause guides')}</a><a href={'/privacy?lang='+language}>{text('개인정보 처리방침','Privacy')}</a></footer></main>;
}
