import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {findRegionalGuide,regionalPlaces} from '@/lib/regional-guides';
import {catalog} from '@/lib/catalog';
import {countryPath} from '@/lib/countries';
import {SITE_URL} from '@/lib/seo';
import SeoLinks from '@/components/seo-links';
import {placePath,isPlaceLanguage} from '@/lib/place-pages';
import {placeDescription} from '@/lib/place-copy';
import GuideEngagement from '@/app/guides/guide-engagement';
export async function generateMetadata({params}:{params:Promise<{slug:string;language:string}>}):Promise<Metadata>{const {slug,language}=await params,g=findRegionalGuide(slug);if(!g||!isPlaceLanguage(language))return {};const ko=language==='ko',name=ko?g.nameKo:g.nameEn,title=ko?`${name} 카페·정원·산책: 사진과 방문 정보 | NotHotplace`:`${name} cafés, gardens & walks | NotHotplace`,description=ko?g.introKo:g.introEn,path=`/regions/${slug}/${language}`;return {title,description,openGraph:{title,description,url:SITE_URL+path}};}
export default async function Page({params}:{params:Promise<{slug:string;language:string}>}){const {slug,language}=await params,g=findRegionalGuide(slug);if(!g||!isPlaceLanguage(language))notFound();const ko=language==='ko',places=regionalPlaces(g,catalog),name=ko?g.nameKo:g.nameEn,query=new URLSearchParams({lang:language,region:g.region,...(g.area?{q:g.area==='New York City'?'':g.area}:{})});const structured={'@context':'https://schema.org','@type':'ItemList',name:(ko?`${name}의 쉼 후보`:`Places to pause in ${name}`),numberOfItems:places.length,itemListElement:places.map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name,url:SITE_URL+placePath(p.id,language)}))};return <main className="journal-page regional-page"><SeoLinks canonical={`${SITE_URL}/regions/${slug}/${language}`} languages={{ko:`${SITE_URL}/regions/${slug}/ko`,en:`${SITE_URL}/regions/${slug}/en`,'x-default':`${SITE_URL}/regions/${slug}/en`}}/><GuideEngagement country={g.country}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,'\\u003c')}}/><header><a className="brand" href={'/?lang='+language}>Not<span>_</span>Hotplace</a><a href={'/regions/'+slug+'/'+(ko?'en':'ko')}>{ko?'English':'한국어'}</a></header><span className="place-eyebrow">{g.country} / {places.length} {ko?'곳의 방문 후보':'PLACES TO EXPLORE'}</span><h1>{ko?`${name}에서, 잠깐의 쉼.`:`A pause in ${name}.`}</h1><p>{ko?g.introKo:g.introEn}</p><section className="regional-checks"><h2>{ko?'방문 전에 확인해요':'Before your visit'}</h2><ul>{(ko?g.notesKo:g.notesEn).map(n=><li key={n}>{n}</li>)}</ul><p>{ko?'사진·관광자료는 공간의 특징을 보여줍니다. 조용함과 혼잡은 실제 방문 시간에 따라 달라져요.':'Photos and source information describe the setting. Quietness and crowds depend on your visiting time.'}</p><a className="place-primary" href={countryPath(g.country)+'?'+query}>{ko?'지역·조건으로 더 찾아보기':'Explore with region and filters'} ↗</a></section><div className="journal-grid">{places.map(p=><article key={p.id}>{p.image&&<a href={placePath(p.id,language)}><img className="regional-photo" src={p.image} alt={p.name} loading="lazy"/></a>}<div><small>{p.area} · {p.image?(ko?'사진 있음':'Photos available'):(ko?'사진 확인 전':'No photo yet')}</small><h2><a href={placePath(p.id,language)}>{p.name} ↗</a></h2><p>{placeDescription(p,language)}</p>{p.visitDetails?.[0]&&<p className="regional-fact">{ko?p.visitDetails[0].labelKo+': '+p.visitDetails[0].textKo:p.visitDetails[0].labelEn+': '+p.visitDetails[0].textEn}</p>}<small>{ko?'자료 확인':'Source checked'} {p.checked} · {ko?'현장 방문 검증 아님':'Not a field visit'}</small><div className="quick-footer"><a href={placePath(p.id,language)+'#reviews'}>{ko?'다녀왔다면 한 번 눌러 후기 남기기':'Visited? Leave one-tap feedback'}</a></div></div></article>)}</div><footer><a href={'/regions?lang='+language}>{ko?'다른 지역 찾아보기':'Browse other regions'} ↗</a></footer></main>;}
