import {z} from 'zod';
import {db,hasPlace} from '@/lib/store';
import {siteOrigin} from '@/lib/site-auth';
import {koreaDay} from '@/lib/traffic';
const choices=z.object({placeId:z.string().min(1).max(100),noise:z.enum(['조용함','보통','시끄러움']),day:z.enum(['평일','주말·공휴일']).optional(),time:z.enum(['오전','오후','저녁']).optional()}).strict();
const deletion=z.object({placeId:z.string().min(1).max(100).optional()}).strict();
const cookieName='__Host-nhp-reaction';
const headers={'Cache-Control':'private, no-store'};
const reply=(data:unknown,status=200,cookie?:string)=>Response.json(data,{status,headers:{...headers,...(cookie?{'Set-Cookie':`${cookieName}=${cookie}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=7776000`}:{})}});
function token(request:Request){const value=request.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(cookieName+'='))?.slice(cookieName.length+1);return value&&/^[0-9a-f-]{36}$/.test(value)?value:null;}
async function actorHash(value:string){const d=db();await d.prepare('INSERT OR IGNORE INTO quick_feedback_settings(name,value) VALUES(?,?)').bind('salt',crypto.randomUUID()+crypto.randomUUID()).run();const row=await d.prepare('SELECT value FROM quick_feedback_settings WHERE name=?').bind('salt').first<{value:string}>();if(!row)throw new Error('salt');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(row.value),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))).map(b=>b.toString(16).padStart(2,'0')).join('');}
async function allowed(actor:string,max:number){const result=await db().prepare('INSERT INTO quick_feedback_limits(day,actor,total) VALUES(?,?,1) ON CONFLICT(day,actor) DO UPDATE SET total=total+1 WHERE total<?').bind(koreaDay(),actor,max).run();return (result.meta.changes||0)>0;}
function validOrigin(request:Request){return request.headers.get('origin')===siteOrigin()&&request.headers.get('sec-fetch-site')!=='cross-site';}
export async function GET(request:Request){try{const id=new URL(request.url).searchParams.get('place');if(!id||id.length>100||!await hasPlace(id))return reply({error:'Unknown place'},404);const d=db(),cutoff=Date.now()-90*86400000;const summary=await d.prepare("SELECT COUNT(*) count,SUM(CASE WHEN noise='조용함' THEN 1 ELSE 0 END) quiet,SUM(CASE WHEN noise='보통' THEN 1 ELSE 0 END) moderate,SUM(CASE WHEN noise='시끄러움' THEN 1 ELSE 0 END) loud FROM quick_feedback WHERE place_id=? AND updated_at>=?").bind(id,cutoff).first();const ownToken=token(request);const mine=ownToken?await d.prepare('SELECT noise,day,time FROM quick_feedback WHERE actor=? AND place_id=? AND updated_at>=?').bind(await actorHash(ownToken),id,cutoff).first():null;return reply({summary,mine});}catch{return reply({error:'Unavailable'},503);}}
export async function POST(request:Request){try{if(!validOrigin(request))return reply({error:'Forbidden'},403);if(request.headers.get('content-type')!=='application/json')return reply({error:'JSON required'},415);const raw=await request.text();if(raw.length>500)return reply({error:'Too large'},413);const result=choices.safeParse(JSON.parse(raw));if(!result.success)return reply({error:'Invalid response'},400);const {placeId,noise,day,time}=result.data;if(!await hasPlace(placeId))return reply({error:'Unknown place'},404);const previous=token(request),ownToken=previous||crypto.randomUUID(),actor=await actorHash(ownToken);const ip=request.headers.get('cf-connecting-ip');if(ip&&!await allowed(await actorHash('rate:'+koreaDay()+':'+ip),60))return reply({error:'오늘의 응답 한도를 넘었어요. 내일 다시 기록해 주세요.'},429);if(!await allowed(actor,12))return reply({error:'오늘의 응답 한도를 넘었어요. 내일 다시 기록해 주세요.'},429);
 await db().prepare('INSERT INTO quick_feedback(actor,place_id,noise,day,time,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(actor,place_id) DO UPDATE SET noise=excluded.noise,day=excluded.day,time=excluded.time,updated_at=excluded.updated_at').bind(actor,placeId,noise,day||null,time||null,Date.now()).run();
 await db().prepare('DELETE FROM quick_feedback WHERE updated_at<?').bind(Date.now()-90*86400000).run();await db().prepare('DELETE FROM quick_feedback_limits WHERE day<?').bind(koreaDay(Date.now()-2*86400000)).run();return reply({ok:true},200,previous?undefined:ownToken);
 }catch(error){return reply({error:'잠시 후 다시 시도해 주세요.'},error instanceof SyntaxError?400:503);}}
export async function DELETE(request:Request){try{if(!validOrigin(request))return reply({error:'Forbidden'},403);if(request.headers.get('content-type')!=='application/json')return reply({error:'JSON required'},415);const raw=await request.text();if(raw.length>200)return reply({error:'Too large'},413);const result=deletion.safeParse(JSON.parse(raw));if(!result.success)return reply({error:'Invalid request'},400);const ownToken=token(request);if(ownToken){const actor=await actorHash(ownToken);if(result.data.placeId)await db().prepare('DELETE FROM quick_feedback WHERE actor=? AND place_id=?').bind(actor,result.data.placeId).run();else await db().prepare('DELETE FROM quick_feedback WHERE actor=?').bind(actor).run();}return reply({ok:true});}catch(error){return reply({error:'Unavailable'},error instanceof SyntaxError?400:503);}}
