import {env} from 'cloudflare:workers';
import {getSiteUser} from '@/lib/site-auth';
import {db,isOwner,hasPlace,allPlaces} from '@/lib/store';
import {z} from 'zod';
import {membershipFor} from '@/lib/membership';
import {refreshQuality} from '@/lib/quality';
import {supportedCities,regionOf} from '@/lib/regions';
export const dynamic='force-dynamic';
const err=(error:string,status=400)=>Response.json({error},{status});
const text=z.string().trim().min(1).max(180);
const review=z.object({placeId:text,satisfied:z.number().int().min(0).max(1),noise:z.enum(['조용함','보통','시끄러움']),crowd:z.enum(['여유로움','보통','붐빔']),comfort:z.enum(['편함','보통','불편함','해당 없음']),day:z.enum(['평일','주말·공휴일']),time:z.enum(['오전','오후','저녁']),tags:z.array(z.enum(['작은 음악','좌석 간격','1인석','주문 방식','풍경','정차 공간','짧은 산책'])).max(7)});
const proposal=z.object({city:z.enum(supportedCities),category:z.enum(['food','cafe','drive']),name:text,address:text,source:z.string().trim().url().max(600).refine(s=>/^https?:\/\//.test(s)),note:z.string().trim().max(400),notChildTarget:z.literal(true),ack:z.literal(true)});
const normalize=(s:string)=>s.normalize('NFKC').toLowerCase().replace(/\s/g,'');
export async function POST(request:Request){
 if(request.headers.get('sec-fetch-site')==='cross-site')return err('허용되지 않은 요청입니다.',403);
 const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)return err('요청 출처를 확인할 수 없어요.',403);
 if(!request.headers.get('content-type')?.includes('application/json'))return err('JSON 요청이 필요합니다.',415);
 const user=await getSiteUser();if(!user)return err('로그인 후 이용해 주세요.',401);
 try{const raw=await request.text();if(raw.length>8000)return err('입력 내용이 너무 길어요.',413);const b=JSON.parse(raw);const d=db();const now=Date.now();
 if(b.action==='trial'){const m=await membershipFor(user.userId);if(m.trialUsed)return err('무료 체험은 계정당 한 번 이용할 수 있어요.',409);await d.prepare('INSERT OR IGNORE INTO trials(user_id,started_at) VALUES(?,?)').bind(user.userId,now).run();return Response.json({ok:true});}
 if(b.action==='moderate'){if(!await isOwner(user))return err('운영자 전용입니다.',403);const p=z.object({placeId:text,mode:z.enum(['auto','paused'])}).parse(b.payload);if(!await hasPlace(p.placeId))return err('장소를 찾을 수 없어요.',404);await d.prepare('INSERT INTO place_moderation(place_id,mode,updated_by,updated_at) VALUES(?,?,?,?) ON CONFLICT(place_id) DO UPDATE SET mode=excluded.mode,updated_by=excluded.updated_by,updated_at=excluded.updated_at').bind(p.placeId,p.mode,user.userId,now).run();return Response.json({ok:true});}
 if(b.action==='review'){const p=review.parse(b.payload);if(!await hasPlace(p.placeId))return err('공개된 장소만 평가할 수 있어요.',404);await d.prepare('INSERT INTO reviews (user_id,place_id,satisfied,noise,crowd,comfort,day,time,tags,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,place_id) DO UPDATE SET satisfied=excluded.satisfied,noise=excluded.noise,crowd=excluded.crowd,comfort=excluded.comfort,day=excluded.day,time=excluded.time,tags=excluded.tags,updated_at=excluded.updated_at').bind(user.userId,p.placeId,p.satisfied,p.noise,p.crowd,p.comfort,p.day,p.time,JSON.stringify([...new Set(p.tags)]),now).run();await refreshQuality(p.placeId);return Response.json({ok:true});}
 if(b.action==='deleteReview'){const id=text.parse(b.payload.placeId);await d.prepare('DELETE FROM reviews WHERE user_id=? AND place_id=?').bind(user.userId,id).run();await refreshQuality(id);return Response.json({ok:true});}
 if(b.action==='save'){const p=z.object({placeId:text,saved:z.boolean()}).parse(b.payload);if(!await hasPlace(p.placeId))return err('장소를 찾을 수 없어요.',404);await (p.saved?d.prepare('INSERT OR IGNORE INTO saved(user_id,place_id) VALUES(?,?)'):d.prepare('DELETE FROM saved WHERE user_id=? AND place_id=?')).bind(user.userId,p.placeId).run();return Response.json({ok:true});}
 if(b.action==='suggest'){const p=proposal.parse(b.payload);if(/키즈|유아|어린이.*전용|kids|baby/i.test(p.name))return err('유아 대상 장소는 등록 대상에서 제외돼요.');const all=await allPlaces();if(all.some(x=>regionOf(x.city)===regionOf(p.city)&&normalize(x.name)===normalize(p.name)))return err('이미 등록된 장소예요.');const pending=await d.prepare("SELECT name,city FROM suggestions WHERE status='pending'").all<any>();if(pending.results.some(x=>regionOf(x.city)===regionOf(p.city)&&normalize(x.name)===normalize(p.name)))return err('같은 이름의 장소가 이미 검토 중이에요.');const count=await d.prepare('SELECT COUNT(*) n FROM suggestions WHERE user_id=? AND created_at>?').bind(user.userId,now-86400000).first<any>();if(count.n>=5)return err('장소 제안은 하루 5곳까지 가능해요.',429);const id=crypto.randomUUID();await d.prepare('INSERT INTO suggestions (id,user_id,city,category,name,address,source,note,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,user.userId,p.city,p.category,p.name,p.address,p.source,p.note,'pending',now).run();return Response.json({ok:true,id,status:'pending'});}
 if(b.action==='claimOwner'){const token=z.string().min(32).max(200).parse(b.payload.token);if(!env.OWNER_SETUP_HASH)return err('운영자 연결이 준비되지 않았어요.',503);const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));const hash=Array.from(new Uint8Array(bytes),x=>x.toString(16).padStart(2,'0')).join('');if(hash!==env.OWNER_SETUP_HASH)return err('운영자 연결 코드가 올바르지 않아요.',403);const result=await d.prepare('INSERT OR IGNORE INTO owner(id,user_id,created_at) VALUES(1,?,?)').bind(user.userId,now).run();if(!result.meta.changes&&!await isOwner(user))return err('운영자가 이미 지정되어 있어요.',403);return Response.json({ok:true});}
 if(b.action==='decide'){if(!await isOwner(user))return err('운영자만 승인할 수 있어요.',403);const p=z.object({id:text,status:z.enum(['approved','rejected']),reason:z.string().trim().max(300),notChildTarget:z.boolean()}).parse(b.payload);if(p.status==='approved'&&!p.notChildTarget)return err('유아 대상 장소가 아닌지 먼저 확인해 주세요.');const target=await d.prepare("SELECT * FROM suggestions WHERE id=? AND status='pending'").bind(p.id).first<any>();if(!target)return err('이미 처리되었거나 없는 제안입니다.',409);if(p.status==='approved'&&(await allPlaces()).some(x=>regionOf(x.city)===regionOf(target.city)&&normalize(x.name)===normalize(target.name)))return err('같은 이름의 장소가 이미 등록되어 있어요.',409);const result=await d.prepare("UPDATE suggestions SET status=?,reason=?,decided_at=?,decided_by=? WHERE id=? AND status='pending'").bind(p.status,p.reason,now,user.userId,p.id).run();if(!result.meta.changes)return err('이미 처리된 제안입니다.',409);return Response.json({ok:true});}
 return err('지원하지 않는 요청입니다.');
 }catch(e){if(e instanceof z.ZodError||e instanceof SyntaxError)return err('필수 선택 항목과 입력 내용을 확인해 주세요.');console.error('action failed',e);return err('저장하지 못했어요. 입력 내용을 유지했으니 다시 시도해 주세요.',503);}
}
