'use client';
import {useEffect,useState} from 'react';
export default function CommunityAdmin({language}:{language:'ko'|'en'}){
 const ko=language==='ko',t=(kr:string,en:string)=>ko?kr:en,[data,setData]=useState<any>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reasons,setReasons]=useState<Record<string,string>>({});
 async function load(){const r=await fetch('/api/community/admin',{cache:'no-store'});if(!r.ok)throw Error();setData(await r.json());}
 useEffect(()=>{void load().catch(()=>setNotice(t('검토함을 불러오지 못했어요.','Unable to load moderation.')));},[]);
 async function decide(action:string,id:string,status:string){setBusy(true);try{const r=await fetch('/api/community/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,status,...(['report','contribution'].includes(action)?{}:{reason:reasons[id]||''})})});if(!r.ok)throw Error(String(r.status));await load();setNotice(t('처리했어요.','Decision saved.'));}catch(e){setNotice((e as Error).message==='400'?t('공개 동의가 있는 프로필을 먼저 승인하고 장소·지역을 확인해 주세요.','Approve the consenting profile and verify places first.'):t('처리하지 못했어요. 다시 불러와 주세요.','Unable to save. Please reload.'));}finally{setBusy(false);}}
 const buttons=(action:string,p:any)=><><label>{t('안내 사유 · 선택','Reason · optional')}<input value={reasons[p.id]||''} maxLength={300} onChange={e=>setReasons({...reasons,[p.id]:e.target.value})}/></label><div className="button-row"><button className="primary" disabled={busy} onClick={()=>void decide(action,p.id,'approved')}>{t('확인하고 승인','Verify and approve')}</button><button className="secondary" disabled={busy} onClick={()=>void decide(action,p.id,'rejected')}>{t('반려','Reject')}</button></div></>;
 return <section className="community-admin"><h2>{t('정보 제보 · 발견자 · 장소 모음 검토','Reports and contributor moderation')}</h2><p>{t('프로필 공개 동의와 정보 출처를 확인해 주세요. 정보 제보의 처리 완료는 장소 안내를 자동으로 바꾸지 않습니다.','Check consent and sources. Resolving a report does not automatically change place information.')}</p><button className="secondary" disabled={busy} onClick={()=>void load().catch(()=>setNotice(t('불러오기 실패','Unable to load')))}>{t('다시 불러오기','Reload')}</button><p role="status">{notice}</p>
 {data&&<><h3>{t('좌석·가격·사진 제보','Information and photo contributions')} · {data.contributions?.length||0}</h3>{(data.contributions||[]).map((p:any)=><article key={p.id}><h4>{(data.places||[]).find((x:{id:string;name:string;source:string})=>x.id===p.place_id)?.name||p.place_id}</h4><p>{p.note}</p>{p.source_url&&<p><a href={p.source_url} target="_blank" rel="noopener noreferrer">{t('안내 출처','Information source')} ↗</a></p>}{p.photo_url&&<p><a href={p.photo_url} target="_blank" rel="noopener noreferrer">{t('사진 링크','Photo link')} ↗</a> · {p.rights_consent?t('공개 사용 동의됨','Public-use consent given'):t('동의 확인 필요','Consent unconfirmed')}</p>}<p>{t('출처와 사진 권한을 확인한 뒤 장소 안내를 직접 수정해 주세요. 이 버튼은 내용을 자동으로 게시하지 않습니다.','Verify the source and photo rights, then edit the listing. This action does not publish the contribution.')}</p><div className="button-row"><button className="primary" disabled={busy} onClick={()=>void decide('contribution',p.id,'reviewed')}>{t('확인 완료','Reviewed')}</button><button className="secondary" disabled={busy} onClick={()=>void decide('contribution',p.id,'dismissed')}>{t('종료','Dismiss')}</button></div></article>)}<h3>{t('정보 오류 제보','Incorrect information reports')} · {data.reports.length}</h3>{data.reports.map((p:any)=>{const place=(data.places||[]).find((x:{id:string;name:string;source:string})=>x.id===p.place_id);return <article key={p.id}><h4>{place?.name||p.place_id} · {p.kind}</h4><p>{p.note||t('추가 설명 없음','No additional details')}</p>{place&&<a href={place.source} target="_blank" rel="noopener noreferrer">{t('원본 안내 확인','Check source')} ↗</a>}<div className="button-row"><button className="primary" disabled={busy} onClick={()=>void decide('report',p.id,'resolved')}>{t('확인·정보 수정 완료','Verified and corrected')}</button><button className="secondary" disabled={busy} onClick={()=>void decide('report',p.id,'dismissed')}>{t('수정 불필요로 종료','Close without change')}</button></div></article>;})}
 <h3>{t('발견자 프로필','Contributor profiles')} · {data.profiles.length}</h3>{data.profiles.map((p:any)=><article key={p.id}><h4>{p.name} · {p.country} / {p.region}</h4><p>{p.bio}</p>{p.link&&<a href={p.link} target="_blank" rel="noopener noreferrer">{p.link}</a>}<p>{t('공개 동의 확인됨','Public consent given')}</p>{buttons('profile',p)}</article>)}
 <h3>{t('장소 모음','Place collections')} · {data.collections.length}</h3>{data.collections.map((p:any)=><article key={p.id}><h4>{p.title} · {p.region}</h4><p>{p.author} · {p.profile_status}</p><p>{p.note}</p><ol>{JSON.parse(p.place_ids).map((id:string)=>{const place=(data.places||[]).find((p:{id:string;name:string;source:string})=>p.id===id);return <li key={id}><a href={'/'+p.country.toLowerCase()+'?place='+encodeURIComponent(id)+'&lang='+language}>{place?.name||id}</a>{place&&<> · <a href={place.source} target="_blank" rel="noopener noreferrer">{t('정보 출처','Source')}</a></>}</li>;})}</ol>{buttons('collection',p)}</article>)}</>}
 </section>;
}
