'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ChevronLeft,ChevronRight,Globe2} from 'lucide-react';
import {loadGeo} from '@/lib/geo-client';
import {LanguageToggle,useLocale} from './locale';

export default function GlobeHome(){
 const {lang,text}=useLocale();const [rotation,setRotation]=useState(100),[geo,setGeo]=useState<any>(null),[data,setData]=useState<any>(null),[failed,setFailed]=useState(false);const drag=useRef<{x:number;r:number;moved:boolean}|null>(null);
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.has('place')||q.has('category')||q.has('q')||location.hash.startsWith('#setup=')){location.replace('/kr'+location.search+location.hash);return;}let live=true;Promise.all([loadGeo(),fetch('/maps/world.json').then(r=>{if(!r.ok)throw Error();return r.json();})]).then(([d,w])=>{if(live){setGeo(()=>d);setData(w);}}).catch(()=>setFailed(true));return()=>{live=false;};},[]);
 const projection=geo?.geoOrthographic().scale(246).translate([300,300]).rotate([rotation,-22]);const path=geo?.geoPath(projection);
 const countries=[{code:'USA',slug:'us',name:text('United States','미국'),label:'UNITED STATES',center:[-98,38]},{code:'KOR',slug:'kr',name:text('South Korea','대한민국'),label:'SOUTH KOREA',center:[127.7,36.2]}];
 return <div className="world-app"><header className="world-header"><a className="brand" href={'/?lang='+lang}>Not<span>_</span>Hotplace</a><LanguageToggle/></header><main className="world-main"><section className="world-heading"><span className="world-kicker">WE WANT REST.</span><h1>{text('Find your','어디에서')}<br/><em>{text('room to breathe.','쉬어갈까요?')}</em></h1><p>{text('A slower day starts somewhere.','여유로운 하루, 그 시작이 될 곳.')}<br/>{text('Choose a country to explore.','나라를 선택해 지도를 둘러보세요.')}</p></section><section className="globe-panel" aria-label={text('Choose a country on the globe','지구본에서 국가 선택')}><div className="globe-display"><svg viewBox="0 0 600 600" role="group" aria-label={text('World globe. Drag to rotate.','세계 지구본. 드래그하여 회전하세요.')} onPointerDown={e=>{drag.current={x:e.clientX,r:rotation,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current){const dx=e.clientX-drag.current.x;if(Math.abs(dx)>4)drag.current.moved=true;setRotation(drag.current.r+dx*.45);}}} onPointerUp={e=>{e.currentTarget.releasePointerCapture(e.pointerId);setTimeout(()=>{drag.current=null;},0);}} onPointerCancel={()=>{drag.current=null;}}>
 <defs><radialGradient id="ocean" cx="32%" cy="25%"><stop stopColor="#162d37"/><stop offset="1" stopColor="#080e13"/></radialGradient><radialGradient id="shade" cx="28%" cy="28%" r="78%"><stop offset=".5" stopColor="#000" stopOpacity="0"/><stop offset="1" stopColor="#000" stopOpacity=".65"/></radialGradient></defs>
 <circle cx="300" cy="300" r="257" fill="none" stroke="#456654" strokeOpacity=".35"/><circle cx="300" cy="300" r="246" fill="url(#ocean)"/>
 {geo&&data&&<><path d={path(geo.geoGraticule10())||''} fill="none" stroke="#617c70" strokeWidth=".7" opacity=".28"/>{data.features.map((f:any)=>{const supported=countries.find(c=>c.code===f.properties.code);return <path key={f.properties.code} d={path(f)||''} fill={supported?'#d1ff73':'#29433e'} stroke={supported?'#eaffb4':'#708b76'} strokeWidth={supported?1.4:.6} onClick={()=>{if(supported&&!drag.current?.moved)location.href='/'+supported.slug+'?lang='+lang;}} className={supported?'globe-country':''}><title>{supported?.name||f.properties.name}</title></path>;})}<circle cx="300" cy="300" r="246" fill="url(#shade)" pointerEvents="none"/>{countries.map(c=>{if(geo.geoDistance(c.center,projection.invert([300,300]))>Math.PI/2)return null;const [x,y]=projection(c.center);return <g key={c.code} className="globe-pin" role="link" tabIndex={0} aria-label={c.name} onClick={()=>{if(!drag.current?.moved)location.href='/'+c.slug+'?lang='+lang;}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();location.href='/'+c.slug+'?lang='+lang;}}}><circle cx={x} cy={y} r="20" fill="transparent"/><circle cx={x} cy={y} r="10" fill="#d1ff73" opacity=".2"/><circle cx={x} cy={y} r="4" fill="#f1ffd5"/><text x={x} y={y-21} fill="#fff" fontSize="14" textAnchor="middle" paintOrder="stroke" stroke="#0a1417" strokeWidth="5">{lang==='en'?c.label:c.name}</text></g>;})}</>}
 </svg>{!data&&<span className="globe-load">{failed?text('Choose a country below.','아래에서 나라를 선택하세요.'):text('Loading the globe…','지구본을 불러오는 중…')}</span>}</div><div className="globe-rotation"><button onClick={()=>setRotation(r=>r+60)} aria-label={text('Rotate west','서쪽으로 회전')}><ChevronLeft size={20}/></button><span>{text('Drag to explore','드래그해서 둘러보기')}</span><button onClick={()=>setRotation(r=>r-60)} aria-label={text('Rotate east','동쪽으로 회전')}><ChevronRight size={20}/></button></div></section><nav className="country-choices" aria-label={text('Available countries','선택 가능한 국가')}>{countries.map(c=><a key={c.code} href={'/'+c.slug+'?lang='+lang} onMouseEnter={()=>setRotation(c.code==='USA'?100:-127)}><span className="country-code">{c.code==='USA'?'US':'KR'}</span><span><strong>{c.name}</strong><small>{text('Open country map','국가 지도 열기')}</small></span><ArrowUpRight/></a>)}</nav></main><footer className="world-footer"><span><Globe2 size={15}/>{text('Korea + the U.S. · More places, at your pace.','한국과 미국 · 나만의 속도로 찾는 쉼.')}</span><a href={'/privacy?lang='+lang}>{text('Privacy','개인정보처리방침')}</a></footer></div>;
}
