'use client';
import {useState} from 'react';
import {Check,ArrowUpRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {plans} from '@/lib/plans';
import {toast} from 'sonner';
type Member={active:boolean;trialUsed:boolean;until:number|null;kind:string};
let sdkPromise:Promise<void>|null=null;
function loadToss(){if((window as any).TossPayments)return Promise.resolve();if(!sdkPromise)sdkPromise=new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src='https://js.tosspayments.com/v2/standard';s.onload=()=>resolve();s.onerror=()=>{sdkPromise=null;s.remove();reject(new Error('결제창을 불러오지 못했어요.'));};document.head.appendChild(s);});return sdkPromise;}
export default function Membership({open,setOpen,signedIn,membership,paymentsReady,onChanged}:{open:boolean;setOpen:(v:boolean)=>void;signedIn:boolean;membership?:Member;paymentsReady:boolean;onChanged:()=>Promise<unknown>}){
 const [selected,setSelected]=useState('month'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const plan=plans.find(p=>p.id===selected)!;
 async function trial(){setBusy(true);setError('');try{const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'trial',payload:{}})});const j=await r.json() as any;if(!r.ok)throw new Error(j.error);await onChanged();toast.success('7일 무료 체험이 시작됐어요. 자동 결제는 없어요.');}catch(e){setError(e instanceof Error?e.message:'다시 시도해 주세요.');}finally{setBusy(false);}}
 async function buy(){setBusy(true);setError('');try{const r=await fetch('/api/payments/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({planId:selected,consent})});const j=await r.json() as any;if(!r.ok)throw new Error(j.error);await loadToss();await (window as any).TossPayments(j.clientKey).payment({customerKey:j.customerKey}).requestPayment({method:'CARD',amount:j.amount,orderId:j.orderId,orderName:j.orderName,successUrl:j.successUrl,failUrl:j.failUrl,card:{flowMode:'DEFAULT'}});}catch(e){setError(e instanceof Error?e.message:'결제를 시작하지 못했어요.');}finally{setBusy(false);}}
 return <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="nhp-modal plus-modal"><span className="eyebrow">NOT_HOTPLACE PLUS</span><DialogTitle className="modal-title">나에게 맞는 쉼을 더 가까이.</DialogTitle><DialogDescription>지도·주변 찾기·후기·저장·공유는 계속 무료예요.</DialogDescription><div className="plus-benefits"><p><Check size={16}/>시간대별 조용함과 여유로움 확인</p><p><Check size={16}/>후기 3명 이상 · 조용함 80% 필터</p><small>후기가 부족한 시간대는 ‘후기 부족’으로 표시해요.</small></div>{membership?.active&&<p className="membership-status">{membership.kind==='trial'?'무료 체험 중':'Plus 이용 중'} · {new Date(membership.until!).toLocaleDateString('ko-KR')}까지</p>}{!membership?.trialUsed&&!membership?.active&&(signedIn?<button className="primary trial-button" disabled={busy} onClick={trial}>카드 없이 7일 무료 체험 <ArrowUpRight size={16}/></button>:<a className="primary trial-button" href="/login" target="_top">로그인하고 7일 무료 체험</a>)}<p className="trial-note">체험이 끝나도 자동으로 결제되지 않아요.</p><div className="plans" role="group" aria-label="Plus 이용 기간">{plans.map(p=><button key={p.id} className={'plan-option '+(selected===p.id?'selected':'')} aria-pressed={selected===p.id} onClick={()=>{setSelected(p.id);setConsent(false);}}><span>{p.name}{p.discount>0&&<em>{p.discount}% 할인</em>}</span><strong>{p.amount.toLocaleString()}<small>원</small></strong><small>{p.months>1?'월 환산 '+p.monthly.toLocaleString()+'원':'가볍게 시작하기'}</small></button>)}</div><p className="price-note">부가세 포함 · {plan.name} 총 {plan.amount.toLocaleString()}원 일시 결제<br/>자동갱신 없는 기간권 · 무료 지도는 계속 이용 가능</p>{paymentsReady?<><label className="ack"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>{plan.name} 이용권 {plan.amount.toLocaleString()}원 결제와 <a href="/policies" target="_blank" rel="noopener noreferrer">이용·환불 안내</a>를 확인했어요.</span></label>{signedIn?<button className="primary" disabled={!consent||busy||membership?.kind==='paid'} onClick={buy}>{busy?'처리 중…':plan.amount.toLocaleString()+'원 결제하기'}</button>:<a className="primary" href="/login" target="_top">로그인하고 구매</a>}</>:<p className="payment-preparing">유료 이용권은 오픈 준비 중이에요. 지금은 무료 기능과 체험을 이용해 보세요.</p>}{error&&<p className="error" role="alert">{error}</p>}</DialogContent></Dialog>;
}
