'use client';
import {useState} from 'react';
const choices=[['location','위치가 달라요','Location'],['hours','운영 시간이 달라요','Hours'],['parking','주차 안내가 달라요','Parking'],['closed','휴무·폐업을 확인해요','Closure'],['conditions','휴식 조건이 달라요','Rest conditions']] as const;
export default function ReportPlace({id,language}:{id:string;language:'ko'|'en'}){
 const ko=language==='ko',[note,setNote]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function report(kind:string){setBusy(true);setNotice('');try{const r=await fetch('/api/place-reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({placeId:id,kind,note})});if(!r.ok)throw Error(String(r.status));setNotice(ko?'제보를 받았어요. 운영자가 출처를 확인한 뒤 안내를 수정합니다.':'Received. The operator will verify the source before changing the listing.');setNote('');}catch(e){setNotice((e as Error).message==='429'?(ko?'정보 제보는 하루 5건까지 가능해요.':'Up to five reports per browser per day.'):(ko?'보내지 못했어요. 잠시 후 다시 시도해 주세요.':'Unable to send. Please try again.'));}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{const r=await fetch('/api/place-reports',{method:'DELETE',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error();setNotice(ko?'이 브라우저에서 남긴 정보 제보를 삭제했어요.':'Deleted reports from this browser.');}catch{setNotice(ko?'삭제하지 못했어요. 다시 시도해 주세요.':'Unable to delete. Try again.');}finally{setBusy(false);}}
 return <details className="place-report"><summary>{ko?'정보가 달라요 · 로그인 없이 제보':'Report incorrect information · no sign-in'}</summary><p>{ko?'해당 항목을 누르면 제보됩니다. 연락처나 개인정보 없이 바뀐 안내·공식 링크만 알려주세요.':'Tap an issue to submit it. Add changed details or an official link without personal or contact information.'}</p><label>{ko?'추가 안내 · 선택':'Details · optional'}<textarea value={note} maxLength={400} rows={2} onChange={e=>setNote(e.target.value)}/></label><div className="report-choices">{choices.map(([kind,kr,en])=><button key={kind} type="button" disabled={busy} onClick={()=>void report(kind)}>{ko?kr:en}</button>)}</div><p role="status">{notice}</p><button className="text-button" type="button" disabled={busy} onClick={()=>void remove()}>{ko?'이 브라우저의 정보 제보 삭제':'Delete this browser’s reports'}</button></details>;
}
