'use client';
import {useEffect,useState} from 'react';
import {loadGeo} from '@/lib/geo-client';
import {useLocale} from './locale';
import type {MapPlace} from './discovery-map';
export default function USMap({places,city,onEnter}:{places:MapPlace[];city:string;onEnter:(s:string)=>void}){
 const {text,t}=useLocale();const [geo,setGeo]=useState<any>(null),[states,setStates]=useState<any>(null),[hover,setHover]=useState(''),[failed,setFailed]=useState(false);
 useEffect(()=>{let live=true;Promise.all([loadGeo(),fetch('/maps/us-states.json?v=20260922b',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();})]).then(([d,s])=>{if(live){setGeo(()=>d);setStates(s);}}).catch(()=>setFailed(true));return()=>{live=false;};},[]);
 const projection=geo?.geoAlbersUsa().scale(880).translate([465,292]);const path=geo?.geoPath(projection);const count=(name:string)=>places.filter(p=>p.city===name||p.states?.includes(name)).length;
 return <section className="us-map-panel"><div className="us-map-heading"><strong>{city==='전국'?text('United States','미국'):t(city)}</strong><button onClick={()=>onEnter('전국')}>{text('All states','전체 주')}</button></div><svg viewBox="0 0 930 590" aria-label={text('United States state selection map','미국 주 선택 지도')} role="group">{geo&&states?.features.filter((f:any)=>f.properties.name!=='Puerto Rico').map((f:any)=>{const name=f.properties.name,shape=path(f),active=city===name,n=count(name);if(!shape)return null;const center=path.centroid(f);return <g key={name}><path d={shape} className={'us-state '+(n?'has-places ':'')+(active?'is-active':'')} role="button" tabIndex={0} aria-label={`${t(name)}: ${n} ${text('places','곳')}`} aria-pressed={active} onClick={()=>onEnter(name)} onMouseEnter={()=>setHover(name)} onMouseLeave={()=>setHover('')} onFocus={()=>setHover(name)} onBlur={()=>setHover('')} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onEnter(name);}}}><title>{t(name)} · {n} {text('places','곳')}</title></path>{n>0&&Number.isFinite(center[0])&&<circle cx={center[0]} cy={center[1]} r="4" fill="#d1ff73" pointerEvents="none"/>}</g>;})}</svg>{!states&&<p role="status">{failed?text('Map unavailable. Use the state selector above.','지도를 불러오지 못했습니다. 위의 지역 선택을 이용하세요.'):text('Loading the map…','지도 불러오는 중…')}</p>}<div className="us-map-caption"><span aria-live="polite">{hover?`${t(hover)} · ${count(hover)} ${text('places','곳')}`:text('Select a state. Highlighted states have places.','주를 선택하세요. 밝은 주에 등록된 장소가 있습니다.')}</span><small>{text('Alaska & Hawaii shown as insets.','알래스카·하와이는 별도 배치.')}</small></div><a className="us-map-source" href="https://github.com/PublicaMundi/MappingAPI/blob/master/data/geojson/us-states.json" target="_blank" rel="noreferrer">{text('Map source','지도 출처')}</a></section>;
}
