import type {Place} from './catalog';
import {matchesPlaceTheme} from './place-themes';
export type Guide={slug:string;titleKo:string;titleEn:string;descriptionKo:string;descriptionEn:string;country:'KR'|'US';kind:'seoul'|'cheongju'|'private'|'spa'|'water'|'temple'|'us'|'photos';checksKo:string[];checksEn:string[]};
export const guides:Guide[]=[
 {slug:'seoul-solo',titleKo:'서울에서 혼자 쉬기: 카페와 찻집',titleEn:'A slower solo day in Seoul',descriptionKo:'서울의 카페와 찻집을 둘러보고, 사진·운영 정보·1인 이용 조건을 확인해 보세요. 방문 시간의 조용함은 후기로 따로 살펴봐요.',descriptionEn:'Explore cafés and teahouses in Seoul. Compare photos, visitor information and solo-visit conditions, then check visitor feedback.',country:'KR',kind:'seoul',checksKo:['1인 이용과 좌석 조건','주말·행사일 혼잡','운영 시간과 휴무'],checksEn:['Solo-visit and seating rules','Weekend and event crowds','Opening hours and closures']},
 {slug:'cheongju-slow',titleKo:'청주에서 쉬어가기: 카페·식사·호반 산책',titleEn:'A slower day in Cheongju',descriptionKo:'청주와 대청호 주변에서 쉬어갈 후보를 비교하세요. 식사의 최소 주문 인원과 정차·주차 조건까지 함께 확인해요.',descriptionEn:'Compare places in Cheongju and near Daecheong Lake. Check minimum dining party sizes and parking before setting out.',country:'KR',kind:'cheongju',checksKo:['식사 최소 주문 인원','주차와 공식 정차 공간','방문일 운영·교통 상황'],checksEn:['Minimum dining party size','Parking and permitted stopping places','Opening status and traffic']},
 {slug:'seoul-private',titleKo:'서울 프라이빗 룸: 공간과 예약 조건 비교',titleEn:'Private rooms in Seoul: compare the conditions',descriptionKo:'일행만의 공간을 찾을 때 룸 종류, 이용 인원, 최소 이용금액과 예약 방법을 함께 확인하세요. 공간의 독립성과 실제 조용함은 별도로 평가해요.',descriptionEn:'Compare room types, party sizes, minimum spends and booking conditions. A private room and actual quietness are assessed separately.',country:'KR',kind:'private',checksKo:['룸 지정과 단독 이용 범위','이용 인원·최소금액·추가요금','방음·음악·주변 공간 소음'],checksEn:['Room allocation and exclusive-use scope','Party size, minimum spend and surcharges','Soundproofing, music and surrounding noise']},
 {slug:'premium-spa',titleKo:'프리미엄 스파: 내 공간부터 확인하기',titleEn:'Premium spas: check your space first',descriptionKo:'스파 프로그램과 예약할 룸을 함께 살펴보세요. 커플룸·VIP룸이 있어도 단독 이용 범위와 추가요금은 별도 확인이 필요해요.',descriptionEn:'Explore spa treatments alongside the room you can book. Confirm exclusive-use scope and any surcharges for couples or VIP rooms.',country:'KR',kind:'spa',checksKo:['룸 종류와 단독 이용 여부','프로그램 시간과 총 요금','일행 이용·예약 취소 조건'],checksEn:['Room type and exclusive use','Treatment duration and total cost','Party size and cancellation terms']},
 {slug:'waterside-pause',titleKo:'물가에서 쉬기: 호반·해안·짧은 산책',titleEn:'A pause by the water',descriptionKo:'호반과 해안 주변의 드라이브·산책 후보를 사진과 이용 정보로 비교하세요. 주차 후 걸을 수 있는 구간과 날씨를 먼저 확인해요.',descriptionEn:'Compare scenic waterside stops and short walks. Check parking, walking access and weather before you travel.',country:'KR',kind:'water',checksKo:['주차 가능한 곳과 도보 접근','탐방 구간 개방·도로 통제','날씨와 시간대별 혼잡'],checksEn:['Parking and walking access','Open trails and road restrictions','Weather and time-of-day crowds']},
 {slug:'temple-stay',titleKo:'템플스테이: 당일·휴식형·1인 참가 비교',titleEn:'Templestay: plan a day visit or a restful night',descriptionKo:'당일 체험과 숙박형 중 원하는 쉼을 고르고, 공식 예약처에서 프로그램·객실 배정·참여 조건을 확인하세요.',descriptionEn:'Choose a day experience or overnight stay, then confirm the program, room allocation and participation conditions with the official booking service.',country:'KR',kind:'temple',checksKo:['당일·숙박·휴식형 구분','1인 참가와 1인 객실의 차이','필수 프로그램·준비물·취소 조건'],checksEn:['Day, overnight and rest-oriented programs','Solo participation versus a private room','Required activities, packing and cancellation']},
 {slug:'us-slow',titleKo:'미국에서 쉬어가기: 카페와 풍경',titleEn:'Find your slower day in the United States',descriptionKo:'미국의 카페와 자연 거점을 사진·공식 정보로 살펴보세요. 방문 시간의 혼잡과 이용 조건은 따로 확인해요.',descriptionEn:'Explore cafés and scenic stops in the United States. Compare photos and official visitor information, then check crowds and access for your visit.',country:'US',kind:'us',checksKo:['입장·주차·예약 조건','공식 운영 시간과 통제 안내','방문 시간대의 분위기'],checksEn:['Admission, parking and reservations','Official opening hours and restrictions','Atmosphere at your visiting time']},
 {slug:'photo-guides',titleKo:'사진과 방문 정보를 함께 보는 50곳',titleEn:'50 places with photos and visitor details',descriptionKo:'사진과 방문 전 정보를 갖춘 국내 장소 50곳을 모았어요. 운영·주차·입장·예약 정보를 비교하며 다음 쉼을 계획하세요.',descriptionEn:'Browse 50 places in Korea with photos and visitor details. Compare opening hours, parking, admission and reservations for your next pause.',country:'KR',kind:'photos',checksKo:['장소별 사진과 촬영 출처','정보 확인일과 공식·관광정보 출처','방문 후기 수와 최근 작성일'],checksEn:['Place photos and credits','Source and information-check date','Visitor response count and recency']},
];
export function findGuide(slug:string){return guides.find(guide=>guide.slug===slug);}
export function guidePlaces(guide:Guide,places:Place[]):Place[]{
 return places.filter(place=>{
  if((place.country||'KR')!==guide.country)return false;
  if(guide.kind==='seoul')return place.city==='서울'&&place.category==='cafe';
  if(guide.kind==='cheongju')return place.city==='청주'||/청주시/.test(place.address);
  if(guide.kind==='private')return place.city==='서울'&&matchesPlaceTheme(place,'private-room');
  if(guide.kind==='spa')return matchesPlaceTheme(place,'premium-spa');
  if(guide.kind==='water')return place.category==='drive'&&/호|저수지|해안|바다|뱃길|대교/.test(place.name+' '+place.description);
  if(guide.kind==='us')return !!place.image;
  if(guide.kind==='photos')return (place.photos?.length||0)>=3&&!!place.visitDetails?.length;
  return false;
 }).sort((a,b)=>Number(!!b.photos?.length)-Number(!!a.photos?.length)||Number(!!b.image)-Number(!!a.image)||a.id.localeCompare(b.id)).slice(0,guide.kind==='photos'?50:12);
}
