import type {Place} from './catalog';
import {matchesPlaceTheme} from './place-themes';
import {matchesCondition,type RestCondition} from './rest-conditions';
import {inRegion} from './regions';
import type {CountryCode} from './countries';
export type Guide={slug:string;titleKo:string;titleEn:string;descriptionKo:string;descriptionEn:string;country:CountryCode;countryGroup?:CountryCode[];scopeKo?:string;scopeEn?:string;kind:'seoul'|'cheongju'|'private'|'spa'|'water'|'temple'|'us'|'photos'|'intent'|'world';condition?:RestCondition;region?:string;category?:string;checksKo:string[];checksEn:string[]};
export const guides:Guide[]=[
 {slug:'korea-reading-cafes',titleKo:'책과 함께 쉬는 카페: 독서 공간 안내 4곳',titleEn:'Four cafés with published reading-space details',descriptionKo:'북카페·책방·독서 공간이 안내된 장소만 모았어요. 책이 있다는 사실과 대화·음악이 작은지는 서로 다른 조건입니다. 좌석 이용과 책 열람·구매 방식을 먼저 확인하세요.',descriptionEn:'These four candidates explicitly describe books or reading spaces. Books do not establish low noise. Check seat use and whether books can be read or bought.',country:'KR',kind:'intent',condition:'books',checksKo:['열람용 책인지 판매용 책인지','독서 좌석·노트북·이용 시간 조건','음악·대화 소음은 최근 방문 후기로 확인'],checksEn:['Reading copies versus books for sale','Seating, laptop rules and time limits','Use recent feedback to assess music and conversations']},
 {slug:'cheongju-parking-cafes',titleKo:'청주 주차 안내가 있는 카페: 차로 가기 전 비교',titleEn:'Cheongju cafés with published parking availability',descriptionKo:'공개 장소 안내에 주차 가능으로 표시된 청주 카페를 비교하세요. 주차 가능 안내만으로 빈자리·무료 주차·입구 동선까지 보장하지는 않습니다. 방문일 매장 안내와 주차 위치를 확인하고 출발하세요.',descriptionEn:'Compare Cheongju cafés whose published listings explicitly report parking availability. This does not establish spare spaces, free parking or an entrance route. Confirm parking details for your visit.',country:'KR',kind:'intent',condition:'parking',region:'청주',category:'cafe',checksKo:['매장 전용 주차인지 인근 공영주차인지','주차 요금·이용 시간·만차 시 대안','주차장에서 실제 입구까지의 접근'],checksEn:['Venue parking versus nearby public parking','Fees, time limits and an alternative when full','Access from the parking area to the actual entrance']},
 {slug:'seoul-solo-seating',titleKo:'서울 1인석 카페: 안내가 확인된 좌석부터',titleEn:'Individual café seats in Seoul: start with documented seating',descriptionKo:'현재 공개 자료에 1인석이 명시된 서울 카페를 소개합니다. 후보 수보다 확인된 조건을 우선하며, 다른 장소는 자료와 후기가 쌓이면 추가해요. 1인석 안내와 혼자 주문 가능한 메뉴·자리 확보는 따로 확인하세요.',descriptionEn:'This guide starts with Seoul cafés that explicitly mention individual seats. Additional places will be included as evidence grows. Individual seats do not establish solo menu availability or guarantee a free seat.',country:'KR',kind:'intent',condition:'soloSeats',region:'서울',category:'cafe',checksKo:['1인석 위치와 이용 가능 시간','1인 주문·최소 주문·노트북 이용 규정','좌석 예약 여부와 방문 시간의 소음'],checksEn:['Where individual seats are and when available','Solo ordering, minimum orders and laptop rules','Seat booking and noise at your visiting time']},
 {slug:'tokyo-garden-pause',titleKo:'도쿄 정원에서 쉬기: 입장·휴무·접근부터',titleEn:'A garden pause in Tokyo: admission, closures and access',descriptionKo:'도쿄 관광기관에 등록된 정원·공원에서 산책 후보를 고르세요. 지도에는 관광기관의 기준점을 표시하고, 입구·입장료·마지막 입장·휴무는 개별 출처에서 확인하도록 연결합니다. 관광객이 적다는 뜻은 아닙니다.',descriptionEn:'Choose a garden or park listed by Tokyo’s tourism organization. Map points are reference locations; use each source to confirm entrances, admission, last entry and closures. These are not low-crowd guarantees.',country:'JP',kind:'intent',region:'Tokyo',category:'walk',checksKo:['유료 구역·마지막 입장·휴원일','선택한 역에서 열려 있는 입구까지의 접근','벚꽃·단풍·행사 기간의 혼잡'],checksEn:['Paid areas, last entry and closure days','Access from your station to an open entrance','Cherry-blossom, autumn and event crowds']},
 {slug:'portland-coffee-pause',titleKo:'포틀랜드에서 커피와 쉬기: 운영 정보가 있는 후보',titleEn:'A coffee pause in Portland: candidates with visitor details',descriptionKo:'포틀랜드의 카페 후보를 주소·공식 출처·방문 안내로 비교해요. 도시 전체의 조용함을 단정하지 않고, 매장별 주문·좌석·방문 시간의 분위기를 직접 확인하도록 안내합니다.',descriptionEn:'Compare Portland cafés using addresses, official sources and visitor details. Noise is venue-specific; check ordering, seating and the atmosphere at your visiting time.',country:'US',kind:'intent',region:'Oregon',category:'cafe',checksKo:['방문할 지점의 주소와 영업일','매장 좌석·주문·테이크아웃 조건','음악·혼잡·혼자 쉬기 편함의 최근 후기'],checksEn:['The branch address and opening days','Seating, ordering and takeaway rules','Recent feedback on music, crowds and solo comfort']},
 {slug:'seoul-solo',titleKo:'서울에서 혼자 쉬기: 카페와 찻집',titleEn:'A slower solo day in Seoul',descriptionKo:'서울의 카페와 찻집을 둘러보고, 사진·운영 정보·1인 이용 조건을 확인해 보세요. 방문 시간의 조용함은 후기로 따로 살펴봐요.',descriptionEn:'Explore cafés and teahouses in Seoul. Compare photos, visitor information and solo-visit conditions, then check visitor feedback.',country:'KR',kind:'seoul',checksKo:['1인 이용과 좌석 조건','주말·행사일 혼잡','운영 시간과 휴무'],checksEn:['Solo-visit and seating rules','Weekend and event crowds','Opening hours and closures']},
 {slug:'cheongju-slow',titleKo:'청주에서 쉬어가기: 카페·식사·호반 산책',titleEn:'A slower day in Cheongju',descriptionKo:'청주와 대청호 주변에서 쉬어갈 후보를 비교하세요. 식사의 최소 주문 인원과 정차·주차 조건까지 함께 확인해요.',descriptionEn:'Compare places in Cheongju and near Daecheong Lake. Check minimum dining party sizes and parking before setting out.',country:'KR',kind:'cheongju',checksKo:['식사 최소 주문 인원','주차와 공식 정차 공간','방문일 운영·교통 상황'],checksEn:['Minimum dining party size','Parking and permitted stopping places','Opening status and traffic']},
 {slug:'seoul-private',titleKo:'서울 프라이빗 룸: 공간과 예약 조건 비교',titleEn:'Private rooms in Seoul: compare the conditions',descriptionKo:'일행만의 공간을 찾을 때 룸 종류, 이용 인원, 최소 이용금액과 예약 방법을 함께 확인하세요. 공간의 독립성과 실제 조용함은 별도로 평가해요.',descriptionEn:'Compare room types, party sizes, minimum spends and booking conditions. A private room and actual quietness are assessed separately.',country:'KR',kind:'private',checksKo:['룸 지정과 단독 이용 범위','이용 인원·최소금액·추가요금','방음·음악·주변 공간 소음'],checksEn:['Room allocation and exclusive-use scope','Party size, minimum spend and surcharges','Soundproofing, music and surrounding noise']},
 {slug:'premium-spa',titleKo:'프리미엄 스파: 내 공간부터 확인하기',titleEn:'Premium spas: check your space first',descriptionKo:'스파 프로그램과 예약할 룸을 함께 살펴보세요. 커플룸·VIP룸이 있어도 단독 이용 범위와 추가요금은 별도 확인이 필요해요.',descriptionEn:'Explore spa treatments alongside the room you can book. Confirm exclusive-use scope and any surcharges for couples or VIP rooms.',country:'KR',kind:'spa',checksKo:['룸 종류와 단독 이용 여부','프로그램 시간과 총 요금','일행 이용·예약 취소 조건'],checksEn:['Room type and exclusive use','Treatment duration and total cost','Party size and cancellation terms']},
 {slug:'waterside-pause',titleKo:'물가에서 쉬기: 호반·해안·짧은 산책',titleEn:'A pause by the water',descriptionKo:'호반과 해안 주변의 드라이브·산책 후보를 사진과 이용 정보로 비교하세요. 주차 후 걸을 수 있는 구간과 날씨를 먼저 확인해요.',descriptionEn:'Compare scenic waterside stops and short walks. Check parking, walking access and weather before you travel.',country:'KR',kind:'water',checksKo:['주차 가능한 곳과 도보 접근','탐방 구간 개방·도로 통제','날씨와 시간대별 혼잡'],checksEn:['Parking and walking access','Open trails and road restrictions','Weather and time-of-day crowds']},
 {slug:'temple-stay',titleKo:'템플스테이: 당일·휴식형·1인 참가 비교',titleEn:'Templestay: plan a day visit or a restful night',descriptionKo:'당일 체험과 숙박형 중 원하는 쉼을 고르고, 공식 예약처에서 프로그램·객실 배정·참여 조건을 확인하세요.',descriptionEn:'Choose a day experience or overnight stay, then confirm the program, room allocation and participation conditions with the official booking service.',country:'KR',kind:'temple',checksKo:['당일·숙박·휴식형 구분','1인 참가와 1인 객실의 차이','필수 프로그램·준비물·취소 조건'],checksEn:['Day, overnight and rest-oriented programs','Solo participation versus a private room','Required activities, packing and cancellation']},
 {slug:'us-slow',titleKo:'미국에서 쉬어가기: 카페와 풍경',titleEn:'Find your slower day in the United States',descriptionKo:'미국의 카페와 자연 거점을 사진·공식 정보로 살펴보세요. 방문 시간의 혼잡과 이용 조건은 따로 확인해요.',descriptionEn:'Explore cafés and scenic stops in the United States. Compare photos and official visitor information, then check crowds and access for your visit.',country:'US',kind:'us',checksKo:['입장·주차·예약 조건','공식 운영 시간과 통제 안내','방문 시간대의 분위기'],checksEn:['Admission, parking and reservations','Official opening hours and restrictions','Atmosphere at your visiting time']},
 {slug:'photo-guides',titleKo:'사진과 방문 정보를 함께 보는 50곳',titleEn:'50 places with photos and visitor details',descriptionKo:'사진과 방문 전 정보를 갖춘 국내 장소 50곳을 모았어요. 운영·주차·입장·예약 정보를 비교하며 다음 쉼을 계획하세요.',descriptionEn:'Browse 50 places in Korea with photos and visitor details. Compare opening hours, parking, admission and reservations for your next pause.',country:'KR',kind:'photos',checksKo:['장소별 사진과 촬영 출처','정보 확인일과 공식·관광정보 출처','방문 후기 수와 최근 작성일'],checksEn:['Place photos and credits','Source and information-check date','Visitor response count and recency']},
 {"slug": "europe-garden-pause", "titleKo": "유럽에서 쉬기: 공원·정원 후보", "titleEn": "A garden pause in Europe", "descriptionKo": "유럽의 실제 장소를 사진·주소 참고자료·이용 안내로 비교해요. 가격·운영·주차 안내는 확인된 경우에만 표시하고, 조용함은 방문 후기로 따로 살펴봅니다.", "descriptionEn": "Compare real places in Europe using credited photos, location references and published visitor details. Prices, hours and parking appear only when documented. Quietness is assessed separately.", "country": "GB", "countryGroup": ["GB", "FR", "DE", "ES", "IT", "PT", "NL", "AT", "CZ", "HU"], "scopeKo": "유럽", "scopeEn": "Europe", "kind": "world", "checksKo": ["입장권·유료 구역과 무료 일반 입장을 구분하기", "운영 시간·출입구·공사 또는 행사 안내 확인하기", "조용함은 방문 시간의 실제 후기로 확인하기"], "checksEn": ["Distinguish general admission from paid areas", "Check hours, entrances, restoration and events", "Use visitor feedback for the time you plan to visit"]},
 {"slug": "central-asia-pause", "titleKo": "중앙아시아에서 쉬기: 산책 공간과 정원", "titleEn": "A slower walk in Central Asia", "descriptionKo": "중앙아시아의 실제 장소를 사진·주소 참고자료·이용 안내로 비교해요. 가격·운영·주차 안내는 확인된 경우에만 표시하고, 조용함은 방문 후기로 따로 살펴봅니다.", "descriptionEn": "Compare real places in Central Asia using credited photos, location references and published visitor details. Prices, hours and parking appear only when documented. Quietness is assessed separately.", "country": "KZ", "countryGroup": ["KZ", "UZ", "KG"], "scopeKo": "중앙아시아", "scopeEn": "Central Asia", "kind": "world", "checksKo": ["입장권·유료 구역과 무료 일반 입장을 구분하기", "운영 시간·출입구·공사 또는 행사 안내 확인하기", "조용함은 방문 시간의 실제 후기로 확인하기"], "checksEn": ["Distinguish general admission from paid areas", "Check hours, entrances, restoration and events", "Use visitor feedback for the time you plan to visit"]},
 {"slug": "asia-garden-pause", "titleKo": "아시아에서 쉬기: 정원·물가 산책", "titleEn": "Garden and waterside pauses in Asia", "descriptionKo": "아시아의 실제 장소를 사진·주소 참고자료·이용 안내로 비교해요. 가격·운영·주차 안내는 확인된 경우에만 표시하고, 조용함은 방문 후기로 따로 살펴봅니다.", "descriptionEn": "Compare real places in Asia using credited photos, location references and published visitor details. Prices, hours and parking appear only when documented. Quietness is assessed separately.", "country": "SG", "countryGroup": ["JP", "SG", "TH", "TW", "MY", "VN", "ID", "IN"], "scopeKo": "아시아", "scopeEn": "Asia", "kind": "world", "checksKo": ["입장권·유료 구역과 무료 일반 입장을 구분하기", "운영 시간·출입구·공사 또는 행사 안내 확인하기", "조용함은 방문 시간의 실제 후기로 확인하기"], "checksEn": ["Distinguish general admission from paid areas", "Check hours, entrances, restoration and events", "Use visitor feedback for the time you plan to visit"]},
 {"slug": "north-america-pause", "titleKo": "북미에서 쉬기: 미국·캐나다·멕시코의 공간", "titleEn": "Places to pause in North America", "descriptionKo": "북미의 실제 장소를 사진·주소 참고자료·이용 안내로 비교해요. 가격·운영·주차 안내는 확인된 경우에만 표시하고, 조용함은 방문 후기로 따로 살펴봅니다.", "descriptionEn": "Compare real places in North America using credited photos, location references and published visitor details. Prices, hours and parking appear only when documented. Quietness is assessed separately.", "country": "US", "countryGroup": ["US", "CA", "MX"], "scopeKo": "북미", "scopeEn": "North America", "kind": "world", "checksKo": ["입장권·유료 구역과 무료 일반 입장을 구분하기", "운영 시간·출입구·공사 또는 행사 안내 확인하기", "조용함은 방문 시간의 실제 후기로 확인하기"], "checksEn": ["Distinguish general admission from paid areas", "Check hours, entrances, restoration and events", "Use visitor feedback for the time you plan to visit"]},
 {"slug": "oceania-garden-pause", "titleKo": "호주·뉴질랜드 정원에서 쉬기", "titleEn": "A garden pause in Australia and New Zealand", "descriptionKo": "오세아니아의 실제 장소를 사진·주소 참고자료·이용 안내로 비교해요. 가격·운영·주차 안내는 확인된 경우에만 표시하고, 조용함은 방문 후기로 따로 살펴봅니다.", "descriptionEn": "Compare real places in Oceania using credited photos, location references and published visitor details. Prices, hours and parking appear only when documented. Quietness is assessed separately.", "country": "AU", "countryGroup": ["AU", "NZ"], "scopeKo": "오세아니아", "scopeEn": "Oceania", "kind": "world", "checksKo": ["입장권·유료 구역과 무료 일반 입장을 구분하기", "운영 시간·출입구·공사 또는 행사 안내 확인하기", "조용함은 방문 시간의 실제 후기로 확인하기"], "checksEn": ["Distinguish general admission from paid areas", "Check hours, entrances, restoration and events", "Use visitor feedback for the time you plan to visit"]},
 {"slug": "istanbul-dubai-pause", "titleKo": "이스탄불·두바이·아부다비에서 산책하기", "titleEn": "A walk in Istanbul, Dubai and Abu Dhabi", "descriptionKo": "이스탄불·아랍에미리트의 실제 장소를 사진·주소 참고자료·이용 안내로 비교해요. 가격·운영·주차 안내는 확인된 경우에만 표시하고, 조용함은 방문 후기로 따로 살펴봅니다.", "descriptionEn": "Compare real places in Istanbul and the UAE using credited photos, location references and published visitor details. Prices, hours and parking appear only when documented. Quietness is assessed separately.", "country": "TR", "countryGroup": ["TR", "AE"], "scopeKo": "이스탄불·아랍에미리트", "scopeEn": "Istanbul and the UAE", "kind": "world", "checksKo": ["입장권·유료 구역과 무료 일반 입장을 구분하기", "운영 시간·출입구·공사 또는 행사 안내 확인하기", "조용함은 방문 시간의 실제 후기로 확인하기"], "checksEn": ["Distinguish general admission from paid areas", "Check hours, entrances, restoration and events", "Use visitor feedback for the time you plan to visit"]},
 {"slug": "south-africa-garden-pause", "titleKo": "남아공의 정원에서 쉬기", "titleEn": "A garden pause in South Africa", "descriptionKo": "남아공의 실제 장소를 사진·주소 참고자료·이용 안내로 비교해요. 가격·운영·주차 안내는 확인된 경우에만 표시하고, 조용함은 방문 후기로 따로 살펴봅니다.", "descriptionEn": "Compare real places in South Africa using credited photos, location references and published visitor details. Prices, hours and parking appear only when documented. Quietness is assessed separately.", "country": "ZA", "countryGroup": ["ZA"], "scopeKo": "남아공", "scopeEn": "South Africa", "kind": "world", "checksKo": ["입장권·유료 구역과 무료 일반 입장을 구분하기", "운영 시간·출입구·공사 또는 행사 안내 확인하기", "조용함은 방문 시간의 실제 후기로 확인하기"], "checksEn": ["Distinguish general admission from paid areas", "Check hours, entrances, restoration and events", "Use visitor feedback for the time you plan to visit"]},
];
export function findGuide(slug:string){return guides.find(guide=>guide.slug===slug);}
export function guidePlaces(guide:Guide,places:Place[]):Place[]{
 if(guide.kind==='world')return (guide.countryGroup||[guide.country]).flatMap(country=>places.filter(p=>(p.country||'KR')===country).sort((a,b)=>Number(!!b.image)-Number(!!a.image)||Number(b.detailLevel==='enriched')-Number(a.detailLevel==='enriched')).slice(0,3));
 return places.filter(place=>{
  if((place.country||'KR')!==guide.country)return false;
  if(guide.kind==='intent')return (!guide.region||inRegion(place,guide.region))&&(!guide.category||place.category===guide.category)&&(!guide.condition||matchesCondition(place,guide.condition))&&(!!guide.condition||!!place.visitDetails?.length);
  if(guide.kind==='seoul')return place.city==='서울'&&place.category==='cafe';
  if(guide.kind==='cheongju')return place.city==='청주'||/청주시/.test(place.address);
  if(guide.kind==='private')return place.city==='서울'&&matchesPlaceTheme(place,'private-room');
  if(guide.kind==='spa')return matchesPlaceTheme(place,'premium-spa');
  if(guide.kind==='water')return place.category==='drive'&&/호|저수지|해안|바다|뱃길|대교/.test(place.name+' '+place.description);
  if(guide.kind==='us')return !!place.image;
  if(guide.kind==='photos')return (place.photos?.length||0)>=3&&!!place.visitDetails?.length;
  return false;
 }).sort((a,b)=>Number(!!b.photos?.length)-Number(!!a.photos?.length)||Number(!!b.image)-Number(!!a.image)||a.id.localeCompare(b.id)).slice(0,guide.kind==='photos'?50:12);
}
