const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),cache={};
function load(file){file=path.resolve(file);if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));if(cache[file])return cache[file].exports;const mod={exports:{}};cache[file]=mod;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const req=name=>name.startsWith('.')?load(path.resolve(path.dirname(file),name)+(name.endsWith('.json')?'':'.ts')):require(name);new Function('require','module','exports',source)(req,mod,mod.exports);return mod.exports;}
const {catalog}=load(path.join(root,'lib/catalog.ts')),{countries,countryCodes}=load(path.join(root,'lib/countries.ts'));
const {visitFacts}=load(path.join(root,'lib/visit-facts.ts'));
const expanded=load(path.join(root,'lib/expanded-catalog.json')),manifest=load(path.join(root,'lib/catalog-source-manifest.json'));
assert.equal(new Set(catalog.map(p=>p.id)).size,catalog.length,'duplicate catalog IDs');
assert.equal(new Set(manifest.map(p=>p.id)).size,manifest.length,'duplicate source IDs');
assert.equal(manifest.length,expanded.length,'missing source records');
for(const p of catalog){assert(countries[p.country],'unsupported country: '+p.id);assert(/^https:\/\//.test(p.source),'missing HTTPS source: '+p.id);if(p.lat!=null)assert(Number.isFinite(p.lat)&&Math.abs(p.lat)<=90&&Number.isFinite(p.lon)&&Math.abs(p.lon)<=180,'invalid coordinates: '+p.id);}
for(const p of expanded){const m=manifest.find(x=>x.id===p.id);assert(m&&m.country===p.country&&m.detailLevel===p.detailLevel,'inconsistent provenance: '+p.id);if(p.image){assert(fs.existsSync(path.join(root,'public',p.image)),'missing local photo: '+p.id);assert(p.photos?.every(x=>x.credit&&x.source&&x.original&&/^https:\/\//.test(x.licenseUrl)),'missing photo rights: '+p.id);}}
const counts=countryCodes.map(code=>{const places=catalog.filter(p=>p.country===code);assert(places.length,'country without places: '+code);return {country:code,name:countries[code].nameEn,places:places.length,photos:places.filter(p=>p.image).length,basic:places.filter(p=>p.detailLevel==='basic').length,parking:places.filter(p=>visitFacts(p).parking).length,seating:places.filter(p=>visitFacts(p).seating).length};});
const report={places:catalog.length,countries:countryCodes.length,newPlaces:expanded.length,newPhotos:expanded.filter(p=>p.image).length,newEnriched:expanded.filter(p=>p.detailLevel==='enriched').length,newBasic:expanded.filter(p=>p.detailLevel==='basic').length,reviewMemos:catalog.filter(p=>p.externalMemo).length,refreshedDomestic:Object.keys(load(path.join(root,'lib/visit-information.json'))).length,coverage:counts};
if(process.argv.includes('--json'))console.log(JSON.stringify(report,null,2));else {console.log(`Catalog valid: ${report.places} places / ${report.countries} countries; ${report.newPlaces} additions (${report.newEnriched} enriched, ${report.newBasic} basic), ${report.newPhotos} new licensed photos.`);console.table(counts);}
