const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const {createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync(path.join(root,'drizzle')).filter(x=>x.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
let user=null;const secret='test-owner-setup-secret-at-least-32-characters';
const env={OWNER_SETUP_HASH:createHash('sha256').update(secret).digest('hex'),DB:{prepare(query){let params=[];const stmt=sql.prepare(query);return{bind(...x){params=x;return this;},async first(){return stmt.get(...params)||null;},async all(){return{results:stmt.all(...params)};},async run(){const r=stmt.run(...params);return {success:true,meta:{changes:r.changes}};}};}}};
const cache={};function load(file){file=path.resolve(file);if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));if(cache[file])return cache[file].exports;const mod={exports:{}};cache[file]=mod;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const req=name=>{if(name==='cloudflare:workers')return {env};if(name==='@/lib/site-auth'||name==='./site-auth')return {getSiteUser:async()=>user,googleReady:()=>false,launchEnv:()=>env,siteOrigin:()=>"https://example.test"};if(name==='@/app/chatgpt-auth')return{getChatGPTUser:async()=>user};if(name.startsWith('@/'))return load(path.join(root,name.slice(2)+(name.endsWith('.json')?'':'.ts')));if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name)+(name.endsWith('.json')?'':'.ts'));return require(name);};new Function('require','module','exports',source)(req,mod,mod.exports);return mod.exports;}
const api=load(path.join(root,'app/api/action/route.ts')),dataRoute=load(path.join(root,'app/api/data/route.ts')),admin=load(path.join(root,'app/api/admin/route.ts'));
const data={GET:(request=new Request('https://example.test/api/data'))=>dataRoute.GET(request)};
async function post(action,payload,origin='https://example.test'){return api.POST(new Request('https://example.test/api/action',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify({action,payload})}));}
const proposal={city:'서울',category:'cafe',name:'검증용 카페',address:'서울 검증용 주소',source:'https://example.test/cafe',note:'테스트',notChildTarget:true,ack:true};
const review={placeId:'cj-daechung',satisfied:1,noise:'조용함',crowd:'여유로움',comfort:'편함',day:'평일',time:'오후',tags:['작은 음악']};
(async()=>{
 const {regionCamera,fullMapCamera,panCamera,zoomCamera,gestureCamera,constrainCamera,MAX_MAP_ZOOM}=load(path.join(root,'lib/atlas-camera.ts'));
 const mapGeometry=load(path.join(root,'lib/korea-map.json'));
 const jeju=mapGeometry.regions.find(r=>r.name==='제주'),seoul=mapGeometry.regions.find(r=>r.name==='서울');
 let camera=regionCamera(jeju);
 assert(camera.scale>1,'Jeju selection focuses the island');
 const dragged=panCamera(camera,100,150);assert.equal(dragged.x,camera.x+100);assert.equal(dragged.y,camera.y+150,'focused map remains draggable');
 const anchor={x:300,y:350},zoomed=zoomCamera(camera,1.1,anchor);
 assert(Math.abs((anchor.x-camera.x)/camera.scale-(anchor.x-zoomed.x)/zoomed.scale)<1e-8,'wheel zoom keeps the pointer over the same longitude');
 assert(Math.abs((anchor.y-camera.y)/camera.scale-(anchor.y-zoomed.y)/zoomed.scale)<1e-8,'wheel zoom keeps the pointer over the same latitude');
 for(let i=0;i<12;i++)camera=zoomCamera(camera,1/1.35);
 assert.deepEqual(camera,fullMapCamera(),'zooming out of Jeju always recovers the complete national map');
 assert(seoul.center[0]>=20&&seoul.center[0]<=700&&seoul.center[1]>=0&&seoul.center[1]<=710,'Seoul is reachable again in national view');
 const seoulCamera=regionCamera(seoul);assert(Math.abs(seoulCamera.x+seoul.center[0]*seoulCamera.scale-360)<1e-8,'next region selection centres Seoul');
 const pinched=gestureCamera(fullMapCamera(),[{x:260,y:355},{x:460,y:355}],[{x:260,y:405},{x:660,y:405}]);
 assert.equal(pinched.scale,2);assert.equal(pinched.x+360*pinched.scale,460);assert.equal(pinched.y+355*pinched.scale,405,'pinch combines scaling and midpoint movement');
 assert.equal(zoomCamera(pinched,100).scale,MAX_MAP_ZOOM,'zoom is bounded');
 const bounded=constrainCamera({x:1e6,y:-1e6,scale:3});assert((360-bounded.x)/3>=20&&(360-bounded.x)/3<=700&&(355-bounded.y)/3>=0&&(355-bounded.y)/3<=710,'long drags cannot lose the map');
 const {catalog}=load(path.join(root,'lib/catalog.ts'));const {regionKeys,inRegion}=load(path.join(root,'lib/regions.ts'));
 assert(catalog.length>=150,'nationwide catalog included');assert.equal(new Set(catalog.map(p=>p.id)).size,catalog.length,'unique place IDs');assert(regionKeys.every(r=>catalog.some(p=>inRegion(p,r))),'all regions have places');assert(inRegion({city:'충북',address:'충청북도 청주시 상당구'},'청주'),'Cheongju includes new provincial records');
 const usData=await (await data.GET(new Request('https://example.test/api/data?country=US'))).json();
 assert.equal(usData.places.length,14,'US starter collection plus verified private spaces');assert(usData.places.every(p=>p.country==='US'),'US response is country scoped');
 const {matchesPlaceTheme,isPlaceTheme}=load(path.join(root,'lib/place-themes.ts'));
 const {placeDescription,placeVisitHint}=load(path.join(root,'lib/place-copy.ts'));
 const spacePlaces=catalog.filter(p=>p.experiences?.length);
 assert.equal(spacePlaces.length,4,'four source-verified venues introduce the space themes');
 assert.equal(catalog.filter(p=>matchesPlaceTheme(p,'private-room')).length,3);
 assert.equal(catalog.filter(p=>matchesPlaceTheme(p,'premium-spa')).length,2);
 assert.equal(catalog.filter(p=>matchesPlaceTheme(p,'exclusive-hire')).length,1);
 assert(matchesPlaceTheme(catalog.find(p=>p.id==='kr-yu-yuan'),'private-room'),'restaurant category and room privacy are independent');
 assert(!matchesPlaceTheme(catalog.find(p=>p.id==='us-atomix'),'private-room'),'exclusive hire and semi-private bar must not imply a room');
 assert(!matchesPlaceTheme({experiences:[{kind:'semi-private'}]},'private-room'),'a semi-private venue alone does not qualify');
 assert(!matchesPlaceTheme({themes:['premium-spa']},'private-room'),'premium price or spa theme does not establish privacy');
 assert(!matchesPlaceTheme({name:'Private room cafe'},'private-room'),'names are not privacy evidence');
 assert(!isPlaceTheme('semi-private')&&!isPlaceTheme(null)&&isPlaceTheme('private-room'),'URL themes are validated');
 for(const place of spacePlaces){
  assert(placeDescription(place,'ko')&&placeDescription(place,'en'));
  assert(placeVisitHint(place,'ko')&&placeVisitHint(place,'en'));
  for(const experience of place.experiences){assert(experience.source.startsWith('https://'));assert.equal(experience.checked,'2026-09-27');assert(experience.bookingEn&&experience.bookingKo);}
 }
 assert(usData.places.find(p=>p.id==='us-atomix').experiences.some(e=>e.kind==='semi-private'),'API preserves space types and booking evidence');
 assert(catalog.every(p=>placeDescription(p,'ko')&&placeDescription(p,'en')),'every catalog card has a bilingual summary');
 assert.equal(placeVisitHint({visitDetails:[{labelEn:'Parking',labelKo:'주차',textKo:'관광정보 안내: 불가능',textEn:'Tourism listing: parking unavailable'}]},'ko'),'','raw metadata does not become a visitor hint');
 assert.equal(placeVisitHint({},'ko'),'','cards without specific advice omit the repeated footer');
 assert(placeVisitHint({visitDetails:[{labelEn:'Solo visit',labelKo:'1인 이용',textKo:'정식은 2인 이상 주문입니다.',textEn:'Set meals require two diners.'}]},'ko').includes('2인'),'meaningful booking constraints remain visible');
 const {readBrowseState,writeBrowseState}=load(path.join(root,'lib/browse-state.ts'));
 const browsing={city:'서울',category:'food',theme:'private-room',term:'유유안',view:'explore',filters:{photos:true,reviewed:false,quiet:false}};
 const shared=writeBrowseState(new URL('https://example.test/kr?utm_source=instagram&resume=1'),browsing,'ko');
 assert.deepEqual(readBrowseState(shared.searchParams,regionKeys),browsing,'shared URL restores region, theme, search and filters');
 assert.equal(shared.searchParams.get('utm_source'),'instagram');assert(!shared.searchParams.has('resume'));
 assert(!shared.searchParams.has('lat')&&!shared.searchParams.has('saved'),'private device state is never serialized');
 const invalid=readBrowseState(new URLSearchParams('region=oops&theme=semi-private&category=bad&view=admin&photos=true'),regionKeys);
 assert.equal(invalid.city,'전국');assert.equal(invalid.theme,'all');assert.equal(invalid.view,'explore');assert.equal(invalid.filters.photos,false);
 const cleared=writeBrowseState(shared,{...browsing,city:'전국',category:'all',theme:'all',term:'',filters:{photos:false,reviewed:false,quiet:false}},'en');
 assert.equal(cleared.search,'?utm_source=instagram&lang=en','clearing state removes stale URL choices');
 const {toggleComparison,comparisonFacts}=load(path.join(root,'lib/place-comparison.ts'));
 assert.deepEqual(toggleComparison(['a','b','c'],'d'),['a','b','c'],'at most three comparison columns');
 assert.deepEqual(toggleComparison(['a','b'],'a'),['b'],'selection toggles off');
 const emptyComparison=comparisonFacts({...catalog[0],experiences:[],visitDetails:[],count:0,quiet:0,positive:0},'ko');
 assert(emptyComparison.some(f=>f.value.includes('조용함 확인 전')),'zero reviews never implies a quietness score');
 assert(emptyComparison.some(f=>f.value==='공식 안내에서 확인 필요'),'unknown costs are explicit');
 const atomixComparison=comparisonFacts({...catalog.find(p=>p.id==='us-atomix'),count:0,quiet:0,positive:0},'en');
 assert(atomixComparison.some(f=>f.value.includes('Semi-private')),'comparison keeps venue-specific privacy types');
 const {matchesExploreFilters,emptyFilters}=load(path.join(root,'lib/explore-filters.ts'));
 const sample={image:'/test.webp',count:5,quiet:4,resting:false};
 assert(matchesExploreFilters(sample,{photos:true,reviewed:true,quiet:true}),'filters combine correctly');
 assert(!matchesExploreFilters({...sample,image:undefined},{...emptyFilters,photos:true}),'photo filter excludes missing images');
 assert(!matchesExploreFilters({...sample,count:0},{...emptyFilters,reviewed:true}),'review filter excludes unreviewed places');
 assert(!matchesExploreFilters({...sample,count:2,quiet:2},{...emptyFilters,quiet:true}),'quiet filter requires three reviews');
 assert(!matchesExploreFilters({...sample,resting:true},{...emptyFilters,quiet:true}),'paused places stay excluded from quiet results');
 assert(usData.places.every(p=>p.visitDetails.length>=2),'US places include official visit details');
 for(const p of usData.places.filter(p=>p.image))assert(fs.existsSync(path.join(root,'public',p.image)),'listed photo exists: '+p.id);
 const krData=await (await data.GET()).json();assert(krData.places.length>=324,'existing production Korea catalog preserved');assert(krData.places.every(p=>p.country==='KR'),'Korea response excludes US');
 assert.equal((await post('suggest',proposal)).status,401,'anonymous cannot write');
 env.OWNER_GOOGLE_EMAIL='mythdriveofficial@gmail.com';
 user={userId:'supabase:owner-google',email:'mythdriveofficial@gmail.com',provider:'google',googleEmailVerified:true};
 assert.equal((await admin.GET()).status,200,'configured verified Google owner can access review queue');
 assert.equal((await (await data.GET()).json()).isOwner,true);
 user={userId:'supabase:spoof',email:'mythdriveofficial@gmail.com',provider:'google',googleEmailVerified:false};
 assert.equal((await admin.GET()).status,403,'unverified owner email rejected');
 user={userId:'another-google',email:'someone@example.test',provider:'google',googleEmailVerified:true};
 assert.equal((await admin.GET()).status,403,'other Google users have no owner role');
 user={userId:'header-only',email:'mythdriveofficial@gmail.com',provider:'chatgpt',googleEmailVerified:true};
 assert.equal((await admin.GET()).status,403,'matching non-Google email does not grant new owner access');
 user=null;

 user={userId:'visitor',email:'visitor@example.test'};
 assert.equal((await post('suggest',proposal,'https://evil.test')).status,403,'cross-origin blocked');
 assert.equal((await post('suggest',{...proposal,name:'키즈카페'})).status,400,'child-target excluded');
 assert.equal((await post('suggest',{...proposal,source:'javascript:alert(1)'})).status,400,'unsafe URL rejected');
 const nationwide=await post('suggest',{...proposal,city:'제주',name:'제주 검증 카페'});assert.equal(nationwide.status,200,'nationwide suggestions accepted');
 const submitted=await (await post('suggest',proposal)).json();assert.equal(submitted.status,'pending');
 let result=await (await data.GET()).json();assert(!result.places.some(p=>p.id===submitted.id),'pending hidden');assert(result.suggestions.every(p=>p.status==='pending'));
 assert.equal((await post('decide',{id:submitted.id,status:'approved',reason:'ok',notChildTarget:true})).status,403,'non-owner approval blocked');
 assert.equal((await admin.GET()).status,403,'non-owner queue blocked');
 assert.equal((await post('review',{...review,placeId:submitted.id})).status,404,'pending review blocked');
 assert.equal((await post('review',{...review,satisfied:99})).status,400,'invalid rating blocked');
 assert.equal((await post('review',review)).status,200);
 assert.equal((await post('review',{...review,satisfied:0})).status,200);
 result=await (await data.GET()).json();assert.equal(result.places.find(p=>p.id===review.placeId).count,1,'repeat review updates');assert.equal(result.places.find(p=>p.id===review.placeId).positive,0);
 user={userId:'other',email:'other@example.test'};result=await (await data.GET()).json();assert.equal(result.reviews.length,0);assert.equal(result.suggestions.length,0,'private records not leaked');
 assert.equal((await post('deleteReview',{placeId:review.placeId})).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM reviews').get().n,1,'cannot delete another user review');
 assert.equal((await post('claimOwner',{token:'x'.repeat(40)})).status,403);
 user={userId:'owner',email:'owner@example.test'};assert.equal((await post('claimOwner',{token:secret})).status,200);
 assert.equal((await post('decide',{id:submitted.id,status:'approved',reason:'ok',notChildTarget:false})).status,400,'approval requires child-target check');
 assert.equal((await post('decide',{id:submitted.id,status:'approved',reason:'ok',notChildTarget:true})).status,200);
 result=await (await data.GET()).json();assert(result.places.some(p=>p.id===submitted.id),'approved visible');assert.equal((await admin.GET()).status,200);
 user={userId:'other',email:'other@example.test'};assert.equal((await post('claimOwner',{token:secret})).status,403,'owner cannot be reassigned');
 await post('save',{placeId:review.placeId,saved:true});result=await (await data.GET()).json();assert(result.saved.includes(review.placeId),'bookmark persists');
 const {ranked}=load(path.join(root,'lib/ranking.ts'));assert.equal(ranked([{id:'none',count:0,positive:0,quiet:0},{id:'one',count:1,positive:1,quiet:1},{id:'loud',count:4,positive:4,quiet:0}]).length,0);
 assert.equal(ranked([{id:'eligible',count:3,positive:3,quiet:3}])[0].id,'eligible');
 sql.prepare('UPDATE reviews SET updated_at=?').run(Date.now()-91*86400000);result=await (await data.GET()).json();assert.equal(result.places.find(p=>p.id===review.placeId).count,0,'old reviews excluded');
 const {distanceKm,qualityState}=load(path.join(root,'lib/discovery.ts'));assert.equal(distanceKm({lat:0,lon:0},{lat:0,lon:0}),0);assert(Math.abs(distanceKm({lat:0,lon:0},{lat:1,lon:0})-111.195)<.01);
 assert.equal(qualityState({n:7,bad:7,days:3,first:Date.now()-10*86400000,last:Date.now()}),'watch','small sample cannot pause');
 const {plans,addMonths}=load(path.join(root,'lib/plans.ts'));assert.equal(plans[1].amount,4900*6*.9);assert.equal(plans[2].amount,4900*12*.7);assert.equal(new Date(addMonths(Date.UTC(2026,0,31),1)).toISOString().slice(0,10),'2026-02-28');
 user={userId:'trial-user',email:'trial@example.test'};assert.equal((await post('trial',{})).status,200);assert.equal((await post('trial',{})).status,409);result=await (await data.GET()).json();assert(result.membership.active);assert('insights' in result.places[0]);
 sql.prepare('UPDATE trials SET started_at=? WHERE user_id=?').run(Date.now()-8*86400000,user.userId);result=await (await data.GET()).json();assert(!result.membership.active);assert(!('insights' in result.places[0]),'paid time buckets hidden from free accounts');
 const payOrder=load(path.join(root,'app/api/payments/order/route.ts')),payConfirm=load(path.join(root,'app/api/payments/confirm/route.ts'));
 const paymentRequest=(route,payload)=>route.POST(new Request('https://example.test/api/payments/test',{method:'POST',headers:{origin:'https://example.test','Content-Type':'application/json'},body:JSON.stringify(payload)}));
 assert.equal((await paymentRequest(payOrder,{planId:'month',consent:true})).status,503,'unconfigured payments disabled');
 env.TOSS_CLIENT_KEY='test_ck_mock';env.TOSS_SECRET_KEY='test_sk_mock';
 const concurrent=await Promise.all([paymentRequest(payOrder,{planId:'half',consent:true,amount:1}),paymentRequest(payOrder,{planId:'half',consent:true,amount:1})]);const orders=await Promise.all(concurrent.map(x=>x.json()));const order=orders[0];assert.equal(order.amount.value,26460,'server owns pricing');assert.equal(order.orderId,orders[1].orderId,'concurrent purchase requests reuse one pending order');
 let fetches=0;const originalFetch=global.fetch;global.fetch=async()=>{fetches++;return Response.json({orderId:order.orderId,totalAmount:26460,currency:'KRW',paymentKey:'mock-payment-key',status:'DONE'});};
 assert.equal((await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:1})).status,400);assert.equal(fetches,0,'tampered amount never reaches payment provider');
 user={userId:'foreign-user',email:'f@example.test'};assert.equal((await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:26460})).status,404);
 user={userId:'trial-user',email:'trial@example.test'};const paid=await (await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:26460})).json();assert(paid.ok);const repeated=await (await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:26460})).json();assert.equal(paid.until,repeated.until);assert.equal(fetches,1,'confirmation idempotent');global.fetch=originalFetch;
 result=await (await data.GET()).json();assert.equal(result.membership.kind,'paid');
 user={userId:'quality-user',email:'q@example.test'};const now=Date.now();for(let i=0;i<8;i++)sql.prepare('INSERT INTO reviews(user_id,place_id,satisfied,noise,crowd,comfort,day,time,tags,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run('quality-'+i,'seoul-san',1,'시끄러움','붐빔','보통','평일','오후','[]',now-i*86400000);
 const {refreshQuality}=load(path.join(root,'lib/quality.ts'));await refreshQuality('seoul-san');result=await (await data.GET()).json();assert(result.places.find(p=>p.id==='seoul-san').resting);assert(!ranked(result.places).some(p=>p.id==='seoul-san'),'crowded places leave recommendation');
 sql.prepare('DELETE FROM reviews WHERE place_id=?').run('seoul-san');await refreshQuality('seoul-san');result=await (await data.GET()).json();assert(result.places.find(p=>p.id==='seoul-san').resting,'loss of evidence cannot unpause');
 assert.equal((await post('moderate',{placeId:'cj-daechung',mode:'paused'})).status,403,'moderation owner only');

 const visit=load(path.join(root,'app/api/visit/route.ts')),stats=load(path.join(root,'app/api/stats/route.ts'));
 const {koreaDay}=load(path.join(root,'lib/traffic.ts'));
 assert.equal(koreaDay(Date.UTC(2026,8,14,14,59)),'2026-09-14');
 assert.equal(koreaDay(Date.UTC(2026,8,14,15,0)),'2026-09-15','Korean calendar boundary');
 const visitRequest=origin=>new Request('https://example.test/api/visit',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:'{}'});
 assert.equal((await visit.POST(visitRequest('https://other.test'))).status,403);
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM daily_visits').get().n,0,'rejected visits not counted');
 assert.equal((await visit.POST(visitRequest('https://example.test'))).status,204);
 assert.equal((await visit.POST(visitRequest('https://example.test'))).status,204);
 assert.deepEqual(sql.prepare('PRAGMA table_info(daily_visits)').all().map(c=>c.name),['day','views'],'only aggregate visit data stored');
 user=null;assert.equal((await stats.GET()).status,403,'anonymous cannot view stats');
 user={userId:'visitor',email:'visitor@example.test'};assert.equal((await stats.GET()).status,403,'ordinary user cannot view stats');
 user={userId:'owner',email:'owner@example.test'};
 const statResponse=await stats.GET();assert.equal(statResponse.headers.get('Cache-Control'),'private, no-store');
 const report=await statResponse.json();assert.equal(report.traffic.today,2);assert.equal(report.traffic.week,2);assert.equal(report.traffic.month,2);assert.equal(report.days.length,1);
 const sitemap=load(path.join(root,'app/sitemap.xml/route.ts'));
 const xml=await sitemap.GET().text();assert(xml.includes('https://nothotplace.com/plus'));assert(xml.includes('https://nothotplace.com/trips'));assert(!xml.includes('/stats')&&!xml.includes('/login'));
 const pages=load(path.join(root,'lib/place-pages.ts'));
 const usPlace=catalog.find(p=>p.country==='US'),krPlace=catalog.find(p=>p.country==='KR');
 assert.equal((xml.match(/<url>/g)||[]).length,6+catalog.length*2,'every published catalog place has both language URLs');
 for(const place of catalog)for(const language of ['en','ko']){
  const url='https://nothotplace.com'+pages.placePath(place.id,language);
  assert(xml.includes('<loc>'+url+'</loc>'),'place listed in sitemap: '+place.id+' '+language);
  assert(xml.includes('hreflang="'+language+'" href="'+url+'"'),'reciprocal locale link');
 }
 assert.equal(pages.findCatalogPlace(submitted.id),undefined,'DB suggestions are not claimed as catalog pages');
 assert(pages.sharePlacePath({...krPlace,id:submitted.id},'ko').startsWith('/kr?'),'approved suggestions retain live explorer share links');
 assert.equal(pages.sharePlacePath(usPlace,'en'),pages.placePath(usPlace.id,'en'),'catalog sharing opens its independent page');
 assert.equal(new URL(pages.explorerPath(usPlace,'en'),'https://example.test').searchParams.get('place'),usPlace.id,'review return path retains selected place');
 assert(!pages.isPlaceLanguage('fr'),'unsupported languages rejected');
 assert(!pages.findCatalogPlace('not-a-real-place'),'missing places stay missing');
 assert(pages.relatedPlaces(usPlace).every(p=>p.id!==usPlace.id&&p.country===usPlace.country&&p.city===usPlace.city),'related links stay regional');

 // Detail API keeps personal state private and applies the same quality window as discovery.
 const detail=load(path.join(root,'app/api/places/[id]/route.ts'));
 const detailGet=id=>detail.GET(new Request('https://example.test/api/places/'+id),{params:Promise.resolve({id})});
 user=null;
 assert.equal((await detailGet('missing-place')).status,404);
 let detailResponse=await detailGet('cj-daechung');assert.equal(detailResponse.headers.get('Cache-Control'),'private, no-store');
 let detailData=await detailResponse.json();assert.equal(detailData.signedIn,false);assert.equal(detailData.saved,false);assert.equal(detailData.review,null);assert.deepEqual(detailData.insights,[]);
 user={userId:'detail-owner',email:'detail@example.test'};
 await post('save',{placeId:'cj-daechung',saved:true});await post('review',{...review,noise:'조용함',crowd:'여유로움'});
 detailData=await (await detailGet('cj-daechung')).json();assert.equal(detailData.saved,true);assert.equal(detailData.review.noise,'조용함');assert.equal(detailData.summary.count,1,'expired reviews excluded');assert.equal(detailData.summary.quiet,1);assert.equal(detailData.summary.relaxed,1);assert(!('user_id' in detailData.review));
 user={userId:'detail-other',email:'other-detail@example.test'};
 detailData=await (await detailGet('cj-daechung')).json();assert.equal(detailData.review,null);assert.equal(detailData.saved,false);assert.equal(detailData.summary.count,1,'aggregate remains public');
 user={userId:'detail-owner',email:'detail@example.test'};await post('deleteReview',{placeId:'cj-daechung'});detailData=await (await detailGet('cj-daechung')).json();assert.equal(detailData.summary.count,0);
 const guides=catalog.filter(p=>p.featured);assert.equal(guides.length,30);assert.equal(catalog.filter(p=>p.country==='KR'&&p.image).length,43);
 for(const p of guides){assert.equal(p.photos.length,3);assert(p.descriptionEn&&p.visitDetails.length>=4);assert.equal(new Set(p.photos.map(x=>x.original)).size,3);for(const photo of p.photos){assert(photo.original.startsWith('https://tong.visitkorea.or.kr/'));assert(photo.source===p.source);assert(fs.existsSync(path.join(root,'public',photo.src)));assert(photo.width>0&&photo.height>0);}}
 const engagement=load(path.join(root,'app/api/engagement/route.ts'));
 const engagementRequest=(body,headers={})=>new Request('https://example.test/api/engagement',{method:'POST',headers:{origin:'https://example.test','Content-Type':'application/json',...headers},body:typeof body==='string'?body:JSON.stringify(body)});
 const event={event:'place_view',country:'KR',source:'instagram'};
 assert.equal((await engagement.POST(engagementRequest(event,{origin:'https://other.test'}))).status,403);
 assert.equal((await engagement.POST(engagementRequest({...event,userId:'should-never-store'}))).status,400);
 assert.equal((await engagement.POST(engagementRequest({...event,source:'https://private.example/query'}))).status,400);
 assert.equal((await engagement.POST(engagementRequest({...event,event:'unknown'}))).status,400);
 assert.equal((await engagement.POST(engagementRequest('bad json'))).status,400);
 assert.equal((await engagement.POST(engagementRequest('x'.repeat(201)))).status,413);
 assert.equal((await engagement.POST(engagementRequest(event,{dnt:'1'}))).status,204);
 assert.equal((await engagement.POST(engagementRequest(event,{'sec-gpc':'1'}))).status,204);
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM engagement_totals').get().n,0,'privacy signals and invalid events do not count');
 await engagement.POST(engagementRequest(event));await engagement.POST(engagementRequest(event));
 assert.equal(sql.prepare('SELECT total FROM engagement_totals').get().total,2);
 assert.deepEqual(sql.prepare('PRAGMA table_info(engagement_totals)').all().map(c=>c.name),['day','event','country','source','total'],'only finite aggregate dimensions are stored');
 user={userId:'owner',email:'owner@example.test'};const engagementReport=await (await stats.GET()).json();assert.equal(engagementReport.engagement[0].total,2);
 console.log('PASS: direct place review/save privacy, review freshness, 30 bilingual guides / 90 licensed assets and aggregate engagement boundaries.');
 console.log('PASS: bilingual place paths, reciprocal sitemap links, community suggestion sharing and review return paths.');
 const {trips,tripThemes}=load(path.join(root,'lib/trips.ts'));assert(trips.length>=9);assert.equal(new Set(trips.map(t=>t.id)).size,trips.length);assert(Object.keys(tripThemes).every(t=>trips.filter(p=>p.theme===t).length>=3));
 for(const trip of trips.filter(t=>t.placeId)){const place=catalog.find(p=>p.id===trip.placeId);assert(place&&place.country==='KR'&&place.category===trip.category,'curated itinerary links to a matching published venue');}
 const {privateBookingFacts}=load(path.join(root,'lib/place-themes.ts'));
 const yuYuan=catalog.find(p=>p.id==='kr-yu-yuan').experiences[0];
 assert(privateBookingFacts(yuYuan,'ko')[0].value.includes('문의'),'unknown room capacity remains unknown');
 assert(privateBookingFacts(yuYuan,'en')[1].value.includes('room type'),'verified minimum-spend conditions remain visible');
 const atomix=catalog.find(p=>p.id==='us-atomix').experiences[0];
 assert(privateBookingFacts(atomix,'en')[0].value.includes('15'),'confirmed capacity is presented');
 assert(privateBookingFacts(atomix,'ko')[1].value.includes('공개 금액 없음'),'unpublished minimum spend never implies zero');
 for(const id of ['kr-osulloc-tea-stone','kr-sayuwon'])assert(!matchesPlaceTheme(catalog.find(p=>p.id===id),'private-room'),'a restful setting is not evidence of an exclusive room');
 const manifest=JSON.parse(fs.readFileSync(path.join(root,'public/manifest.webmanifest'),'utf8'));assert.equal(manifest.display,'standalone');for(const icon of manifest.icons)assert(fs.existsSync(path.join(root,'public',icon.src)));
 // Payment replay must remain bound to the payment originally verified for this user.
 user={userId:'trial-user',email:'trial@example.test'};
 assert.equal((await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'different-payment-key',amount:26460})).status,400);
 const {reconcilePayment}=load(path.join(root,'lib/payment-service.ts'));
 const stored=sql.prepare('SELECT * FROM payment_orders WHERE id=?').get(order.orderId);
 await reconcilePayment(stored,{orderId:order.orderId,totalAmount:26460,currency:'KRW',paymentKey:'mock-payment-key',status:'CANCELED'});
 assert(!(await (await data.GET()).json()).membership.active,'refunded pass stops access after trial expiry');
 await reconcilePayment(stored,{orderId:order.orderId,totalAmount:26460,currency:'KRW',paymentKey:'mock-payment-key',status:'DONE'});
 assert(!(await (await data.GET()).json()).membership.active,'stale completion cannot restore refunded access');
 console.log('PASS: aggregate visits, Korean date boundary, stats permissions, sitemap, travel themes, install assets and payment replay/refund handling.');
 console.log('PASS: trial expiry, premium gating, distance, prices, payment integrity/idempotency, automatic recommendation hold,  nationwide catalog, regional filtering, authorization, owner binding, approval visibility, persistence, input validation, review deduplication, 90-day aggregation, recommendation eligibility.');
})().catch(e=>{console.error(e);process.exitCode=1;});
