const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const {createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync(path.join(root,'drizzle')).filter(x=>x.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
let user=null;const secret='test-owner-setup-secret-at-least-32-characters';
const env={OWNER_SETUP_HASH:createHash('sha256').update(secret).digest('hex'),DB:{prepare(query){let params=[];const stmt=sql.prepare(query);return{bind(...x){params=x;return this;},async first(){return stmt.get(...params)||null;},async all(){return{results:stmt.all(...params)};},async run(){const r=stmt.run(...params);return {success:true,meta:{changes:r.changes}};}};}}};
const cache={};function load(file){file=path.resolve(file);if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));if(cache[file])return cache[file].exports;const mod={exports:{}};cache[file]=mod;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const req=name=>{if(name==='cloudflare:workers')return {env};if(name==='@/lib/site-auth'||name==='./site-auth')return {getSiteUser:async()=>user,googleReady:()=>false,launchEnv:()=>env,siteOrigin:()=>"https://example.test"};if(name==='@/app/chatgpt-auth')return{getChatGPTUser:async()=>user};if(name.startsWith('@/'))return load(path.join(root,name.slice(2)+(name.endsWith('.json')?'':'.ts')));if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name)+(name.endsWith('.json')?'':'.ts'));return require(name);};new Function('require','module','exports',source)(req,mod,mod.exports);return mod.exports;}
const api=load(path.join(root,'app/api/action/route.ts')),data=load(path.join(root,'app/api/data/route.ts')),admin=load(path.join(root,'app/api/admin/route.ts'));
async function post(action,payload,origin='https://example.test'){return api.POST(new Request('https://example.test/api/action',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify({action,payload})}));}
const proposal={city:'서울',category:'cafe',name:'검증용 카페',address:'서울 검증용 주소',source:'https://example.test/cafe',note:'테스트',notChildTarget:true,ack:true};
const review={placeId:'cj-daechung',satisfied:1,noise:'조용함',crowd:'여유로움',comfort:'편함',day:'평일',time:'오후',tags:['작은 음악']};
(async()=>{
 const {catalog}=load(path.join(root,'lib/catalog.ts'));const {regionKeys,inRegion}=load(path.join(root,'lib/regions.ts'));
 assert(catalog.length>=150,'nationwide catalog included');assert.equal(new Set(catalog.map(p=>p.id)).size,catalog.length,'unique place IDs');assert(regionKeys.every(r=>catalog.some(p=>inRegion(p,r))),'all regions have places');assert(inRegion({city:'충북',address:'충청북도 청주시 상당구'},'청주'),'Cheongju includes new provincial records');
 assert.equal((await post('suggest',proposal)).status,401,'anonymous cannot write');
 env.OWNER_GOOGLE_EMAIL='mythdriveofficial@gmail.com';
 user={userId:'supabase:owner-google',email:'mythdriveofficial@gmail.com',provider:'google',googleEmailVerified:true};
 assert.equal((await admin.GET()).status,200,'configured verified Google owner can access review queue');
 assert.equal((await (await data.GET()).json()).isOwner,true);
 user={userId:'supabase:spoof',email:'mythdriveofficial@gmail.com',provider:'google',googleEmailVerified:false};
 assert.equal((await admin.GET()).status,403,'unverified owner email rejected');
 user={userId:'another-google',email:'someone@example.test',provider:'google',googleEmailVerified:true};
 assert.equal((await admin.GET()).status,403,'other Google users have no owner role');
 user={userId:'header-only',email:'mythdriveofficial@gmail.com',provider:'chatgpt',googleEmailVerified:true};
 assert.equal((await admin.GET()).status,403,'matching non-Google email does not grant new owner access');
 user=null;

 user={userId:'visitor',email:'visitor@example.test'};
 assert.equal((await post('suggest',proposal,'https://evil.test')).status,403,'cross-origin blocked');
 assert.equal((await post('suggest',{...proposal,name:'키즈카페'})).status,400,'child-target excluded');
 assert.equal((await post('suggest',{...proposal,source:'javascript:alert(1)'})).status,400,'unsafe URL rejected');
 const nationwide=await post('suggest',{...proposal,city:'제주',name:'제주 검증 카페'});assert.equal(nationwide.status,200,'nationwide suggestions accepted');
 const submitted=await (await post('suggest',proposal)).json();assert.equal(submitted.status,'pending');
 let result=await (await data.GET()).json();assert(!result.places.some(p=>p.id===submitted.id),'pending hidden');assert(result.suggestions.every(p=>p.status==='pending'));
 assert.equal((await post('decide',{id:submitted.id,status:'approved',reason:'ok',notChildTarget:true})).status,403,'non-owner approval blocked');
 assert.equal((await admin.GET()).status,403,'non-owner queue blocked');
 assert.equal((await post('review',{...review,placeId:submitted.id})).status,404,'pending review blocked');
 assert.equal((await post('review',{...review,satisfied:99})).status,400,'invalid rating blocked');
 assert.equal((await post('review',review)).status,200);
 assert.equal((await post('review',{...review,satisfied:0})).status,200);
 result=await (await data.GET()).json();assert.equal(result.places.find(p=>p.id===review.placeId).count,1,'repeat review updates');assert.equal(result.places.find(p=>p.id===review.placeId).positive,0);
 user={userId:'other',email:'other@example.test'};result=await (await data.GET()).json();assert.equal(result.reviews.length,0);assert.equal(result.suggestions.length,0,'private records not leaked');
 assert.equal((await post('deleteReview',{placeId:review.placeId})).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM reviews').get().n,1,'cannot delete another user review');
 assert.equal((await post('claimOwner',{token:'x'.repeat(40)})).status,403);
 user={userId:'owner',email:'owner@example.test'};assert.equal((await post('claimOwner',{token:secret})).status,200);
 assert.equal((await post('decide',{id:submitted.id,status:'approved',reason:'ok',notChildTarget:false})).status,400,'approval requires child-target check');
 assert.equal((await post('decide',{id:submitted.id,status:'approved',reason:'ok',notChildTarget:true})).status,200);
 result=await (await data.GET()).json();assert(result.places.some(p=>p.id===submitted.id),'approved visible');assert.equal((await admin.GET()).status,200);
 user={userId:'other',email:'other@example.test'};assert.equal((await post('claimOwner',{token:secret})).status,403,'owner cannot be reassigned');
 await post('save',{placeId:review.placeId,saved:true});result=await (await data.GET()).json();assert(result.saved.includes(review.placeId),'bookmark persists');
 const {ranked}=load(path.join(root,'lib/ranking.ts'));assert.equal(ranked([{id:'none',count:0,positive:0,quiet:0},{id:'one',count:1,positive:1,quiet:1},{id:'loud',count:4,positive:4,quiet:0}]).length,0);
 assert.equal(ranked([{id:'eligible',count:3,positive:3,quiet:3}])[0].id,'eligible');
 sql.prepare('UPDATE reviews SET updated_at=?').run(Date.now()-91*86400000);result=await (await data.GET()).json();assert.equal(result.places.find(p=>p.id===review.placeId).count,0,'old reviews excluded');
 const {distanceKm,qualityState}=load(path.join(root,'lib/discovery.ts'));assert.equal(distanceKm({lat:0,lon:0},{lat:0,lon:0}),0);assert(Math.abs(distanceKm({lat:0,lon:0},{lat:1,lon:0})-111.195)<.01);
 assert.equal(qualityState({n:7,bad:7,days:3,first:Date.now()-10*86400000,last:Date.now()}),'watch','small sample cannot pause');
 const {plans,addMonths}=load(path.join(root,'lib/plans.ts'));assert.equal(plans[1].amount,4900*6*.9);assert.equal(plans[2].amount,4900*12*.7);assert.equal(new Date(addMonths(Date.UTC(2026,0,31),1)).toISOString().slice(0,10),'2026-02-28');
 user={userId:'trial-user',email:'trial@example.test'};assert.equal((await post('trial',{})).status,200);assert.equal((await post('trial',{})).status,409);result=await (await data.GET()).json();assert(result.membership.active);assert('insights' in result.places[0]);
 sql.prepare('UPDATE trials SET started_at=? WHERE user_id=?').run(Date.now()-8*86400000,user.userId);result=await (await data.GET()).json();assert(!result.membership.active);assert(!('insights' in result.places[0]),'paid time buckets hidden from free accounts');
 const payOrder=load(path.join(root,'app/api/payments/order/route.ts')),payConfirm=load(path.join(root,'app/api/payments/confirm/route.ts'));
 const paymentRequest=(route,payload)=>route.POST(new Request('https://example.test/api/payments/test',{method:'POST',headers:{origin:'https://example.test','Content-Type':'application/json'},body:JSON.stringify(payload)}));
 assert.equal((await paymentRequest(payOrder,{planId:'month',consent:true})).status,503,'unconfigured payments disabled');
 env.TOSS_CLIENT_KEY='test_ck_mock';env.TOSS_SECRET_KEY='test_sk_mock';
 const concurrent=await Promise.all([paymentRequest(payOrder,{planId:'half',consent:true,amount:1}),paymentRequest(payOrder,{planId:'half',consent:true,amount:1})]);const orders=await Promise.all(concurrent.map(x=>x.json()));const order=orders[0];assert.equal(order.amount.value,26460,'server owns pricing');assert.equal(order.orderId,orders[1].orderId,'concurrent purchase requests reuse one pending order');
 let fetches=0;const originalFetch=global.fetch;global.fetch=async()=>{fetches++;return Response.json({orderId:order.orderId,totalAmount:26460,currency:'KRW',paymentKey:'mock-payment-key',status:'DONE'});};
 assert.equal((await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:1})).status,400);assert.equal(fetches,0,'tampered amount never reaches payment provider');
 user={userId:'foreign-user',email:'f@example.test'};assert.equal((await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:26460})).status,404);
 user={userId:'trial-user',email:'trial@example.test'};const paid=await (await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:26460})).json();assert(paid.ok);const repeated=await (await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:26460})).json();assert.equal(paid.until,repeated.until);assert.equal(fetches,1,'confirmation idempotent');global.fetch=originalFetch;
 result=await (await data.GET()).json();assert.equal(result.membership.kind,'paid');
 user={userId:'quality-user',email:'q@example.test'};const now=Date.now();for(let i=0;i<8;i++)sql.prepare('INSERT INTO reviews(user_id,place_id,satisfied,noise,crowd,comfort,day,time,tags,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run('quality-'+i,'seoul-san',1,'시끄러움','붐빔','보통','평일','오후','[]',now-i*86400000);
 const {refreshQuality}=load(path.join(root,'lib/quality.ts'));await refreshQuality('seoul-san');result=await (await data.GET()).json();assert(result.places.find(p=>p.id==='seoul-san').resting);assert(!ranked(result.places).some(p=>p.id==='seoul-san'),'crowded places leave recommendation');
 sql.prepare('DELETE FROM reviews WHERE place_id=?').run('seoul-san');await refreshQuality('seoul-san');result=await (await data.GET()).json();assert(result.places.find(p=>p.id==='seoul-san').resting,'loss of evidence cannot unpause');
 assert.equal((await post('moderate',{placeId:'cj-daechung',mode:'paused'})).status,403,'moderation owner only');

 const visit=load(path.join(root,'app/api/visit/route.ts')),stats=load(path.join(root,'app/api/stats/route.ts'));
 const {koreaDay}=load(path.join(root,'lib/traffic.ts'));
 assert.equal(koreaDay(Date.UTC(2026,8,14,14,59)),'2026-09-14');
 assert.equal(koreaDay(Date.UTC(2026,8,14,15,0)),'2026-09-15','Korean calendar boundary');
 const visitRequest=origin=>new Request('https://example.test/api/visit',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:'{}'});
 assert.equal((await visit.POST(visitRequest('https://other.test'))).status,403);
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM daily_visits').get().n,0,'rejected visits not counted');
 assert.equal((await visit.POST(visitRequest('https://example.test'))).status,204);
 assert.equal((await visit.POST(visitRequest('https://example.test'))).status,204);
 assert.deepEqual(sql.prepare('PRAGMA table_info(daily_visits)').all().map(c=>c.name),['day','views'],'only aggregate visit data stored');
 user=null;assert.equal((await stats.GET()).status,403,'anonymous cannot view stats');
 user={userId:'visitor',email:'visitor@example.test'};assert.equal((await stats.GET()).status,403,'ordinary user cannot view stats');
 user={userId:'owner',email:'owner@example.test'};
 const statResponse=await stats.GET();assert.equal(statResponse.headers.get('Cache-Control'),'private, no-store');
 const report=await statResponse.json();assert.equal(report.traffic.today,2);assert.equal(report.traffic.week,2);assert.equal(report.traffic.month,2);assert.equal(report.days.length,1);
 const sitemap=load(path.join(root,'app/sitemap.xml/route.ts'));
 const xml=await sitemap.GET().text();assert(xml.includes('https://nothotplace.com/plus'));assert(xml.includes('https://nothotplace.com/trips'));assert(!xml.includes('/stats')&&!xml.includes('/login'));
 const {trips,tripThemes}=load(path.join(root,'lib/trips.ts'));assert.equal(trips.length,9);assert.equal(new Set(trips.map(t=>t.id)).size,9);assert(Object.keys(tripThemes).every(t=>trips.filter(p=>p.theme===t).length===3));
 const manifest=JSON.parse(fs.readFileSync(path.join(root,'public/manifest.webmanifest'),'utf8'));assert.equal(manifest.display,'standalone');for(const icon of manifest.icons)assert(fs.existsSync(path.join(root,'public',icon.src)));
 // Payment replay must remain bound to the payment originally verified for this user.
 user={userId:'trial-user',email:'trial@example.test'};
 assert.equal((await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'different-payment-key',amount:26460})).status,400);
 const {reconcilePayment}=load(path.join(root,'lib/payment-service.ts'));
 const stored=sql.prepare('SELECT * FROM payment_orders WHERE id=?').get(order.orderId);
 await reconcilePayment(stored,{orderId:order.orderId,totalAmount:26460,currency:'KRW',paymentKey:'mock-payment-key',status:'CANCELED'});
 assert(!(await (await data.GET()).json()).membership.active,'refunded pass stops access after trial expiry');
 await reconcilePayment(stored,{orderId:order.orderId,totalAmount:26460,currency:'KRW',paymentKey:'mock-payment-key',status:'DONE'});
 assert(!(await (await data.GET()).json()).membership.active,'stale completion cannot restore refunded access');
 console.log('PASS: aggregate visits, Korean date boundary, stats permissions, sitemap, travel themes, install assets and payment replay/refund handling.');
 console.log('PASS: trial expiry, premium gating, distance, prices, payment integrity/idempotency, automatic recommendation hold,  nationwide catalog, regional filtering, authorization, owner binding, approval visibility, persistence, input validation, review deduplication, 90-day aggregation, recommendation eligibility.');
})().catch(e=>{console.error(e);process.exitCode=1;});
