const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const {createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync(path.join(root,'drizzle')).filter(x=>x.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
let user=null;const secret='test-owner-setup-secret-at-least-32-characters';
const env={OWNER_SETUP_HASH:createHash('sha256').update(secret).digest('hex'),DB:{prepare(query){let params=[];const stmt=sql.prepare(query);return{bind(...x){params=x;return this;},async first(){return stmt.get(...params)||null;},async all(){return{results:stmt.all(...params)};},async run(){const r=stmt.run(...params);return {success:true,meta:{changes:r.changes}};}};}}};
env.DB.batch=async statements=>{sql.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sql.exec('COMMIT');return results;}catch(error){sql.exec('ROLLBACK');throw error;}};
const cache={};function load(file){file=path.resolve(file);if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));if(cache[file])return cache[file].exports;const mod={exports:{}};cache[file]=mod;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const req=name=>{if(name==='cloudflare:workers')return {env};if(name==='@/lib/site-auth'||name==='./site-auth')return {getSiteUser:async()=>user,googleReady:()=>false,launchEnv:()=>env,siteOrigin:()=>"https://example.test"};if(name==='@/app/chatgpt-auth')return{getChatGPTUser:async()=>user};if(name.startsWith('@/'))return load(path.join(root,name.slice(2)+(name.endsWith('.json')?'':'.ts')));if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name)+(name.endsWith('.json')?'':'.ts'));return require(name);};new Function('require','module','exports',source)(req,mod,mod.exports);return mod.exports;}
const api=load(path.join(root,'app/api/action/route.ts')),dataRoute=load(path.join(root,'app/api/data/route.ts')),admin=load(path.join(root,'app/api/admin/route.ts'));
const data={GET:(request=new Request('https://example.test/api/data'))=>dataRoute.GET(request)};
async function post(action,payload,origin='https://example.test'){return api.POST(new Request('https://example.test/api/action',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify({action,payload})}));}
const proposal={city:'서울',category:'cafe',name:'검증용 카페',address:'서울 검증용 주소',source:'https://example.test/cafe',note:'테스트',notChildTarget:true,ack:true};
const review={placeId:'cj-daechung',satisfied:1,noise:'조용함',crowd:'여유로움',comfort:'편함',day:'평일',time:'오후',tags:['작은 음악']};
(async()=>{
 const {regionCamera,fullMapCamera,panCamera,zoomCamera,gestureCamera,constrainCamera,MAX_MAP_ZOOM}=load(path.join(root,'lib/atlas-camera.ts'));
 const mapGeometry=load(path.join(root,'lib/korea-map.json'));
 const jeju=mapGeometry.regions.find(r=>r.name==='제주'),seoul=mapGeometry.regions.find(r=>r.name==='서울');
 let camera=regionCamera(jeju);
 assert(camera.scale>1,'Jeju selection focuses the island');
 const dragged=panCamera(camera,100,150);assert.equal(dragged.x,camera.x+100);assert.equal(dragged.y,camera.y+150,'focused map remains draggable');
 const anchor={x:300,y:350},zoomed=zoomCamera(camera,1.1,anchor);
 assert(Math.abs((anchor.x-camera.x)/camera.scale-(anchor.x-zoomed.x)/zoomed.scale)<1e-8,'wheel zoom keeps the pointer over the same longitude');
 assert(Math.abs((anchor.y-camera.y)/camera.scale-(anchor.y-zoomed.y)/zoomed.scale)<1e-8,'wheel zoom keeps the pointer over the same latitude');
 for(let i=0;i<12;i++)camera=zoomCamera(camera,1/1.35);
 assert.deepEqual(camera,fullMapCamera(),'zooming out of Jeju always recovers the complete national map');
 assert(seoul.center[0]>=20&&seoul.center[0]<=700&&seoul.center[1]>=0&&seoul.center[1]<=710,'Seoul is reachable again in national view');
 const seoulCamera=regionCamera(seoul);assert(Math.abs(seoulCamera.x+seoul.center[0]*seoulCamera.scale-360)<1e-8,'next region selection centres Seoul');
 const pinched=gestureCamera(fullMapCamera(),[{x:260,y:355},{x:460,y:355}],[{x:260,y:405},{x:660,y:405}]);
 assert.equal(pinched.scale,2);assert.equal(pinched.x+360*pinched.scale,460);assert.equal(pinched.y+355*pinched.scale,405,'pinch combines scaling and midpoint movement');
 assert.equal(zoomCamera(pinched,100).scale,MAX_MAP_ZOOM,'zoom is bounded');
 const bounded=constrainCamera({x:1e6,y:-1e6,scale:3});assert((360-bounded.x)/3>=20&&(360-bounded.x)/3<=700&&(355-bounded.y)/3>=0&&(355-bounded.y)/3<=710,'long drags cannot lose the map');
 const {catalog}=load(path.join(root,'lib/catalog.ts'));const {regionKeys,inRegion}=load(path.join(root,'lib/regions.ts'));
 assert(catalog.length>=150,'nationwide catalog included');assert.equal(new Set(catalog.map(p=>p.id)).size,catalog.length,'unique place IDs');assert(regionKeys.every(r=>catalog.some(p=>inRegion(p,r))),'all regions have places');assert(inRegion({city:'충북',address:'충청북도 청주시 상당구'},'청주'),'Cheongju includes new provincial records');
 const usData=await (await data.GET(new Request('https://example.test/api/data?country=US'))).json();
 assert(usData.places.length>=543,'existing US places and 500 official NYC park records are available');assert(usData.places.every(p=>p.country==='US'),'US response is country scoped');
 const {matchesPlaceTheme,isPlaceTheme}=load(path.join(root,'lib/place-themes.ts'));
 const {placeDescription,placeVisitHint}=load(path.join(root,'lib/place-copy.ts'));
 const spacePlaces=catalog.filter(p=>p.experiences?.length);
 assert.equal(spacePlaces.length,4,'four source-verified venues introduce the space themes');
 assert.equal(catalog.filter(p=>matchesPlaceTheme(p,'private-room')).length,3);
 assert.equal(catalog.filter(p=>matchesPlaceTheme(p,'premium-spa')).length,2);
 assert.equal(catalog.filter(p=>matchesPlaceTheme(p,'exclusive-hire')).length,1);
 assert(matchesPlaceTheme(catalog.find(p=>p.id==='kr-yu-yuan'),'private-room'),'restaurant category and room privacy are independent');
 assert(!matchesPlaceTheme(catalog.find(p=>p.id==='us-atomix'),'private-room'),'exclusive hire and semi-private bar must not imply a room');
 assert(!matchesPlaceTheme({experiences:[{kind:'semi-private'}]},'private-room'),'a semi-private venue alone does not qualify');
 assert(!matchesPlaceTheme({themes:['premium-spa']},'private-room'),'premium price or spa theme does not establish privacy');
 assert(!matchesPlaceTheme({name:'Private room cafe'},'private-room'),'names are not privacy evidence');
 assert(!isPlaceTheme('semi-private')&&!isPlaceTheme(null)&&isPlaceTheme('private-room'),'URL themes are validated');
 for(const place of spacePlaces){
  assert(placeDescription(place,'ko')&&placeDescription(place,'en'));
  assert(placeVisitHint(place,'ko')&&placeVisitHint(place,'en'));
  for(const experience of place.experiences){assert(experience.source.startsWith('https://'));assert.equal(experience.checked,'2026-09-27');assert(experience.bookingEn&&experience.bookingKo);}
 }
 assert(usData.places.find(p=>p.id==='us-atomix').experiences.some(e=>e.kind==='semi-private'),'API preserves space types and booking evidence');
 assert(catalog.every(p=>placeDescription(p,'ko')&&placeDescription(p,'en')),'every catalog card has a bilingual summary');
 assert.equal(placeVisitHint({visitDetails:[{labelEn:'Parking',labelKo:'주차',textKo:'관광정보 안내: 불가능',textEn:'Tourism listing: parking unavailable'}]},'ko'),'','raw metadata does not become a visitor hint');
 assert.equal(placeVisitHint({},'ko'),'','cards without specific advice omit the repeated footer');
 const {matchesPlaceSearch,matchesSearchText}=load(path.join(root,'lib/place-search.ts'));
 const seoulCafe=catalog.find(p=>p.id==='tour-4108662');
 assert(matchesPlaceSearch(seoulCafe,'Seoul'),'English region searches work in the Korean interface');
 assert(matchesPlaceSearch(seoulCafe,'서울 카페'),'region and category terms combine');
 assert(matchesPlaceSearch(seoulCafe,'cafe SEOUL'),'multiple terms are case and order independent');
 assert(matchesPlaceSearch(seoulCafe,'  '),'blank search preserves the full result set');
 assert(!matchesPlaceSearch(seoulCafe,'Seoul missing-place-name'),'every search term is required');
 assert(matchesPlaceSearch({...seoulCafe,name:'수연 산방'},'수연산방'),'spacing differences do not hide a place');
 assert(matchesSearchText(['New York'],'뉴욕')&&matchesSearchText(['뉴욕'],'New York'),'international regions match in both languages');
 assert(matchesSearchText(['Tokyo'],'도쿄')&&matchesSearchText(['서울'],'Seoul'),'country search shares bilingual region matching');
 const {photoLicenseLabel}=load(path.join(root,'lib/photo-license.ts'));
 assert.equal(photoLicenseLabel('https://www.kogl.or.kr/info/licenseType1.do','ko'),'공공누리 제1유형');
 assert.equal(photoLicenseLabel('https://creativecommons.org/licenses/by-sa/3.0/','en'),'CC BY-SA 3.0');
 assert.equal(photoLicenseLabel('https://creativecommons.org/licenses/by/4.0','ko'),'CC BY 4.0');
 assert.equal(photoLicenseLabel('https://creativecommons.org/publicdomain/zero/1.0/deed.en','en'),'CC0 1.0');
 assert.equal(photoLicenseLabel('https://example.test/license','ko'),'사진 이용 허락','unknown licenses never inherit KOGL labels');
 assert(placeVisitHint({visitDetails:[{labelEn:'Solo visit',labelKo:'1인 이용',textKo:'정식은 2인 이상 주문입니다.',textEn:'Set meals require two diners.'}]},'ko').includes('2인'),'meaningful booking constraints remain visible');
 const {readBrowseState,writeBrowseState}=load(path.join(root,'lib/browse-state.ts'));
 const {emptyFilters:defaultBrowseFilters}=load(path.join(root,'lib/explore-filters.ts'));
 const browsing={city:'서울',category:'food',theme:'private-room',term:'유유안',view:'explore',filters:{...defaultBrowseFilters,photos:true,reviewed:false,quiet:false}};
 const shared=writeBrowseState(new URL('https://example.test/kr?utm_source=instagram&resume=1'),browsing,'ko');
 assert.deepEqual(readBrowseState(shared.searchParams,regionKeys),browsing,'shared URL restores region, theme, search and filters');
 assert.equal(shared.searchParams.get('utm_source'),'instagram');assert(!shared.searchParams.has('resume'));
 assert(!shared.searchParams.has('lat')&&!shared.searchParams.has('saved'),'private device state is never serialized');
 const invalid=readBrowseState(new URLSearchParams('region=oops&theme=semi-private&category=bad&view=admin&photos=true'),regionKeys);
 assert.equal(invalid.city,'전국');assert.equal(invalid.theme,'all');assert.equal(invalid.view,'explore');assert.equal(invalid.filters.photos,false);
 const cleared=writeBrowseState(shared,{...browsing,city:'전국',category:'all',theme:'all',term:'',filters:{photos:false,reviewed:false,quiet:false}},'en');
 assert.equal(cleared.search,'?utm_source=instagram&lang=en','clearing state removes stale URL choices');
 const {toggleComparison,comparisonFacts}=load(path.join(root,'lib/place-comparison.ts'));
 assert.deepEqual(toggleComparison(['a','b','c'],'d'),['a','b','c'],'at most three comparison columns');
 assert.deepEqual(toggleComparison(['a','b'],'a'),['b'],'selection toggles off');
 const emptyComparison=comparisonFacts({...catalog[0],experiences:[],visitDetails:[],count:0,quiet:0,positive:0},'ko');
 assert(emptyComparison.some(f=>f.value.includes('조용함 확인 전')),'zero reviews never implies a quietness score');
 assert(emptyComparison.some(f=>f.value==='공식 안내에서 확인 필요'),'unknown costs are explicit');
 const atomixComparison=comparisonFacts({...catalog.find(p=>p.id==='us-atomix'),count:0,quiet:0,positive:0},'en');
 assert(atomixComparison.some(f=>f.value.includes('Semi-private')),'comparison keeps venue-specific privacy types');
 const {matchesExploreFilters,emptyFilters}=load(path.join(root,'lib/explore-filters.ts'));
 const sample={image:'/test.webp',count:5,quiet:4,resting:false};
 assert(matchesExploreFilters(sample,{photos:true,reviewed:true,quiet:true}),'filters combine correctly');
 assert(!matchesExploreFilters({...sample,image:undefined},{...emptyFilters,photos:true}),'photo filter excludes missing images');
 assert(!matchesExploreFilters({...sample,count:0},{...emptyFilters,reviewed:true}),'review filter excludes unreviewed places');
 assert(!matchesExploreFilters({...sample,count:2,quiet:2},{...emptyFilters,quiet:true}),'quiet filter requires three reviews');
 assert(!matchesExploreFilters({...sample,resting:true},{...emptyFilters,quiet:true}),'paused places stay excluded from quiet results');
 assert(usData.places.every(p=>p.visitDetails.length>=2),'US places include official visit details');
 for(const p of usData.places.filter(p=>p.image))assert(fs.existsSync(path.join(root,'public',p.image)),'listed photo exists: '+p.id);
 const krData=await (await data.GET()).json();assert(krData.places.length>=324,'existing production Korea catalog preserved');assert(krData.places.every(p=>p.country==='KR'),'Korea response excludes US');
 assert.equal((await post('suggest',proposal)).status,401,'anonymous cannot write');
 env.OWNER_GOOGLE_EMAIL='mythdriveofficial@gmail.com';
 user={userId:'supabase:owner-google',email:'mythdriveofficial@gmail.com',provider:'google',googleEmailVerified:true};
 assert.equal((await admin.GET()).status,200,'configured verified Google owner can access review queue');
 assert.equal((await (await data.GET()).json()).isOwner,true);
 user={userId:'supabase:spoof',email:'mythdriveofficial@gmail.com',provider:'google',googleEmailVerified:false};
 assert.equal((await admin.GET()).status,403,'unverified owner email rejected');
 user={userId:'another-google',email:'someone@example.test',provider:'google',googleEmailVerified:true};
 assert.equal((await admin.GET()).status,403,'other Google users have no owner role');
 user={userId:'header-only',email:'mythdriveofficial@gmail.com',provider:'chatgpt',googleEmailVerified:true};
 assert.equal((await admin.GET()).status,403,'matching non-Google email does not grant new owner access');
 user=null;

 user={userId:'visitor',email:'visitor@example.test'};
 assert.equal((await post('suggest',proposal,'https://evil.test')).status,403,'cross-origin blocked');
 assert.equal((await post('suggest',{...proposal,name:'키즈카페'})).status,400,'child-target excluded');
 assert.equal((await post('suggest',{...proposal,source:'javascript:alert(1)'})).status,400,'unsafe URL rejected');
 const nationwide=await post('suggest',{...proposal,city:'제주',name:'제주 검증 카페'});assert.equal(nationwide.status,200,'nationwide suggestions accepted');
 const submitted=await (await post('suggest',proposal)).json();assert.equal(submitted.status,'pending');
 let result=await (await data.GET()).json();assert(!result.places.some(p=>p.id===submitted.id),'pending hidden');assert(result.suggestions.every(p=>p.status==='pending'));
 assert.equal((await post('decide',{id:submitted.id,status:'approved',reason:'ok',notChildTarget:true})).status,403,'non-owner approval blocked');
 assert.equal((await admin.GET()).status,403,'non-owner queue blocked');
 assert.equal((await post('review',{...review,placeId:submitted.id})).status,404,'pending review blocked');
 assert.equal((await post('review',{...review,satisfied:99})).status,400,'invalid rating blocked');
 assert.equal((await post('review',review)).status,200);
 assert.equal((await post('review',{...review,satisfied:0})).status,200);
 result=await (await data.GET()).json();assert.equal(result.places.find(p=>p.id===review.placeId).count,1,'repeat review updates');assert.equal(result.places.find(p=>p.id===review.placeId).positive,0);
 user={userId:'other',email:'other@example.test'};result=await (await data.GET()).json();assert.equal(result.reviews.length,0);assert.equal(result.suggestions.length,0,'private records not leaked');
 assert.equal((await post('deleteReview',{placeId:review.placeId})).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM reviews').get().n,1,'cannot delete another user review');
 assert.equal((await post('claimOwner',{token:'x'.repeat(40)})).status,403);
 user={userId:'owner',email:'owner@example.test'};assert.equal((await post('claimOwner',{token:secret})).status,200);
 assert.equal((await post('decide',{id:submitted.id,status:'approved',reason:'ok',notChildTarget:false})).status,400,'approval requires child-target check');
 assert.equal((await post('decide',{id:submitted.id,status:'approved',reason:'ok',notChildTarget:true})).status,200);
 result=await (await data.GET()).json();assert(result.places.some(p=>p.id===submitted.id),'approved visible');assert.equal((await admin.GET()).status,200);
 user={userId:'other',email:'other@example.test'};assert.equal((await post('claimOwner',{token:secret})).status,403,'owner cannot be reassigned');
 await post('save',{placeId:review.placeId,saved:true});result=await (await data.GET()).json();assert(result.saved.includes(review.placeId),'bookmark persists');
 const {ranked}=load(path.join(root,'lib/ranking.ts'));assert.equal(ranked([{id:'none',count:0,positive:0,quiet:0},{id:'one',count:1,positive:1,quiet:1},{id:'loud',count:4,positive:4,quiet:0}]).length,0);
 assert.equal(ranked([{id:'eligible',count:3,positive:3,quiet:3}])[0].id,'eligible');
 sql.prepare('UPDATE reviews SET updated_at=?').run(Date.now()-91*86400000);result=await (await data.GET()).json();assert.equal(result.places.find(p=>p.id===review.placeId).count,0,'old reviews excluded');
 const {distanceKm,qualityState}=load(path.join(root,'lib/discovery.ts'));assert.equal(distanceKm({lat:0,lon:0},{lat:0,lon:0}),0);assert(Math.abs(distanceKm({lat:0,lon:0},{lat:1,lon:0})-111.195)<.01);
 assert.equal(qualityState({n:7,bad:7,days:3,first:Date.now()-10*86400000,last:Date.now()}),'watch','small sample cannot pause');
 const {plans,addMonths}=load(path.join(root,'lib/plans.ts'));assert.equal(plans[1].amount,4900*6*.9);assert.equal(plans[2].amount,4900*12*.7);assert.equal(new Date(addMonths(Date.UTC(2026,0,31),1)).toISOString().slice(0,10),'2026-02-28');
 user={userId:'trial-user',email:'trial@example.test'};assert.equal((await post('trial',{})).status,200);assert.equal((await post('trial',{})).status,409);result=await (await data.GET()).json();assert(result.membership.active);assert('insights' in result.places[0]);
 sql.prepare('UPDATE trials SET started_at=? WHERE user_id=?').run(Date.now()-8*86400000,user.userId);result=await (await data.GET()).json();assert(!result.membership.active);assert(!('insights' in result.places[0]),'paid time buckets hidden from free accounts');
 const payOrder=load(path.join(root,'app/api/payments/order/route.ts')),payConfirm=load(path.join(root,'app/api/payments/confirm/route.ts'));
 const paymentRequest=(route,payload)=>route.POST(new Request('https://example.test/api/payments/test',{method:'POST',headers:{origin:'https://example.test','Content-Type':'application/json'},body:JSON.stringify(payload)}));
 assert.equal((await paymentRequest(payOrder,{planId:'month',consent:true})).status,503,'unconfigured payments disabled');
 env.TOSS_CLIENT_KEY='test_ck_mock';env.TOSS_SECRET_KEY='test_sk_mock';
 const concurrent=await Promise.all([paymentRequest(payOrder,{planId:'half',consent:true,amount:1}),paymentRequest(payOrder,{planId:'half',consent:true,amount:1})]);const orders=await Promise.all(concurrent.map(x=>x.json()));const order=orders[0];assert.equal(order.amount.value,26460,'server owns pricing');assert.equal(order.orderId,orders[1].orderId,'concurrent purchase requests reuse one pending order');
 let fetches=0;const originalFetch=global.fetch;global.fetch=async()=>{fetches++;return Response.json({orderId:order.orderId,totalAmount:26460,currency:'KRW',paymentKey:'mock-payment-key',status:'DONE'});};
 assert.equal((await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:1})).status,400);assert.equal(fetches,0,'tampered amount never reaches payment provider');
 user={userId:'foreign-user',email:'f@example.test'};assert.equal((await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:26460})).status,404);
 user={userId:'trial-user',email:'trial@example.test'};const paid=await (await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:26460})).json();assert(paid.ok);const repeated=await (await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'mock-payment-key',amount:26460})).json();assert.equal(paid.until,repeated.until);assert.equal(fetches,1,'confirmation idempotent');global.fetch=originalFetch;
 result=await (await data.GET()).json();assert.equal(result.membership.kind,'paid');
 user={userId:'quality-user',email:'q@example.test'};const now=Date.now();for(let i=0;i<8;i++)sql.prepare('INSERT INTO reviews(user_id,place_id,satisfied,noise,crowd,comfort,day,time,tags,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run('quality-'+i,'seoul-san',1,'시끄러움','붐빔','보통','평일','오후','[]',now-i*86400000);
 const {refreshQuality}=load(path.join(root,'lib/quality.ts'));await refreshQuality('seoul-san');result=await (await data.GET()).json();assert(result.places.find(p=>p.id==='seoul-san').resting);assert(!ranked(result.places).some(p=>p.id==='seoul-san'),'crowded places leave recommendation');
 sql.prepare('DELETE FROM reviews WHERE place_id=?').run('seoul-san');await refreshQuality('seoul-san');result=await (await data.GET()).json();assert(result.places.find(p=>p.id==='seoul-san').resting,'loss of evidence cannot unpause');
 assert.equal((await post('moderate',{placeId:'cj-daechung',mode:'paused'})).status,403,'moderation owner only');

 const visit=load(path.join(root,'app/api/visit/route.ts')),stats=load(path.join(root,'app/api/stats/route.ts'));
 const {koreaDay}=load(path.join(root,'lib/traffic.ts'));
 assert.equal(koreaDay(Date.UTC(2026,8,14,14,59)),'2026-09-14');
 assert.equal(koreaDay(Date.UTC(2026,8,14,15,0)),'2026-09-15','Korean calendar boundary');
 const visitRequest=origin=>new Request('https://example.test/api/visit',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:'{}'});
 assert.equal((await visit.POST(visitRequest('https://other.test'))).status,403);
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM daily_visits').get().n,0,'rejected visits not counted');
 assert.equal((await visit.POST(visitRequest('https://example.test'))).status,204);
 assert.equal((await visit.POST(visitRequest('https://example.test'))).status,204);
 assert.deepEqual(sql.prepare('PRAGMA table_info(daily_visits)').all().map(c=>c.name),['day','views'],'only aggregate visit data stored');
 user=null;assert.equal((await stats.GET()).status,403,'anonymous cannot view stats');
 user={userId:'visitor',email:'visitor@example.test'};assert.equal((await stats.GET()).status,403,'ordinary user cannot view stats');
 user={userId:'owner',email:'owner@example.test'};
 const statResponse=await stats.GET();assert.equal(statResponse.headers.get('Cache-Control'),'private, no-store');
 const report=await statResponse.json();assert.equal(report.traffic.today,2);assert.equal(report.traffic.week,2);assert.equal(report.traffic.month,2);assert.equal(report.days.length,1);
 const sitemap=load(path.join(root,'app/sitemap.xml/route.ts'));
 const xml=await sitemap.GET().text();assert(xml.includes('https://nothotplace.com/plus'));assert(xml.includes('https://nothotplace.com/trips'));assert(!xml.includes('/stats')&&!xml.includes('/login'));
 const pages=load(path.join(root,'lib/place-pages.ts'));
 const usPlace=catalog.find(p=>p.country==='US'),krPlace=catalog.find(p=>p.country==='KR');
 const sitemapGuides=load(path.join(root,'lib/guides.ts')).guides;
 assert.equal((xml.match(/<url>/g)||[]).length,(7+load(path.join(root,'lib/countries.ts')).countryCodes.length)+catalog.filter(p=>p.detailLevel!=='basic').length*2+sitemapGuides.length*2+load(path.join(root,'lib/regional-guides.ts')).regionalGuides.length*2,'place and guide pages have both language URLs');
 for(const guide of sitemapGuides)for(const language of ['ko','en'])assert(xml.includes('<loc>https://nothotplace.com/guides/'+guide.slug+'/'+language+'</loc>'));
 for(const place of catalog.filter(p=>p.detailLevel!=='basic'))for(const language of ['en','ko']){
  const url='https://nothotplace.com'+pages.placePath(place.id,language);
  assert(xml.includes('<loc>'+url+'</loc>'),'place listed in sitemap: '+place.id+' '+language);
  assert(xml.includes('hreflang="'+language+'" href="'+url+'"'),'reciprocal locale link');
 }
 assert.equal(pages.findCatalogPlace(submitted.id),undefined,'DB suggestions are not claimed as catalog pages');
 assert(pages.sharePlacePath({...krPlace,id:submitted.id},'ko').startsWith('/kr?'),'approved suggestions retain live explorer share links');
 assert.equal(pages.sharePlacePath(usPlace,'en'),pages.placePath(usPlace.id,'en'),'catalog sharing opens its independent page');
 assert.equal(new URL(pages.explorerPath(usPlace,'en'),'https://example.test').searchParams.get('place'),usPlace.id,'review return path retains selected place');
 assert(!pages.isPlaceLanguage('fr'),'unsupported languages rejected');
 assert(!pages.findCatalogPlace('not-a-real-place'),'missing places stay missing');
 assert(pages.relatedPlaces(usPlace).every(p=>p.id!==usPlace.id&&p.country===usPlace.country&&p.city===usPlace.city),'related links stay regional');

 // Detail API keeps personal state private and applies the same quality window as discovery.
 const detail=load(path.join(root,'app/api/places/[id]/route.ts'));
 const detailGet=id=>detail.GET(new Request('https://example.test/api/places/'+id),{params:Promise.resolve({id})});
 user=null;
 assert.equal((await detailGet('missing-place')).status,404);
 let detailResponse=await detailGet('cj-daechung');assert.equal(detailResponse.headers.get('Cache-Control'),'private, no-store');
 let detailData=await detailResponse.json();assert.equal(detailData.signedIn,false);assert.equal(detailData.saved,false);assert.equal(detailData.review,null);assert.deepEqual(detailData.insights,[]);
 user={userId:'detail-owner',email:'detail@example.test'};
 await post('save',{placeId:'cj-daechung',saved:true});await post('review',{...review,noise:'조용함',crowd:'여유로움'});
 detailData=await (await detailGet('cj-daechung')).json();assert.equal(detailData.saved,true);assert.equal(detailData.review.noise,'조용함');assert.equal(detailData.summary.count,1,'expired reviews excluded');assert.equal(detailData.summary.quiet,1);assert.equal(detailData.summary.relaxed,1);assert(!('user_id' in detailData.review));
 user={userId:'detail-other',email:'other-detail@example.test'};
 detailData=await (await detailGet('cj-daechung')).json();assert.equal(detailData.review,null);assert.equal(detailData.saved,false);assert.equal(detailData.summary.count,1,'aggregate remains public');
 user={userId:'detail-owner',email:'detail@example.test'};await post('deleteReview',{placeId:'cj-daechung'});detailData=await (await detailGet('cj-daechung')).json();assert.equal(detailData.summary.count,0);
 const guides=catalog.filter(p=>p.country==='KR'&&p.featured);assert.equal(guides.length,50);assert(catalog.filter(p=>p.country==='KR'&&p.image).length>=50);
 for(const p of guides){assert.equal(p.photos.length,3);assert(p.descriptionEn&&p.visitDetails.length>=4);assert.equal(new Set(p.photos.map(x=>x.original)).size,3);for(const photo of p.photos){assert(photo.original.startsWith('https://tong.visitkorea.or.kr/'));assert(photo.source===p.source);assert(fs.existsSync(path.join(root,'public',photo.src)));assert(photo.width>0&&photo.height>0);}}
 const engagement=load(path.join(root,'app/api/engagement/route.ts'));
 const engagementRequest=(body,headers={})=>new Request('https://example.test/api/engagement',{method:'POST',headers:{origin:'https://example.test','Content-Type':'application/json',...headers},body:typeof body==='string'?body:JSON.stringify(body)});
 const event={event:'place_view',country:'KR',source:'instagram'};
 assert.equal((await engagement.POST(engagementRequest(event,{origin:'https://other.test'}))).status,403);
 assert.equal((await engagement.POST(engagementRequest({...event,userId:'should-never-store'}))).status,400);
 assert.equal((await engagement.POST(engagementRequest({...event,source:'https://private.example/query'}))).status,400);
 assert.equal((await engagement.POST(engagementRequest({...event,event:'unknown'}))).status,400);
 assert.equal((await engagement.POST(engagementRequest('bad json'))).status,400);
 assert.equal((await engagement.POST(engagementRequest('x'.repeat(201)))).status,413);
 assert.equal((await engagement.POST(engagementRequest(event,{dnt:'1'}))).status,204);
 assert.equal((await engagement.POST(engagementRequest(event,{'sec-gpc':'1'}))).status,204);
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM engagement_totals').get().n,0,'privacy signals and invalid events do not count');
 await engagement.POST(engagementRequest(event));await engagement.POST(engagementRequest(event));
 assert.equal(sql.prepare('SELECT total FROM engagement_totals').get().total,2);
 assert.deepEqual(sql.prepare('PRAGMA table_info(engagement_totals)').all().map(c=>c.name),['day','event','country','source','total'],'only finite aggregate dimensions are stored');
 user={userId:'owner',email:'owner@example.test'};const engagementReport=await (await stats.GET()).json();assert.equal(engagementReport.engagement[0].total,2);

 const {restMatches,defaultRestPreferences,bestQuietTime}=load(path.join(root,'lib/rest-finder.ts'));
 const finderFixture={...catalog[0],id:'finder-open',category:'drive',visitDetails:[{labelEn:'Admission',labelKo:'입장료',textEn:'Free',textKo:'무료'}],lat:37.5,lon:127,count:0,quiet:0,positive:0};
 const blockedFixture={...finderFixture,id:'finder-paused',resting:true,count:20,quiet:20,positive:20};
 const unknownFee={...finderFixture,id:'finder-unknown-fee',visitDetails:[]};
 assert.deepEqual(restMatches([blockedFixture,finderFixture,unknownFee],{...defaultRestPreferences,budget:0}).map(match=>match.place.id),['finder-open'],'paused venues and unknown fees never pass a free-admission filter');
 assert.equal(restMatches([{...finderFixture,description:'2인 이상 주문 조건',category:'food'}],{...defaultRestPreferences,party:'solo'}).length,0,'published minimum party sizes are respected');
 assert.equal(restMatches([{...finderFixture,lat:null}],{...defaultRestPreferences,position:{lat:37.5,lon:127}}).length,0,'unknown coordinates never pass nearby filtering');
 assert.equal(bestQuietTime([{day:'평일',time:'오후',n:2,quiet:2,relaxed:2}]),null,'a tiny sample does not suggest a visiting time');
 const timeEvidence={day:'평일',time:'오후',n:5,quiet:5,relaxed:5};
 assert.equal(bestQuietTime([timeEvidence],{day:'주말·공휴일',time:'오후'}),null,'weekday feedback does not imply a weekend match');
 const rankedMatch=restMatches([{...finderFixture,insights:[timeEvidence]}],{...defaultRestPreferences,day:'평일',time:'오후'})[0];assert.equal(rankedMatch.time.day,'평일');assert.equal(rankedMatch.reviewed,false,'published information never fabricates satisfaction');
 const guideModule=load(path.join(root,'lib/guides.ts'));
 assert.equal(guideModule.guidePlaces(guideModule.findGuide('photo-guides'),catalog).length,50,'the 50-photo guide has 50 real catalog records');
 assert(guideModule.guidePlaces(guideModule.findGuide('seoul-private'),catalog).every(place=>place.experiences?.some(room=>['private-room','private-suite'].includes(room.kind))),'a semi-private area cannot appear as a private room');
 for(const guide of guideModule.guides){if(guide.kind!=='temple')assert(guideModule.guidePlaces(guide,catalog).length>0,'guide has real results: '+guide.slug);}
 const campaignEvent={event:'guide_view',country:'KR',source:'instagram',campaign:'seoul_solo'};
 assert.equal((await engagement.POST(engagementRequest({...campaignEvent,campaign:'someone@example.test'}))).status,400,'arbitrary campaign text is rejected');
 assert.equal((await engagement.POST(engagementRequest(campaignEvent))).status,204);assert.equal(sql.prepare('SELECT total FROM campaign_totals WHERE campaign=? AND event=?').get('seoul_solo','guide_view').total,1);
 assert(!sql.prepare('PRAGMA table_info(campaign_totals)').all().some(column=>/user|ip|url|place_id/.test(column.name)),'campaign totals have no identifying dimensions');
 console.log('PASS: rest matches, unknown-cost/location exclusions, evidence-only time suggestions, real guide contents and finite campaign attribution.');
 console.log('PASS: direct place review/save privacy, review freshness, 50 bilingual guides / 150 licensed Korea assets and aggregate engagement boundaries.');
 console.log('PASS: bilingual place paths, reciprocal sitemap links, community suggestion sharing and review return paths.');
 const {trips,tripThemes}=load(path.join(root,'lib/trips.ts'));assert(trips.length>=9);assert.equal(new Set(trips.map(t=>t.id)).size,trips.length);assert(Object.keys(tripThemes).every(t=>trips.filter(p=>p.theme===t).length>=3));
 for(const trip of trips.filter(t=>t.placeId)){const place=catalog.find(p=>p.id===trip.placeId);assert(place&&place.country==='KR'&&place.category===trip.category,'curated itinerary links to a matching published venue');}
 const {privateBookingFacts}=load(path.join(root,'lib/place-themes.ts'));
 const yuYuan=catalog.find(p=>p.id==='kr-yu-yuan').experiences[0];
 assert(privateBookingFacts(yuYuan,'ko')[0].value.includes('문의'),'unknown room capacity remains unknown');
 assert(privateBookingFacts(yuYuan,'en')[1].value.includes('room type'),'verified minimum-spend conditions remain visible');
 const atomix=catalog.find(p=>p.id==='us-atomix').experiences[0];
 assert(privateBookingFacts(atomix,'en')[0].value.includes('15'),'confirmed capacity is presented');
 assert(privateBookingFacts(atomix,'ko')[1].value.includes('공개 금액 없음'),'unpublished minimum spend never implies zero');
 for(const id of ['kr-osulloc-tea-stone','kr-sayuwon'])assert(!matchesPlaceTheme(catalog.find(p=>p.id===id),'private-room'),'a restful setting is not evidence of an exclusive room');
 const manifest=JSON.parse(fs.readFileSync(path.join(root,'public/manifest.webmanifest'),'utf8'));assert.equal(manifest.display,'standalone');for(const icon of manifest.icons)assert(fs.existsSync(path.join(root,'public',icon.src)));
 // Payment replay must remain bound to the payment originally verified for this user.
 user={userId:'trial-user',email:'trial@example.test'};
 assert.equal((await paymentRequest(payConfirm,{orderId:order.orderId,paymentKey:'different-payment-key',amount:26460})).status,400);
 const {reconcilePayment}=load(path.join(root,'lib/payment-service.ts'));
 const stored=sql.prepare('SELECT * FROM payment_orders WHERE id=?').get(order.orderId);
 await reconcilePayment(stored,{orderId:order.orderId,totalAmount:26460,currency:'KRW',paymentKey:'mock-payment-key',status:'CANCELED'});
 assert(!(await (await data.GET()).json()).membership.active,'refunded pass stops access after trial expiry');
 await reconcilePayment(stored,{orderId:order.orderId,totalAmount:26460,currency:'KRW',paymentKey:'mock-payment-key',status:'DONE'});
 assert(!(await (await data.GET()).json()).membership.active,'stale completion cannot restore refunded access');
 console.log('PASS: aggregate visits, Korean date boundary, stats permissions, sitemap, travel themes, install assets and payment replay/refund handling.');

 // Anonymous feedback remains a separate, bounded channel; account review rules stay intact.
 user=null;
 const quick=load(path.join(root,'app/api/quick-feedback/route.ts'));
 function quickRequest(body,cookie='',origin='https://example.test',method='POST',extra={}){return new Request('https://example.test/api/quick-feedback',{method,headers:{origin,'Content-Type':'application/json',...(cookie?{cookie}:{}),...extra},body:typeof body==='string'?body:JSON.stringify(body)});}
 const answer={placeId:'cj-daechung',noise:'조용함'};
 assert.equal((await quick.POST(quickRequest(answer,'','https://evil.test'))).status,403);
 assert.equal((await quick.POST(quickRequest({...answer,day:'unknown'}))).status,400);
 assert.equal((await quick.POST(quickRequest({...answer,placeId:'missing'}))).status,404);
 assert.equal((await quick.POST(quickRequest({...answer,userId:'spoof'}))).status,400);
 assert.equal((await quick.POST(quickRequest('x'.repeat(501)))).status,413);
 assert.equal((await quick.POST(quickRequest('bad-json'))).status,400);
 let quickResponse=await quick.POST(quickRequest(answer));assert.equal(quickResponse.status,200);
 const cookie=quickResponse.headers.get('set-cookie').split(';')[0];assert(quickResponse.headers.get('set-cookie').includes('HttpOnly; Secure; SameSite=Strict'));
 let quickSummary=await (await quick.GET(new Request('https://example.test/api/quick-feedback?place=cj-daechung',{headers:{cookie}}))).json();
 assert.equal(quickSummary.summary.count,1);assert.equal(quickSummary.mine.day,null);assert.equal(quickSummary.mine.time,null,'unknown visit times stay unknown');assert(!('actor' in quickSummary.mine));
 assert.equal((await post('review',review)).status,401,'one-tap permission never grants account-review permission');
 assert.equal((await quick.POST(quickRequest({...answer,noise:'シズカ'},cookie))).status,400);
 assert.equal((await quick.POST(quickRequest({...answer,noise:'시끄러움',day:'평일'},cookie))).status,200);
 quickSummary=await (await quick.GET(new Request('https://example.test/api/quick-feedback?place=cj-daechung',{headers:{cookie}}))).json();assert.equal(quickSummary.summary.count,1,'same browser updates, not duplicate votes');assert.equal(quickSummary.summary.loud,1);assert.equal(quickSummary.mine.time,null);
 detailData=await (await detailGet('cj-daechung')).json();assert.equal(detailData.summary.count,0,'guest reactions cannot inflate account statistics');assert.equal(detailData.bestTime,null,'guest reactions cannot manufacture time recommendations');
 const otherQuick=await quick.POST(quickRequest(answer)),otherCookie=otherQuick.headers.get('set-cookie').split(';')[0];
 await quick.DELETE(quickRequest({placeId:'cj-daechung'},cookie,'https://example.test','DELETE'));quickSummary=await (await quick.GET(new Request('https://example.test/api/quick-feedback?place=cj-daechung'))).json();assert.equal(quickSummary.summary.count,1,'browser can only delete its own response');
 for(let i=0;i<11;i++)assert.equal((await quick.POST(quickRequest(answer,otherCookie))).status,200);
 assert.equal((await quick.POST(quickRequest(answer,otherCookie))).status,429,'daily per-browser cap enforced');
 sql.prepare('UPDATE quick_feedback SET updated_at=?').run(Date.now()-91*86400000);quickSummary=await (await quick.GET(new Request('https://example.test/api/quick-feedback?place=cj-daechung'))).json();assert.equal(quickSummary.summary.count,0,'expired responses are not public');
 sql.prepare('INSERT INTO quick_feedback_limits(day,actor,total) VALUES(?,?,1)').run('2020-01-01','expired-limit');
 assert.equal((await quick.POST(quickRequest(answer,'','https://example.test','POST',{'cf-connecting-ip':'192.0.2.1'}))).status,200);
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM quick_feedback_limits WHERE day=?').get('2020-01-01').n,0,'old limit hashes removed');assert(!sql.prepare('SELECT actor FROM quick_feedback_limits').all().some(r=>r.actor.includes('192.0.2.1')),'raw IP not persisted');
 const {parseJournal}=load(path.join(root,'lib/rest-journal.ts'));assert.deepEqual(parseJournal('corrupt'),[]);assert.deepEqual(parseJournal(JSON.stringify([{placeId:'unknown',state:'visited',at:Date.now()}])),[]);assert.equal(parseJournal(JSON.stringify([{placeId:'cj-daechung',state:'planned',at:Date.now()},{placeId:'cj-daechung',state:'visited',at:Date.now()}])).length,1,'journal normalizes duplicates');assert(!('userId' in parseJournal(JSON.stringify([{placeId:'cj-daechung',state:'planned',at:Date.now(),userId:'ignored'}]))[0]));
 const jpData=await (await data.GET(new Request('https://example.test/api/data?country=JP'))).json();assert.equal(jpData.places.length,30);assert(jpData.places.every(p=>p.country==='JP'&&p.category==='walk'&&p.visitDetails.length>=3));
 const {mapPath,explorerPath}=load(path.join(root,'lib/place-pages.ts'));assert(mapPath(jpData.places[0]).startsWith('https://www.google.com/maps'));assert(explorerPath(jpData.places[0],'ko').startsWith('/jp?'));
 const {regionalGuides,regionalPlaces}=load(path.join(root,'lib/regional-guides.ts'));assert.equal(regionalGuides.length,23);assert(regionalGuides.every(g=>regionalPlaces(g,catalog).length>0),'every regional landing has real catalog content');
 assert(regionalPlaces(regionalGuides.find(g=>g.slug==='new-york'),catalog).length>=15);assert(regionalPlaces(regionalGuides.find(g=>g.slug==='portland'),catalog).length>=15);
 assert(restMatches(jpData.places,{...defaultRestPreferences,purpose:'drive'}).length>0,'scenery purpose includes walking gardens');
 assert.equal((await engagement.POST(engagementRequest({event:'quick_review',country:'JP',source:'direct'}))).status,204,'new actions and country allowed by migrated aggregate schema');
 const regionalSitemap=load(path.join(root,'app/sitemap.xml/route.ts')).GET();const regionalSitemapText=await regionalSitemap.text();assert(regionalSitemapText.includes('/jp</loc>'));assert(regionalSitemapText.includes('/regions/tokyo/ko'));assert(regionalSitemapText.includes('/places/jp-tokyo-20/en'));assert(!regionalSitemapText.includes('/journal'));
 console.log('PASS: anonymous input limits, cookie isolation, expiry, guest/account separation, local journal validation, 30 Japan venues, 23 populated regional guides and new-country sitemap.');

 {
 // Published facts and external notes never manufacture first-party review evidence.
 const {conditionKeys,matchesCondition,conditionEvidence}=load(path.join(root,'lib/rest-conditions.ts'));
 assert(!matchesCondition({name:'Quiet private book cafe'},'books'),'place names do not establish a condition');
 assert(!matchesCondition({restFeedback:{quietMusic:2}},'quietMusic'),'two reports do not qualify');
 assert(matchesCondition({restFeedback:{quietMusic:3}},'quietMusic'));
 assert(!matchesCondition({restFeedback:{quietMusic:3},resting:true},'quietMusic'),'held venues cannot qualify through stale positive feedback');
 assert.equal(conditionEvidence({restFeedback:{quietMusic:3}},'quietMusic','ko').source,'','account feedback is not a published source');
 assert(conditionKeys.every(key=>typeof emptyFilters[key]==='boolean'),'every condition has a validated URL filter');
 const conditionUrl=writeBrowseState(new URL('https://example.test/kr'),{...browsing,filters:{...emptyFilters,books:true,soloOrder:true,quiet:true}},'ko');
 assert.equal(readBrowseState(conditionUrl.searchParams,regionKeys).filters.soloOrder,true);
 assert(!readBrowseState(new URLSearchParams('books=yes&quietMusic=1&actor=private'),regionKeys).filters.books);
 const conditionsBook=catalog.filter(p=>matchesCondition(p,'books'));assert.equal(conditionsBook.length,4);assert(conditionsBook.every(p=>p.conditions.find(f=>f.kind==='books').source.startsWith('https://')));
 const memos=catalog.filter(p=>p.externalMemo);assert.equal(memos.length,22);assert(memos.every(p=>p.externalMemo.periodKo&&p.externalMemo.periodEn&&p.externalMemo.sources.every(s=>s.url.startsWith('https://'))));
 const {externalReviewLinks}=load(path.join(root,'lib/external-reviews.ts'));
 assert.equal(externalReviewLinks(catalog.find(p=>p.id==='cj-daechung')).length,3);
 assert(externalReviewLinks(catalog.find(p=>p.id==='us-stumptown-division')).some(s=>s.name==='Yelp'));
 assert(Object.keys(load(path.join(root,'lib/location-catalog.json'))).every(id=>catalog.find(p=>p.id===id)?.locationInfo?.kind==='reference'),'existing tourism map reference points are retained and never presented as entrances');
 assert(guideModule.guidePlaces(guideModule.findGuide('cheongju-parking-cafes'),catalog).length>=2,'parking guide has real sourced candidates');
 assert(guideModule.guides.filter(g=>g.kind==='intent').every(g=>guideModule.guidePlaces(g,catalog).length>0),'new intent guides are populated');
 const {storySelection,storyCaption}=load(path.join(root,'lib/story-card.ts'));
 const storyRecords=catalog.slice(0,4).map((p,i)=>({placeId:p.id,state:i?'visited':'planned',noise:'조용함',at:Date.now()}));
 assert.equal(storySelection(storyRecords,[storyRecords[0].placeId,storyRecords[0].placeId,'unknown',storyRecords[1].placeId],catalog).length,2);
 assert.equal(storySelection(storyRecords,storyRecords.map(r=>r.placeId),catalog).length,3);
 assert(!storyCaption(storyRecords[0],'ko',true).includes('조용함'),'a planned visit cannot imply observed noise');
 assert(!storyCaption(storyRecords[1],'ko',false).includes('조용함'),'noise remains optional');
 assert(storyCaption(storyRecords[1],'en',true).includes('Quiet'));
 for(let i=0;i<3;i++){user={userId:'condition-user-'+i,email:'condition-'+i+'@example.test'};assert.equal((await post('review',{...review,placeId:'seoul-suyeon',tags:['칸막이 좌석','혼자 주문','셀프 주문','칸막이 좌석']})).status,200);}
 user=null;let conditionData=await (await detailGet('seoul-suyeon')).json();assert.equal(conditionData.restFeedback.partitions,3,'duplicate tags cannot inflate the number of reviewers');assert.equal(conditionData.restFeedback.selfOrder,3);assert(!conditionData.plus);
 result=await (await data.GET()).json();assert(matchesExploreFilters(result.places.find(p=>p.id==='seoul-suyeon'),{...emptyFilters,partitions:true,quiet:true}),'free API exposes supported condition and quiet evidence');
 sql.prepare('UPDATE reviews SET updated_at=? WHERE user_id=?').run(Date.now()-91*86400000,'condition-user-0');conditionData=await (await detailGet('seoul-suyeon')).json();assert.equal(conditionData.restFeedback.partitions,2);assert(!matchesCondition(conditionData,'partitions'),'expired reviewer evidence stops qualifying');

 // Anonymous information reports are isolated, bounded, private and manually moderated.
 const reports=load(path.join(root,'app/api/place-reports/route.ts'));
 const report={placeId:'cj-daechung',kind:'parking',note:'검증용 주차 정보 확인 요청'};
 assert.equal((await reports.POST(quickRequest(report,'','https://evil.test'))).status,403);
 assert.equal((await reports.POST(quickRequest({...report,placeId:'missing'}))).status,404);
 assert.equal((await reports.POST(quickRequest({...report,actor:'spoof'}))).status,400);
 assert.equal((await reports.POST(quickRequest({...report,note:'x'.repeat(401)}))).status,400);
 let reportResponse=await reports.POST(quickRequest(report,'','https://example.test','POST',{'cf-connecting-ip':'192.0.2.8'}));assert.equal(reportResponse.status,200);
 const reportCookie=reportResponse.headers.get('set-cookie').split(';')[0];assert(reportResponse.headers.get('set-cookie').includes('HttpOnly; Secure; SameSite=Strict'));
 assert.equal((await reports.POST(quickRequest({...report,note:'갱신된 제보'},reportCookie))).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM place_reports').get().n,1,'same browser and issue updates the existing report');
 const secondReport=await reports.POST(quickRequest(report)),secondReportCookie=secondReport.headers.get('set-cookie').split(';')[0];
 assert.equal((await reports.DELETE(quickRequest({},reportCookie,'https://evil.test','DELETE'))).status,403);
 await reports.DELETE(quickRequest({},reportCookie,'https://example.test','DELETE'));assert.equal(sql.prepare('SELECT COUNT(*) n FROM place_reports').get().n,1,'only this browser’s reports are deleted');
 for(let i=0;i<4;i++)assert.equal((await reports.POST(quickRequest(report,secondReportCookie))).status,200);
 assert.equal((await reports.POST(quickRequest(report,secondReportCookie))).status,429,'report cap is separate from noise votes');
 assert(sql.prepare('SELECT actor FROM place_reports').all().every(r=>/^[a-f0-9]{64}$/.test(r.actor)),'reports store keyed pseudonyms');
 assert(!sql.prepare('SELECT actor FROM quick_feedback_limits').all().some(r=>r.actor.includes('192.0.2.8')),'raw report IP is not retained');

 // Public identity is opt-in; approval, withdrawal and deletion enforce the same rule.
 const community=load(path.join(root,'app/api/community/route.ts')),communityAdmin=load(path.join(root,'app/api/community/admin/route.ts'));
 const communityRequest=(payload,origin='https://example.test')=>new Request('https://example.test/api/community',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(payload)});
 const profile={action:'profile',name:'서울 쉼 발견자',country:'KR',region:'서울',link:'https://example.test/public',bio:'지역의 쉬어갈 장소를 모아요.',consent:true};
 assert.equal((await community.POST(communityRequest(profile))).status,401);assert.equal((await communityAdmin.GET()).status,403);
 user={userId:'visitor',email:'visitor@example.test'};
 assert.equal((await community.POST(communityRequest(profile,'https://evil.test'))).status,403);
 assert.equal((await community.POST(communityRequest({...profile,consent:false}))).status,400);
 assert.equal((await community.POST(communityRequest({...profile,link:'javascript:alert(1)'}))).status,400);
 assert.equal((await community.POST(communityRequest({...profile,link:'https://name:password@example.test/'}))).status,400);
 assert.equal((await community.POST(communityRequest({...profile,region:'missing'}))).status,400);
 assert.equal((await community.POST(communityRequest(profile))).status,200);
 let communityData=await (await community.GET()).json();const profileId=communityData.profile.id;assert.equal(communityData.profiles.length,0);assert.equal(communityData.profile.status,'pending');assert(!('user_id' in communityData.profile));
 const collection={action:'collection',title:'서울에서 쉬어갈 두 곳',country:'KR',region:'서울',placeIds:['seoul-suyeon','seoul-sueno'],note:'좌석과 음악을 비교하고 방문일 영업 정보를 확인해 보세요.'};
 assert.equal((await community.POST(communityRequest({...collection,placeIds:['seoul-suyeon','us-stumptown-division']}))).status,400);
 assert.equal((await community.POST(communityRequest({...collection,placeIds:['seoul-suyeon','seoul-suyeon']}))).status,400);
 assert.equal((await community.POST(communityRequest(collection))).status,200);communityData=await (await community.GET()).json();const collectionId=communityData.ownCollections[0].id;assert.equal(communityData.collections.length,0);
 assert.equal((await communityAdmin.POST(communityRequest({action:'profile',id:profileId,status:'approved',reason:''}))).status,403);
 user={userId:'unrelated',email:'unrelated@example.test'};await community.POST(communityRequest({action:'cancel',id:collectionId}));assert.equal(sql.prepare('SELECT COUNT(*) n FROM contributor_collections WHERE id=?').get(collectionId).n,1,'foreign collection cannot be removed');await community.POST(communityRequest({action:'deleteProfile'}));assert.equal(sql.prepare('SELECT COUNT(*) n FROM contributor_profiles WHERE id=?').get(profileId).n,1);
 user={userId:'owner',email:'owner@example.test'};
 assert.equal((await communityAdmin.POST(communityRequest({action:'collection',id:collectionId,status:'approved',reason:''}))).status,400,'collection approval requires approved consenting profile');
 assert.equal((await communityAdmin.POST(communityRequest({action:'profile',id:profileId,status:'approved',reason:''}))).status,200);
 assert.equal((await communityAdmin.POST(communityRequest({action:'profile',id:profileId,status:'approved',reason:''}))).status,409,'duplicate decisions are rejected');
 assert.equal((await communityAdmin.POST(communityRequest({action:'collection',id:collectionId,status:'approved',reason:''}))).status,200);
 let moderation=await (await communityAdmin.GET()).json();assert(moderation.reports.every(r=>!('actor' in r)));const reportId=moderation.reports[0].id;
 assert.equal((await communityAdmin.POST(communityRequest({action:'report',id:reportId,status:'resolved'}))).status,200);assert.equal(sql.prepare('SELECT status FROM place_reports WHERE id=?').get(reportId).status,'resolved');
 user=null;communityData=await (await community.GET()).json();assert.equal(communityData.profiles.length,1);assert.equal(communityData.collections.length,1);assert.equal(communityData.profile,null);assert.equal(communityData.ownCollections.length,0);assert(communityData.collections.every(p=>!('user_id' in p)));assert(!JSON.stringify(communityData).includes('visitor@example.test'),'account email is never public');
 result=await (await data.GET()).json();assert.equal(result.places.find(p=>p.id===submitted.id).contributor.name,profile.name,'approved listing credits only consenting public identity');
 user={userId:'visitor',email:'visitor@example.test'};assert.equal((await community.POST(communityRequest({...profile,name:'서울 쉼 발견자 수정'}))).status,200);assert.equal((await (await community.GET()).json()).profile.id,profileId,'profile edit preserves public ID');user=null;assert.equal((await (await community.GET()).json()).collections.length,0,'profile edits hide published collections until review');
 user={userId:'owner',email:'owner@example.test'};assert.equal((await communityAdmin.POST(communityRequest({action:'profile',id:profileId,status:'approved',reason:''}))).status,200);
 user={userId:'visitor',email:'visitor@example.test'};await community.POST(communityRequest({action:'withdraw'}));user=null;communityData=await (await community.GET()).json();assert.equal(communityData.collections.length,0);assert.equal(communityData.profiles.length,0);result=await (await data.GET()).json();assert(!result.places.find(p=>p.id===submitted.id).contributor,'withdrawing hides listing credit too');
 user={userId:'owner',email:'owner@example.test'};assert.equal((await communityAdmin.POST(communityRequest({action:'profile',id:profileId,status:'approved',reason:''}))).status,409,'withdrawn consent cannot be overridden');
 user={userId:'visitor',email:'visitor@example.test'};assert.equal((await community.POST(communityRequest({action:'deleteProfile'}))).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM contributor_profiles WHERE id=?').get(profileId).n,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM contributor_collections WHERE id=?').get(collectionId).n,0,'profile and collections delete together');
 sql.prepare('UPDATE place_reports SET updated_at=?').run(Date.now()-91*86400000);user={userId:'owner',email:'owner@example.test'};await communityAdmin.GET();assert.equal(sql.prepare('SELECT COUNT(*) n FROM place_reports').get().n,0,'expired reports are purged');
 console.log('PASS: sourced conditions, unique recent reviewer evidence, story selection/privacy, bounded private reports, opt-in contributor identity, moderation permissions, withdrawal and atomic deletion.');
 }
 {
 const {countryCodes,countries}=load(path.join(root,'lib/countries.ts'));
 const expanded=load(path.join(root,'lib/expanded-catalog.json'));
 const manifest=load(path.join(root,'lib/catalog-source-manifest.json'));
 assert.equal(countryCodes.length,30);assert.equal(catalog.length,1006);assert.equal(expanded.length,605);
 assert.equal(new Set(manifest.map(p=>p.id)).size,605);
 assert(expanded.every(p=>manifest.some(m=>m.id===p.id&&m.country===p.country)),'every new record has source provenance');
 for(const country of countryCodes){const response=await (await data.GET(new Request('https://example.test/api/data?country='+country))).json();assert(response.places.length>0);assert(response.places.every(p=>p.country===country),'all 30 API views are country scoped');assert(countries[country].regions.includes(countries[country].defaultRegion));}
 for(const p of expanded){assert(p.visitDetails.length>=1&&p.source.startsWith('https://'),'source information exists even when access facts remain unknown');if(p.lat!=null)assert(Number.isFinite(p.lat)&&Math.abs(p.lat)<=90&&Number.isFinite(p.lon)&&Math.abs(p.lon)<=180&&p.locationInfo.kind==='reference','new coordinates are bounded reference points, not verified entrances');}
 const {visitFacts}=load(path.join(root,'lib/visit-facts.ts'));
 const fixture={...catalog[0],visitFacts:undefined,conditions:[],visitDetails:[]};
 assert.equal(visitFacts(fixture).parking,undefined,'unknown parking must not imply unavailable');
 assert.equal(visitFacts({...fixture,visitDetails:[{labelEn:'Parking',textKo:'주차 불가능',textEn:'Parking unavailable'}]}).parking.status,'unavailable');
 assert.equal(visitFacts({...fixture,visitDetails:[{labelEn:'Parking',textKo:'인근 공영 주차',textEn:'Nearby public parking'}]}).parking.status,'nearby');
 const seats=visitFacts({...fixture,visitDetails:[{labelEn:'Seating',textKo:'1인석과 4인석',textEn:'Individual seats and 4-seat tables'}]}).seating;
 assert.equal(seats.solo,true);assert.equal(seats.group,true);assert.deepEqual(seats.groupSizes,[4]);
 assert.equal(visitFacts({...fixture,visitDetails:[{labelEn:'Seating',textKo:'1인석 없음',textEn:'No individual seats'}]}).seating,undefined);
 const {publishedCost}=load(path.join(root,'lib/rest-finder.ts'));
 const price={source:fixture.source,checked:fixture.checked,amount:0,currency:'KRW',textKo:'무료',textEn:'Free'};
 assert.equal(publishedCost({...fixture,visitFacts:{price:{...price,basis:'menu'}}}),null,'a free menu item never implies free admission');
 assert.equal(publishedCost({...fixture,visitFacts:{price:{...price,basis:'experience'}}}),null);
 assert.equal(publishedCost({...fixture,visitFacts:{price:{...price,basis:'admission'}}}).amount,0);

 const contribution=load(path.join(root,'app/api/place-contributions/route.ts'));
 const moderation=load(path.join(root,'app/api/community/admin/route.ts'));
 const req=(body,cookie='',extra={},method='POST')=>new Request('https://example.test/api/place-contributions',{method,headers:{origin:'https://example.test','Content-Type':'application/json',...(cookie?{cookie}:{}),...extra},body:typeof body==='string'?body:JSON.stringify(body)});
 const input={placeId:'world-gb-hyde-park',note:'Seats along the walking path',sourceUrl:'https://www.royalparks.org.uk/visit/parks/hyde-park',photoUrl:'',rightsConsent:false};
 user=null;
 assert.equal((await contribution.POST(req(input,'',{origin:'https://other.test'}))).status,403);
 assert.equal((await contribution.POST(req(input,'',{'sec-fetch-site':'cross-site'}))).status,403);
 assert.equal((await contribution.POST(req(input,'',{'Content-Type':'text/plain'}))).status,415);
 assert.equal((await contribution.POST(req({...input,placeId:'missing'}))).status,404);
 assert.equal((await contribution.POST(req({...input,actor:'spoof'}))).status,400);
 assert.equal((await contribution.POST(req('broken json'))).status,400);
 assert.equal((await contribution.POST(req('x'.repeat(3501)))).status,413);
 for(const url of ['http://example.test','https://name:password@example.test','https://localhost','https://127.0.0.1','https://10.0.0.1','https://[::1]','https://2130706433','https://169.254.169.254'])assert.equal((await contribution.POST(req({...input,sourceUrl:url}))).status,400,'unsafe contribution URL: '+url);
 assert.equal((await contribution.POST(req({...input,photoUrl:'https://example.test/my-photo.webp'}))).status,400,'photo publication requires explicit rights consent');
 const submittedPhoto=await contribution.POST(req({...input,photoUrl:'https://example.test/my-photo.webp',rightsConsent:true},'',{'cf-connecting-ip':'192.0.2.33'}));assert.equal(submittedPhoto.status,200);
 const photoCookie=submittedPhoto.headers.get('set-cookie').split(';')[0];assert(submittedPhoto.headers.get('set-cookie').includes('HttpOnly; Secure; SameSite=Strict'));
 const row=sql.prepare('SELECT * FROM place_contributions').get();assert.equal(row.status,'pending');assert(/^[a-f0-9]{64}$/.test(row.actor));assert.equal(row.rights_consent,1);
 assert(!sql.prepare('SELECT actor FROM quick_feedback_limits').all().some(p=>p.actor.includes('192.0.2.33')),'contribution IPs are keyed pseudonyms');
 assert.equal((await moderation.GET()).status,403,'anonymous users cannot read private contribution notes');
 const publicData=JSON.stringify(await (await data.GET(new Request('https://example.test/api/data?country=GB'))).json());assert(!publicData.includes(input.note)&&!publicData.includes('my-photo.webp'),'pending notes and photos never enter public listings');
 const other=await contribution.POST(req(input)),otherCookie=other.headers.get('set-cookie').split(';')[0];
 assert.equal((await contribution.DELETE(req({},photoCookie,{origin:'https://evil.test'},'DELETE'))).status,403);
 await contribution.DELETE(req({},photoCookie,{},'DELETE'));assert.equal(sql.prepare('SELECT COUNT(*) n FROM place_contributions').get().n,1,'withdrawal only deletes this browser’s contributions');
 for(let i=0;i<4;i++)assert.equal((await contribution.POST(req(input,otherCookie))).status,200);
 assert.equal((await contribution.POST(req(input,otherCookie))).status,429,'five contributions per browser/day');
 user={userId:'owner',email:'owner@example.test'};
 const queue=await (await moderation.GET()).json();assert.equal(queue.contributions.length,5);assert(queue.contributions.every(p=>!('actor' in p)));
 const decision={action:'contribution',id:queue.contributions[0].id,status:'reviewed'};
 assert.equal((await moderation.POST(req(decision))).status,200);assert.equal((await moderation.POST(req(decision))).status,409);
 assert(!JSON.stringify(await (await data.GET(new Request('https://example.test/api/data?country=GB'))).json()).includes(input.note),'a reviewed decision does not auto-publish source claims');
 sql.prepare('UPDATE place_contributions SET updated_at=?').run(Date.now()-91*86400000);await moderation.GET();assert.equal(sql.prepare('SELECT COUNT(*) n FROM place_contributions').get().n,0,'expired contributions are removed after 90 days');
 user=null;
 for(let i=0;i<30;i++)assert.equal((await contribution.POST(req(input,'',{'cf-connecting-ip':'192.0.2.34'}))).status,200);
 assert.equal((await contribution.POST(req(input,'',{'cf-connecting-ip':'192.0.2.34'}))).status,429,'rotating browser cookies cannot bypass the IP daily cap');
 assert.throws(()=>sql.prepare("INSERT INTO place_contributions VALUES('test','test','test','test','','https://example.test/p.webp',0,'pending',0,0)").run(),/CHECK/,'photo rights are also enforced in the database');
 const legacy=new DatabaseSync(':memory:');const migrations=fs.readdirSync(path.join(root,'drizzle')).filter(x=>x.endsWith('.sql')).sort();
 for(const file of migrations.filter(x=>x<'0008'))legacy.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
 legacy.exec("INSERT INTO engagement_totals VALUES('2026-10-01','save','KR','instagram',9); INSERT INTO campaign_totals VALUES('2026-10-01','guide_view','US','instagram','us_slow',7); INSERT INTO contributor_profiles VALUES('legacy-user','legacy-id','Legacy','서울','KR','','',1,'approved','',1); INSERT INTO contributor_collections VALUES('legacy-list','legacy-user','Legacy list','KR','서울','[]','','approved','',1,1);");
 const tables=['engagement_totals','campaign_totals','contributor_profiles','contributor_collections'];const snapshots=tables.map(t=>legacy.prepare('SELECT * FROM '+t).all());
 for(const file of migrations.filter(x=>x>='0008'))legacy.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
 tables.forEach((table,i)=>assert.deepEqual(legacy.prepare('SELECT * FROM '+table).all(),snapshots[i],'world migration retains '+table));
 legacy.exec("INSERT INTO engagement_totals VALUES('2026-10-02','save','SG','direct',1)");assert.throws(()=>legacy.exec("INSERT INTO engagement_totals VALUES('2026-10-02','save','sg','direct',1)"),/CHECK/);legacy.close();
 console.log('PASS: 30 country scopes, 1,006 unique places, source/reference integrity, unknown parking, seat sizes, admission semantics, private consent-based contributions, actor/IP limits, withdrawal, moderation, expiry and migration data preservation.');
 }
 console.log('PASS: trial expiry, premium gating, distance, prices, payment integrity/idempotency, automatic recommendation hold,  nationwide catalog, regional filtering, authorization, owner binding, approval visibility, persistence, input validation, review deduplication, 90-day aggregation, recommendation eligibility.');
})().catch(e=>{console.error(e);process.exitCode=1;});
